/* العربية */
export default {
  "Condomínio": "المجمّع السكني", "Unidades": "الوحدات", "Pessoas": "الأشخاص", "Financeiro": "المالية",
  "Cobranças QR": "مدفوعات QR", "Multas": "الغرامات", "Comunicados": "الإعلانات", "Documentos": "المستندات",
  "Manutenção": "الصيانة", "Portaria": "الاستقبال", "Gerenciar Acessos": "إدارة الحسابات", 
  "Visão geral do condomínio em tempo real": "نظرة عامة على المجمّع في الوقت الفعلي",
  "Cadastro-mãe: dados legais, gestão e regras internas": "السجل الرئيسي: البيانات القانونية والإدارة والقواعد الداخلية",

  /* subtítulos dinâmicos do cabeçalho */
  "unidade": "وحدة", "unidades": "وحدات", "bloco/torre": "مبنى/برج", "blocos/torres": "مبانٍ/أبراج",
  "pessoa cadastrada": "شخص مسجّل", "pessoas cadastradas": "أشخاص مسجّلون",
  "aprovações do síndico ativas": "موافقات المدير مفعّلة",
  "cobrança em aberto": "دفعة مستحقة", "cobranças em aberto": "دفعات مستحقة", "vencidas": "متأخرة",
  "multa/advertência registrada": "غرامة/إنذار مسجّل", "multas/advertências registradas": "غرامات/إنذارات مسجّلة",
  "comunicado publicado": "تعميم منشور", "comunicados publicados": "تعاميم منشورة",
  "documento arquivado": "مستند مؤرشف", "documentos arquivados": "مستندات مؤرشفة",
  "chamado em aberto": "طلب صيانة مفتوح", "chamados em aberto": "طلبات صيانة مفتوحة",
  /* teste gratuito de 30 dias */
  "Ative seu teste gratuito de 30 dias — cadastre o cartão; nada será cobrado agora.": "فعّل تجربتك المجانية لمدة 30 يومًا — سجّل البطاقة؛ لن يُخصم شيء الآن.",
  "O período de avaliação terminou. Ative a assinatura para continuar.": "انتهت فترة التجربة. فعّل الاشتراك للمتابعة.",
  "Iniciar teste gratuito de 30 dias": "بدء التجربة المجانية لمدة 30 يومًا",

  "A troca de plano durante o teste gratuito é cobrada imediatamente — aguarde o fim do teste para trocar.": "تغيير الباقة أثناء التجربة المجانية يُحصَّل فورًا — انتظر انتهاء التجربة للتغيير.",
  "Teste gratuito — termina em": "التجربة المجانية — تنتهي خلال", "dia(s)": "يوم/أيام",
  "Depois, a cobrança é feita automaticamente no cartão cadastrado.": "بعد ذلك يتم الخصم تلقائيًا من البطاقة المسجّلة.",

  "Tenho um código de ativação": "لدي رمز تفعيل", "Código de ativação": "رمز التفعيل",
  "Ativar": "تفعيل", "Ativando…": "جارٍ التفعيل…",

  "Código aplicado. Se o acesso não liberar em instantes, use \"Já paguei — verificar\".": "تم تطبيق الرمز. إذا لم يُفتح الوصول خلال لحظات، استخدم \"Já paguei — verificar\".",

  "Cancelar assinatura": "إلغاء الاشتراك",
  "Cancelar a assinatura? O acesso continua até o fim do período já pago e nenhuma cobrança futura será feita.": "إلغاء الاشتراك؟ يستمر الوصول حتى نهاية الفترة المدفوعة ولن تُخصم أي مبالغ مستقبلًا.",
  "Cancelamento agendado — o acesso continua até": "تم جدولة الإلغاء — يستمر الوصول حتى",
  "Assinatura cancelada.": "تم إلغاء الاشتراك.",
  "Assinatura cancelada em": "تم إلغاء الاشتراك في", "o acesso será desativado em": "سيتم إيقاف الوصول في",
  "Nenhuma cobrança futura será feita.": "لن تُخصم أي مبالغ مستقبلًا.",
  "Acima da franquia do plano": "تجاوز الحد المشمول في الباقة",
  "o excedente é cobrado por unidade adicional na fatura da licença.": "يُحتسب الفائض عن كل وحدة إضافية في فاتورة الترخيص.",

  "Controle de acessos, entregas e ocorrências": "إدارة الدخول والطرود والحوادث",

  "Notificações": "الإشعارات", "Alternar tema": "تبديل المظهر", "Idioma": "اللغة", "Perfil de acesso": "دور الوصول",
  "Diretor": "المدير العام", "Síndico": "مدير المبنى", "Tesouraria": "المحاسبة", "Administradora": "شركة الإدارة", "Morador": "ساكن",
  "Visão estratégica, aprovações e auditoria": "رؤية استراتيجية وموافقات وتدقيق",
  "Operação, multas, comunicados e manutenção": "التشغيل والغرامات والإعلانات والصيانة",
  "Financeiro, cobranças e conciliação": "المالية والمدفوعات والمطابقة",

  "Boletos, comprovantes, comunicados e chamados": "الفواتير والإيصالات والإعلانات والطلبات",
  "Gestão condominial premium · powered by Serve Now Global": "إدارة مجمّعات سكنية متميزة · powered by Serve Now Global",
  "Criar acesso do diretor": "إنشاء حساب المدير العام",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "هذا هو الدخول الأول. سيُستخدم الحساب الذي تنشئه هنا لتسجيل الدخول بدور",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Acessos.": "، وسيتمكن من تسجيل بيانات دخول باقي الأدوار في «إدارة الحسابات».",
  "Nome completo": "الاسم الكامل", "E-mail": "البريد الإلكتروني", "Senha": "كلمة المرور", "Confirmar senha": "تأكيد كلمة المرور",
  "Criar conta e continuar": "إنشاء الحساب والمتابعة",
  "Já tem prédio cadastrado? Fazer login": "لديك مبنى مسجّل بالفعل؟ تسجيل الدخول",
  "Entrar como": "تسجيل الدخول بدور", "Trocar perfil": "تغيير الدور", "Voltar ao cadastro": "العودة إلى التسجيل",
  "Entrar": "دخول", "Verificando conta...": "جارٍ التحقق من الحساب...",
  "E-mail ou senha incorretos.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Acessos.": "البريد الإلكتروني أو كلمة المرور غير صحيحة. اطلب من المدير التحقق من حسابك في «إدارة الحسابات».",

  "Não foi possível verificar sua conta agora.": "تعذّر التحقق من حسابك الآن.",

  "As senhas não conferem.": "كلمتا المرور غير متطابقتين.",
  "Nenhum acesso de": "لا يوجد حساب لدور",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Acessos.": "حتى الآن. اطلب من المدير إنشاءه في «إدارة الحسابات».",
  "Tema claro": "مظهر فاتح", "Tema escuro": "مظهر داكن",

  "Seu nome": "اسمك", "voce@exemplo.com": "you@example.com", "Repita a senha": "أعد إدخال كلمة المرور",
  "Saldo em caixa": "الرصيد النقدي", "Inadimplência": "نسبة التأخر في السداد", "Receitas de": "إيرادات", "Despesas de": "مصروفات",
  "Nova cobrança": "دفعة جديدة", "Novo gasto": "مصروف جديد", "Nova multa": "غرامة جديدة", "Novo comunicado": "إعلان جديد", "Novo chamado": "طلب جديد",
  "Evolução financeira do mês — dia a dia": "التطور المالي للشهر — يوماً بيوم",
  "Distribuição de receitas": "توزيع الإيرادات", "Despesas por categoria": "المصروفات حسب الفئة",
  "Inadimplência ao longo do tempo": "التأخر في السداد عبر الزمن", 
  "Aprovações pendentes": "موافقات معلّقة", "Alertas do dia": "تنبيهات اليوم", "Ver todas →": "عرض الكل ←",
  "Sem despesas em": "لا مصروفات في", "Sem receitas em": "لا إيرادات في", "Dia": "اليوم",
  "Receita": "إيراد", "Despesa": "مصروف", "Multa": "غرامة",
  "aguarda decisão do síndico": "بانتظار قرار مدير المبنى",
  "cobrança(s) vencida(s) somando": "دفعة/دفعات متأخرة بمجموع",
  "sem responsável designado": "بدون مسؤول محدد",
  "Pago": "مدفوع", "Entrada": "مقبوض", "Parcial": "جزئي", "Em aberto": "مفتوح", "Aguardando": "قيد الانتظار", "Vencida": "متأخرة", "Emitida": "صادرة",
  "Ocupada": "مأهولة", "Alugada": "مؤجّرة", "Vaga": "شاغرة", "Ativo": "نشط", "Em teste": "تجريبي", "Inadimplente": "متأخر السداد",
  "Prazo de defesa": "مهلة الاعتراض", "Multa aplicada": "غرامة مطبّقة", "Advertência": "إنذار",
  "Em andamento": "قيد التنفيذ", "Concluído": "مكتمل", "No condomínio": "داخل المجمّع", "Saiu": "غادر", "Retirado": "تم الاستلام",
  "Ocorrência": "حادثة", "Cancelada": "ملغاة", "Cancelado": "ملغى", "Vendida": "مُباعة", "Reservada": "محجوزة", "Inativa": "غير نشطة",
  "Alta": "عالية", "Média": "متوسطة", "Baixa": "منخفضة",
  "Todos os status": "كل الحالات", "Todos os papéis": "كل الأدوار", "Todos": "الكل", "Pagas": "مدفوعة", "Emitidas": "صادرة", "Vencidas": "متأخرة",
  "Abertos": "مفتوحة", "Concluídos": "مكتملة",
  "Nome": "الاسم", "Papel": "الدور", "Unidade": "الوحدة", "Telefone": "الهاتف", "Status": "الحالة",
  "Data": "التاريخ", "Tipo": "النوع", "Categoria": "الفئة", "Descrição": "الوصف", "Valor": "المبلغ",
  "Responsável": "المسؤول", "Competência": "الفترة", "Vencimento": "تاريخ الاستحقاق", "Plano": "الباقة", "Mensalidade": "الاشتراك الشهري", "Mensal": "شهري", "Anual": "سنوي", "Anuidade": "الاشتراك السنوي", 
  "Planos": "الباقات",
  "Últimos comunicados": "أحدث الإعلانات", "Minha situação": "وضعي", "Cobranças da unidade": "مدفوعات الوحدة",
  "Unidade / apartamento": "الوحدة / الشقة", "Cadastre unidades primeiro na tela Unidades.": "سجّل الوحدات أولاً في شاشة «الوحدات».",
  "Nenhuma cobrança para esta unidade ainda.": "لا مدفوعات لهذه الوحدة بعد.",
  "Toque para ler": "انقر للقراءة",
  "Destino": "الوجهة", "Todas as unidades (rateio pela fração)": "جميع الوحدات (توزيع حسب الحصة)",

  "Será gerada 1 cobrança para": "سيتم إنشاء دفعة واحدة لـ",
  "O morador verá o aviso no portal dele.": "سيرى الساكن الإشعار في بوابته.",
  "Serão geradas": "سينشئ النظام", 
  "Gerar cobrança": "إنشاء الدفعة", "Gerar": "إنشاء", "cobranças": "دفعات",
  "Cobrança de": "دفعة", "vencida": "متأخرة", "Nova cobrança de": "دفعة جديدة لشهر",
  "vence em": "تُستحق في", "venceu em": "استُحقت في",

  "Você pode apresentar defesa até": "يمكنك تقديم اعتراض حتى",
  "Procure a administração do condomínio.": "تواصل مع إدارة المجمّع.",
  "Movimentação de hoje": "حركة اليوم", "Nenhum chamado aqui": "لا طلبات هنا", "sem custo lançado": "لا تكلفة مسجّلة",
  "Nome fantasia *": "الاسم التجاري *", "Razão social": "الاسم القانوني", "CNPJ *": "الرقم الضريبي للشركة *", "CPF ou RG do diretor *": "رقم هويتك (المدير) *",
  "Porte": "الحجم", "Endereço completo *": "العنوان الكامل *", "Nome fantasia": "الاسم التجاري", "CNPJ": "الرقم الضريبي للشركة",
  "Inscrição municipal": "التسجيل البلدي", "Torres / blocos": "الأبراج / المباني", "Unidades / vagas": "الوحدات / المواقف",
  "Endereço completo": "العنوان الكامل", "Administradora responsável": "شركة الإدارة المسؤولة", "Síndico atual": "مدير المبنى الحالي",
  "Diretor administrativo": "المدير الإداري", "Início da gestão": "بداية الولاية", 
  "Horário de silêncio": "ساعات الهدوء", "Mudanças": "الانتقالات", "Obras": "الأعمال الإنشائية", "Visitantes": "الزوار", "Animais": "الحيوانات الأليفة",
  "Áreas comuns": "المرافق المشتركة", "Logo (upload)": "الشعار (رفع)", "Cor primária do portal": "اللون الأساسي للبوابة",
  "Responsável financeiro": "المسؤول المالي", "Área privativa (m²)": "المساحة الخاصة (م²)",
  "Vagas vinculadas": "المواقف المرتبطة", "Número": "الرقم", "Bloco / torre": "المبنى / البرج", "Andar": "الطابق",
  "Número (ou início do intervalo)": "الرقم (أو بداية النطاق)", "Até o número (opcional)": "حتى الرقم (اختياري)",
  "Ex.: 402, 1 ou 1D": "مثال: 402 أو 1 أو 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "مثال: 100 أو 4D — اتركه فارغاً لإنشاء وحدة واحدة",

  "Papel no condomínio": "الدور في المجمّع", "Unidade vinculada": "الوحدة المرتبطة",
  "Data de entrada": "تاريخ الدخول", "Documento (upload)": "مستند (رفع)",
  "Fundo de reserva": "صندوق الاحتياط", "Fundo de obras": "صندوق الأعمال", "Valor ($)": "المبلغ ($)",
  "Subcategoria / centro de custo": "فئة فرعية / مركز تكلفة", "Forma de pagamento": "طريقة الدفع", "Rateio": "التوزيع",
  "Nota fiscal (anexo)": "فاتورة (مرفق)", "Aguardando pagamento": "بانتظار الدفع",
  "Base de cálculo": "أساس الحساب", "Canais de envio": "قنوات الإرسال",
  "Aplicadas em 2026": "مطبّقة في 2026", "Em prazo de defesa": "ضمن مهلة الاعتراض", "Arrecadado em multas": "المحصّل من الغرامات",
  "Categoria da infração": "فئة المخالفة", "Unidade responsável": "الوحدة المسؤولة", "Data e hora": "التاريخ والوقت",
  "Tipo de penalidade": "نوع العقوبة", "Valor (se multa)": "المبلغ (إن كانت غرامة)", "Prazo para defesa": "مهلة الاعتراض",
  "Base normativa": "الأساس التنظيمي", "Descrição detalhada": "وصف تفصيلي",
  "Provas (foto, vídeo, áudio ou documento)": "أدلة (صورة أو فيديو أو صوت أو مستند)",
  "Destinatários": "المستلمون", "Título": "العنوان", "Mensagem": "الرسالة", "Canais": "القنوات",
  "Unidade (se aplicável)": "الوحدة (إن وُجدت)", "Prioridade": "الأولوية", "Prazo": "المهلة",
  "Custo estimado": "التكلفة التقديرية", "Fotos / vídeos": "صور / فيديو", "Descrição do problema": "وصف المشكلة",
  "Acessos registrados": "عمليات دخول مسجّلة", "Visitantes no condomínio": "زوار داخل المجمّع",
  "Entregas registradas": "طرود مسجّلة", "Vagas de visitante livres": "مواقف زوار شاغرة",
  "Nome / empresa": "الاسم / الشركة", "Unidade de destino": "الوحدة المقصودة", "Janela de horário": "الفترة الزمنية",
  "Veículo (opcional)": "المركبة (اختياري)", 

  "Nova unidade": "وحدة جديدة", "Nova pessoa": "شخص جديد", "Novo lançamento": "قيد جديد",
  "Gerar cobranças da competência": "إنشاء مدفوعات الفترة", "Registrar infração": "تسجيل مخالفة",
  "Novo documento timbrado": "مستند رسمي جديد", "Abrir chamado de manutenção": "فتح طلب صيانة",
  "Pré-autorizar entrada": "تصريح دخول مسبق", "Novo acesso": "حساب جديد", 
  "Abrir chamado": "فتح طلب",
  "Cancelar": "إلغاء", "Fechar": "إغلاق", "Exportar": "تصدير", "Lançamento": "قيد", "Pessoa": "شخص",
  "Cadastrar unidade": "تسجيل وحدة", "Criar unidade": "إنشاء وحدة", "Cadastrar": "تسجيل",
  "Salvar alterações": "حفظ التغييرات", "Gerar cobranças": "إنشاء المدفوعات", "Gerar cobranças do mês": "إنشاء مدفوعات الشهر",
  "Reenviar": "إعادة إرسال", "Baixar": "تنزيل", "Enviar por WhatsApp": "إرسال عبر WhatsApp", "Imprimir PDF": "طباعة PDF",
  "Enviar ao responsável": "إرسال إلى المسؤول", "Cancelar multa": "إلغاء الغرامة", "Aprovar (síndico)": "اعتماد (مدير المبنى)",
  "Enviar para aprovação": "إرسال للموافقة", "Ver": "عرض", "Publicar e enviar": "نشر وإرسال",
  "Criar documento timbrado": "إنشاء مستند رسمي", "Gerar PDF": "إنشاء PDF",
  "Gerar QR de acesso": "إنشاء رمز QR للدخول", "Registrar ocorrência": "تسجيل حادثة",
  "Autorizar e gerar QR": "تصريح وإنشاء QR", "Adicionar acesso": "إضافة حساب", "Remover": "حذف",
  "Criar acesso": "إنشاء حساب", 
  "Pagar": "دفع", "Copiar código": "نسخ الرمز", 
  "Tentar novamente": "إعادة المحاولة", "Voltar e trocar perfil": "الرجوع وتغيير الدور", "Sair": "تسجيل الخروج",
  "Lançar e enviar para aprovação": "تسجيل وإرسال للموافقة", 
  "Salvando…": "جارٍ الحفظ…", "Criando…": "جارٍ الإنشاء…", "Gerando…": "جارٍ التوليد…", "Publicando…": "جارٍ النشر…",
  "Abrindo…": "جارٍ الفتح…", "Autorizando…": "جارٍ التصريح…", "Enviando…": "جارٍ الإرسال…",
  "Extrato": "كشف الحساب",
  "Início": "الرئيسية", "Pagamentos": "المدفوعات", "Avisos": "الإشعارات",

  "Buscar por nome…": "ابحث بالاسم…", "Buscar lançamento…": "ابحث عن قيد…",
  "Buscar por unidade ou responsável…": "ابحث بالوحدة أو المسؤول…",
  "Nenhuma unidade encontrada": "لم يُعثر على وحدات",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "عدّل البحث أو عوامل التصفية، أو سجّل أول وحدة في هذا المجمّع.",
  "Nenhuma pessoa encontrada": "لم يُعثر على أشخاص",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "سجّل الملاك والمستأجرين والموظفين ومزوّدي الخدمات بأدوار منفصلة لتجنّب الالتباس التشغيلي.",
  "Nenhum lançamento neste período": "لا قيود في هذه الفترة",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "سجّل أول إيراد أو مصروف للفترة لبدء متابعة الصندوق.",
  "Nenhuma cobrança nesta competência": "لا مدفوعات في هذه الفترة",

  "Nenhum documento nesta categoria": "لا مستندات في هذه الفئة",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "تُؤرشف هنا تلقائياً المستندات الرسمية للغرامات والإعلانات والمحاضر والإيصالات، وتُحفظ لسنوات.",
  "Nenhum acesso criado ainda": "لم تُنشأ حسابات بعد",

  "Não foi possível carregar os dados": "تعذّر تحميل البيانات",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "تحقق من الاتصال وحاول مجدداً. إذا استمرت المشكلة فتواصل مع الدعم.",
};
