/* বাংলা */
export default {
  "Condomínio": "আবাসন", "Unidades": "ইউনিট", "Pessoas": "ব্যক্তি", "Financeiro": "অর্থ",
  "Cobranças QR": "QR বিল", "Multas": "জরিমানা", "Comunicados": "নোটিশ", "Documentos": "নথি",
  "Manutenção": "রক্ষণাবেক্ষণ", "Portaria": "রিসেপশন", "Gerenciar Emails": "ইমেইল ব্যবস্থাপনা", "Painel SaaS": "SaaS প্যানেল",
  "Visão geral do condomínio em tempo real": "আবাসনের রিয়েল-টাইম সারসংক্ষেপ",
  "Cadastro-mãe: dados legais, gestão e regras internas": "মূল রেকর্ড: আইনি তথ্য, ব্যবস্থাপনা ও অভ্যন্তরীণ নিয়ম",
  "96 unidades · 2 torres + térreo comercial": "৯৬টি ইউনিট · ২টি টাওয়ার + বাণিজ্যিক নিচতলা",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "আলাদা ভূমিকা: মালিক, ভাড়াটে, কর্মচারী ও সেবাদাতা",
  "Competência 06/2026 · aprovações do síndico ativas": "সময়কাল ০৬/২০২৬ · ব্যবস্থাপকের অনুমোদন সক্রিয়",
  "QR Code Verum Pay com baixa automática": "স্বয়ংক্রিয় সমন্বয়সহ Verum Pay QR কোড",
  "Fluxo com prova, defesa e aprovação": "প্রমাণ, আপত্তি ও অনুমোদনের প্রক্রিয়া",
  "Envio por portal, e-mail e WhatsApp": "পোর্টাল, ইমেইল ও WhatsApp-এ পাঠানো",
  "Arquivo timbrado com retenção histórica": "লেটারহেড নথির দীর্ঘমেয়াদি সংরক্ষণাগার",
  "Ordens de serviço por categoria e prioridade": "বিভাগ ও অগ্রাধিকার অনুযায়ী কাজের আদেশ",
  "Controle de acessos, entregas e ocorrências": "প্রবেশ, ডেলিভারি ও ঘটনার নিয়ন্ত্রণ",
  "Clientes, planos, licenças e implantação": "গ্রাহক, প্ল্যান, লাইসেন্স ও চালুকরণ",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "ব্যবস্থাপক, কোষাধ্যক্ষ, ব্যবস্থাপনা কোম্পানি ও বাসিন্দাদের লগইন তথ্য",
  "Notificações": "বিজ্ঞপ্তি", "Alternar tema": "থিম বদলান", "Idioma": "ভাষা", "Perfil de acesso": "অ্যাক্সেস ভূমিকা",
  "Diretor": "পরিচালক", "Síndico": "ব্যবস্থাপক", "Tesouraria": "কোষাধ্যক্ষ", "Administradora": "ব্যবস্থাপনা কোম্পানি", "Morador": "বাসিন্দা",
  "Visão estratégica, aprovações e auditoria": "কৌশলগত দৃষ্টি, অনুমোদন ও নিরীক্ষা",
  "Operação, multas, comunicados e manutenção": "পরিচালনা, জরিমানা, নোটিশ ও রক্ষণাবেক্ষণ",
  "Financeiro, cobranças e conciliação": "অর্থ, বিল ও সমন্বয়",
  "Gestão SaaS: clientes, planos e licenças": "SaaS ব্যবস্থাপনা: গ্রাহক, প্ল্যান ও লাইসেন্স",
  "Boletos, comprovantes, comunicados e chamados": "বিল, রসিদ, নোটিশ ও অনুরোধ",
  "Gestão condominial premium · powered by Verum Pay": "প্রিমিয়াম আবাসন ব্যবস্থাপনা · powered by Verum Pay",
  "Criar acesso do diretor": "পরিচালকের অ্যাকাউন্ট তৈরি করুন",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "এটি প্রথম প্রবেশ। এখানে তৈরি অ্যাকাউন্টটি এই ভূমিকায় লগইনে ব্যবহৃত হবে:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": "। এই ভূমিকা \"ইমেইল ব্যবস্থাপনা\"-তে অন্য ভূমিকার ইমেইল ও পাসওয়ার্ড নিবন্ধন করতে পারবে।",
  "Nome completo": "পুরো নাম", "E-mail": "ইমেইল", "Senha": "পাসওয়ার্ড", "Confirmar senha": "পাসওয়ার্ড নিশ্চিত করুন",
  "Criar conta e continuar": "অ্যাকাউন্ট তৈরি করে এগিয়ে যান",
  "Já tem prédio cadastrado? Fazer login": "ভবন আগে থেকেই নিবন্ধিত? লগইন করুন",
  "Entrar como": "যে ভূমিকায় লগইন", "Trocar perfil": "ভূমিকা বদলান", "Voltar ao cadastro": "নিবন্ধনে ফিরে যান",
  "Entrar": "লগইন", "Verificando conta...": "অ্যাকাউন্ট যাচাই হচ্ছে...",
  "E-mail ou senha incorretos.": "ইমেইল বা পাসওয়ার্ড ভুল।",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "ইমেইল বা পাসওয়ার্ড ভুল। পরিচালককে \"ইমেইল ব্যবস্থাপনা\"-তে আপনার অ্যাকাউন্ট যাচাই করতে বলুন।",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "এই ডিভাইসে পরিচালকের অ্যাকাউন্ট পাওয়া যায়নি। ফিরে গিয়ে পরিচালকের অ্যাকাউন্ট তৈরি করুন।",
  "Não foi possível verificar sua conta agora.": "এখন আপনার অ্যাকাউন্ট যাচাই করা গেল না।",
  "A senha deve ter pelo menos 4 caracteres.": "পাসওয়ার্ড কমপক্ষে ৪ অক্ষরের হতে হবে।",
  "As senhas não conferem.": "পাসওয়ার্ড দুটি মিলছে না।",
  "Nenhum acesso de": "এই ভূমিকার কোনো অ্যাকাউন্ট নেই:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "। পরিচালককে \"ইমেইল ব্যবস্থাপনা\"-তে এটি তৈরি করতে বলুন।",
  "Tema claro": "হালকা থিম", "Tema escuro": "গাঢ় থিম",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "এই নামে কোনো অ্যাকাউন্ট নেই। পরিচালককে \"ইমেইল ব্যবস্থাপনা\"-তে নিবন্ধন করতে বলুন।",
  "Senha incorreta para este nome.": "এই নামের জন্য পাসওয়ার্ড ভুল।",
  "Seu nome": "আপনার নাম", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "কমপক্ষে ৪ অক্ষর", "Repita a senha": "পাসওয়ার্ড আবার লিখুন",
  "Saldo em caixa": "নগদ স্থিতি", "Inadimplência": "বকেয়ার হার", "Receitas de": "আয় —", "Despesas de": "ব্যয় —",
  "Nova cobrança": "নতুন বিল", "Novo gasto": "নতুন ব্যয়", "Nova multa": "নতুন জরিমানা", "Novo comunicado": "নতুন নোটিশ", "Novo chamado": "নতুন অনুরোধ",
  "Evolução financeira do mês — dia a dia": "মাসের আর্থিক গতিধারা — দিন অনুযায়ী",
  "Distribuição de receitas": "আয়ের বণ্টন", "Despesas por categoria": "বিভাগ অনুযায়ী ব্যয়",
  "Inadimplência ao longo do tempo": "সময়ের সাথে বকেয়া", "Atividade recente": "সাম্প্রতিক কার্যকলাপ",
  "Aprovações pendentes": "অনুমোদনের অপেক্ষায়", "Alertas do dia": "আজকের সতর্কতা", "Ver todas →": "সব দেখুন →",
  "Sem despesas em": "কোনো ব্যয় নেই:", "Sem receitas em": "কোনো আয় নেই:", "Dia": "দিন",
  "Receita": "আয়", "Despesa": "ব্যয়", "Multa": "জরিমানা",
  "aguarda decisão do síndico": "ব্যবস্থাপকের সিদ্ধান্তের অপেক্ষায়",
  "cobrança(s) vencida(s) somando": "টি বকেয়া বিল, মোট",
  "sem responsável designado": "কোনো দায়িত্বপ্রাপ্ত নেই",
  "Pago": "পরিশোধিত", "Parcial": "আংশিক", "Em aberto": "খোলা", "Aguardando": "অপেক্ষমাণ", "Vencida": "বকেয়া", "Emitida": "ইস্যুকৃত",
  "Ocupada": "বসবাসরত", "Alugada": "ভাড়া দেওয়া", "Vaga": "খালি", "Ativo": "সক্রিয়", "Em teste": "পরীক্ষামূলক", "Inadimplente": "বকেয়াদার",
  "Prazo de defesa": "আপত্তির সময়সীমা", "Multa aplicada": "জরিমানা কার্যকর", "Advertência": "সতর্কীকরণ",
  "Em andamento": "চলমান", "Concluído": "সম্পন্ন", "No condomínio": "আবাসনে আছে", "Saiu": "বেরিয়ে গেছে", "Retirado": "গৃহীত",
  "Ocorrência": "ঘটনা", "Cancelada": "বাতিল", "Cancelado": "বাতিল", "Vendida": "বিক্রীত", "Reservada": "সংরক্ষিত", "Inativa": "নিষ্ক্রিয়",
  "Alta": "উচ্চ", "Média": "মাঝারি", "Baixa": "নিম্ন",
  "Todos os status": "সব অবস্থা", "Todos os papéis": "সব ভূমিকা", "Todos": "সব", "Pagas": "পরিশোধিত", "Emitidas": "ইস্যুকৃত", "Vencidas": "বকেয়া",
  "Abertos": "খোলা", "Concluídos": "সম্পন্ন",
  "Nome": "নাম", "Papel": "ভূমিকা", "Unidade": "ইউনিট", "CPF/CNPJ": "পরিচয়পত্র নম্বর", "Telefone": "ফোন", "Status": "অবস্থা",
  "Data": "তারিখ", "Tipo": "ধরন", "Categoria": "বিভাগ", "Descrição": "বর্ণনা", "Valor": "পরিমাণ",
  "Responsável": "দায়িত্বপ্রাপ্ত", "Competência": "সময়কাল", "Vencimento": "শেষ তারিখ", "Plano": "প্ল্যান", "Mensalidade": "মাসিক ফি", "Renovação": "নবায়ন",
  "Evolução da receita recorrente": "পুনরাবৃত্ত আয়ের গতিধারা", "Planos": "প্ল্যান",
  "Últimos comunicados": "সর্বশেষ নোটিশ", "Minha situação": "আমার অবস্থা", "Cobranças da unidade": "ইউনিটের বিল",
  "Unidade / apartamento": "ইউনিট / ফ্ল্যাট", "Cadastre unidades primeiro na tela Unidades.": "আগে \"ইউনিট\" পর্দায় ইউনিট নিবন্ধন করুন।",
  "Nenhuma cobrança para esta unidade ainda.": "এই ইউনিটের জন্য এখনো কোনো বিল নেই।",
  "Toque para ler": "পড়তে ট্যাপ করুন",
  "Destino": "লক্ষ্য", "Todas as unidades (rateio pela fração)": "সব ইউনিট (অংশ অনুযায়ী ভাগ)",
  "Valor da cobrança (R$)": "বিলের পরিমাণ (R$)",
  "Será gerada 1 cobrança para": "১টি বিল তৈরি হবে:",
  "O morador verá o aviso no portal dele.": "বাসিন্দা তার পোর্টালে বিজ্ঞপ্তিটি দেখবেন।",
  "Serão geradas": "সিস্টেম তৈরি করবে", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "টি বিল (আর্থিক দায়িত্বপ্রাপ্ত ইউনিট), আদর্শ অংশ অনুযায়ী ভাগ করা।",
  "Gerar cobrança": "বিল তৈরি করুন", "Gerar": "তৈরি করুন", "cobranças": "টি বিল",
  "Cobrança de": "বিল:", "vencida": "(বকেয়া)", "Nova cobrança de": "নতুন বিল:",
  "vence em": "শেষ তারিখ", "venceu em": "শেষ তারিখ পেরিয়েছে:",
  "Multas da unidade": "ইউনিটের জরিমানা",
  "Você pode apresentar defesa até": "এই তারিখ পর্যন্ত আপত্তি জানাতে পারবেন:",
  "Procure a administração do condomínio.": "আবাসন কর্তৃপক্ষের সাথে যোগাযোগ করুন।",
  "Movimentação de hoje": "আজকের গতিবিধি", "Nenhum chamado aqui": "এখানে কোনো অনুরোধ নেই", "sem custo lançado": "কোনো খরচ লেখা হয়নি",
  "Nome fantasia *": "ব্যবসায়িক নাম *", "Razão social": "আইনি নাম", "CNPJ *": "কোম্পানির কর নম্বর *", "Seu CPF (diretor) *": "আপনার পরিচয়পত্র নম্বর (পরিচালক) *",
  "Porte": "আকার", "Endereço completo *": "পূর্ণ ঠিকানা *", "Nome fantasia": "ব্যবসায়িক নাম", "CNPJ": "কোম্পানির কর নম্বর",
  "Inscrição municipal": "পৌর নিবন্ধন", "Torres / blocos": "টাওয়ার / ব্লক", "Unidades / vagas": "ইউনিট / পার্কিং",
  "Endereço completo": "পূর্ণ ঠিকানা", "Administradora responsável": "দায়িত্বপ্রাপ্ত ব্যবস্থাপনা কোম্পানি", "Síndico atual": "বর্তমান ব্যবস্থাপক",
  "Diretor administrativo": "প্রশাসনিক পরিচালক", "Início da gestão": "মেয়াদের শুরু", "Status do contrato SaaS": "SaaS চুক্তির অবস্থা",
  "Horário de silêncio": "নীরবতার সময়", "Mudanças": "বাসা বদল", "Obras": "সংস্কার কাজ", "Visitantes": "অতিথি", "Animais": "পোষা প্রাণী",
  "Áreas comuns": "সাধারণ এলাকা", "Logo (upload)": "লোগো (আপলোড)", "Cor primária do portal": "পোর্টালের মূল রং",
  "Responsável financeiro": "আর্থিক দায়িত্বপ্রাপ্ত", "Fração ideal (%)": "আদর্শ অংশ (%)", "Área privativa (m²)": "ব্যক্তিগত আয়তন (m²)",
  "Vagas vinculadas": "সংযুক্ত পার্কিং", "Número": "নম্বর", "Bloco / torre": "ব্লক / টাওয়ার", "Andar": "তলা",
  "Número (ou início do intervalo)": "নম্বর (বা পরিসরের শুরু)", "Até o número (opcional)": "যে নম্বর পর্যন্ত (ঐচ্ছিক)",
  "Ex.: 402, 1 ou 1D": "যেমন: 402, 1 বা 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "যেমন: 100 বা 4D — খালি রাখলে একটিই তৈরি হবে",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "\"যে নম্বর পর্যন্ত\" পূরণ করে একসাথে অনেক ইউনিট তৈরি করুন: 1 থেকে 100 তৈরি করবে 1, 2… 100; 1D থেকে 4D তৈরি করবে 1D, 2D, 3D ও 4D। ব্লকে আগে থেকে থাকা নম্বরগুলো বাদ যাবে। ধরন, তলা, অবস্থা ও অংশ সবগুলোতে প্রযোজ্য।",
  "CPF ou CNPJ": "পরিচয়পত্র নম্বর", "Papel no condomínio": "আবাসনে ভূমিকা", "Unidade vinculada": "সংযুক্ত ইউনিট",
  "Data de entrada": "প্রবেশের তারিখ", "Documento (upload)": "নথি (আপলোড)",
  "Fundo de reserva": "সংরক্ষিত তহবিল", "Fundo de obras": "সংস্কার তহবিল", "Valor (R$)": "পরিমাণ (R$)",
  "Subcategoria / centro de custo": "উপবিভাগ / ব্যয় কেন্দ্র", "Forma de pagamento": "পরিশোধ পদ্ধতি", "Rateio": "বণ্টন",
  "Nota fiscal (anexo)": "চালান (সংযুক্তি)", "Aguardando pagamento": "পরিশোধের অপেক্ষায়",
  "Valor total a ratear (R$)": "বণ্টনযোগ্য মোট পরিমাণ (R$)", "Base de cálculo": "হিসাবের ভিত্তি", "Canais de envio": "পাঠানোর মাধ্যম",
  "Aplicadas em 2026": "২০২৬-এ প্রয়োগকৃত", "Em prazo de defesa": "আপত্তির সময়সীমার মধ্যে", "Arrecadado em multas": "জরিমানা থেকে আদায়",
  "Categoria da infração": "লঙ্ঘনের বিভাগ", "Unidade responsável": "দায়ী ইউনিট", "Data e hora": "তারিখ ও সময়",
  "Tipo de penalidade": "শাস্তির ধরন", "Valor (se multa)": "পরিমাণ (জরিমানা হলে)", "Prazo para defesa": "আপত্তির শেষ তারিখ",
  "Base normativa": "বিধিগত ভিত্তি", "Descrição detalhada": "বিস্তারিত বর্ণনা",
  "Provas (foto, vídeo, áudio ou documento)": "প্রমাণ (ছবি, ভিডিও, অডিও বা নথি)",
  "Destinatários": "প্রাপক", "Título": "শিরোনাম", "Mensagem": "বার্তা", "Canais": "মাধ্যম",
  "Unidade (se aplicável)": "ইউনিট (প্রযোজ্য হলে)", "Conteúdo": "বিষয়বস্তু", "Prioridade": "অগ্রাধিকার", "Prazo": "সময়সীমা",
  "Custo estimado": "আনুমানিক খরচ", "Fotos / vídeos": "ছবি / ভিডিও", "Descrição do problema": "সমস্যার বর্ণনা",
  "Acessos registrados": "নথিভুক্ত প্রবেশ", "Visitantes no condomínio": "আবাসনে অতিথি",
  "Entregas registradas": "নথিভুক্ত ডেলিভারি", "Vagas de visitante livres": "খালি অতিথি পার্কিং",
  "Nome / empresa": "নাম / কোম্পানি", "Unidade de destino": "গন্তব্য ইউনিট", "Janela de horário": "সময়সীমা",
  "Veículo (opcional)": "গাড়ি (ঐচ্ছিক)", "Condomínios ativos": "সক্রিয় আবাসন",
  "Receita recorrente (MRR)": "পুনরাবৃত্ত আয় (MRR)", "Em período de teste": "পরীক্ষামূলক সময়ে",
  "Nova unidade": "নতুন ইউনিট", "Nova pessoa": "নতুন ব্যক্তি", "Novo lançamento": "নতুন এন্ট্রি",
  "Gerar cobranças da competência": "সময়কালের বিল তৈরি করুন", "Registrar infração": "লঙ্ঘন নথিভুক্ত করুন",
  "Novo documento timbrado": "নতুন লেটারহেড নথি", "Abrir chamado de manutenção": "রক্ষণাবেক্ষণ অনুরোধ খুলুন",
  "Pré-autorizar entrada": "প্রবেশের পূর্বানুমোদন", "Novo acesso": "নতুন অ্যাকাউন্ট", "Contratar novo condomínio": "নতুন আবাসন যুক্ত করুন",
  "Abrir chamado": "অনুরোধ খুলুন",
  "Cancelar": "বাতিল", "Fechar": "বন্ধ করুন", "Exportar": "রপ্তানি", "Lançamento": "এন্ট্রি", "Pessoa": "ব্যক্তি",
  "Cadastrar unidade": "ইউনিট নিবন্ধন", "Criar unidade": "ইউনিট তৈরি করুন", "Cadastrar": "নিবন্ধন",
  "Salvar alterações": "পরিবর্তন সংরক্ষণ করুন", "Gerar cobranças": "বিল তৈরি করুন", "Gerar cobranças do mês": "এ মাসের বিল তৈরি করুন",
  "Reenviar": "পুনরায় পাঠান", "Baixar": "ডাউনলোড", "Enviar por WhatsApp": "WhatsApp-এ পাঠান", "Imprimir PDF": "PDF প্রিন্ট করুন",
  "Enviar ao responsável": "দায়িত্বপ্রাপ্তকে পাঠান", "Cancelar multa": "জরিমানা বাতিল করুন", "Aprovar (síndico)": "অনুমোদন (ব্যবস্থাপক)",
  "Enviar para aprovação": "অনুমোদনের জন্য পাঠান", "Ver": "দেখুন", "Publicar e enviar": "প্রকাশ করে পাঠান",
  "Criar documento timbrado": "লেটারহেড নথি তৈরি করুন", "Gerar PDF": "PDF তৈরি করুন",
  "Gerar QR de acesso": "প্রবেশ QR তৈরি করুন", "Registrar ocorrência": "ঘটনা নথিভুক্ত করুন",
  "Autorizar e gerar QR": "অনুমোদন দিয়ে QR তৈরি করুন", "Adicionar acesso": "অ্যাকাউন্ট যোগ করুন", "Remover": "মুছুন",
  "Criar acesso": "অ্যাকাউন্ট তৈরি করুন", "Novo cliente": "নতুন গ্রাহক", "Bloquear acesso": "অ্যাক্সেস বন্ধ করুন", "Abrir painel": "প্যানেল খুলুন",
  "Iniciar implantação": "চালুকরণ শুরু করুন", "Pagar": "পরিশোধ করুন", "Copiar código": "কোড কপি করুন", "Enviar chamado": "অনুরোধ পাঠান",
  "Tentar novamente": "আবার চেষ্টা করুন", "Voltar e trocar perfil": "ফিরে গিয়ে ভূমিকা বদলান", "Sair": "লগআউট",
  "Lançar e enviar para aprovação": "এন্ট্রি করে অনুমোদনে পাঠান", "Criar condomínio e começar": "আবাসন তৈরি করে শুরু করুন",
  "Salvando…": "সংরক্ষণ হচ্ছে…", "Criando…": "তৈরি হচ্ছে…", "Gerando…": "তৈরি হচ্ছে…", "Publicando…": "প্রকাশ হচ্ছে…",
  "Abrindo…": "খোলা হচ্ছে…", "Autorizando…": "অনুমোদন হচ্ছে…", "Enviando…": "পাঠানো হচ্ছে…",
  "Boletos e QR": "বিল ও QR", "Extrato": "বিবরণী",
  "Início": "হোম", "Pagamentos": "পরিশোধ", "Avisos": "নোটিশ",
  "Buscar por número, bloco ou responsável…": "নম্বর, ব্লক বা দায়িত্বপ্রাপ্ত দিয়ে খুঁজুন…",
  "Buscar por nome…": "নাম দিয়ে খুঁজুন…", "Buscar lançamento…": "এন্ট্রি খুঁজুন…",
  "Buscar por unidade ou responsável…": "ইউনিট বা দায়িত্বপ্রাপ্ত দিয়ে খুঁজুন…",
  "Nenhuma unidade encontrada": "কোনো ইউনিট পাওয়া যায়নি",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "খোঁজ বা ফিল্টার বদলান, অথবা এই আবাসনের প্রথম ইউনিট নিবন্ধন করুন।",
  "Nenhuma pessoa encontrada": "কোনো ব্যক্তি পাওয়া যায়নি",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "বিভ্রান্তি এড়াতে মালিক, ভাড়াটে, কর্মচারী ও সেবাদাতাদের আলাদা ভূমিকায় নিবন্ধন করুন।",
  "Nenhum lançamento neste período": "এই সময়ে কোনো এন্ট্রি নেই",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "নগদ প্রবাহ অনুসরণ শুরু করতে সময়কালের প্রথম আয় বা ব্যয় লিখুন।",
  "Nenhuma cobrança nesta competência": "এই সময়ে কোনো বিল নেই",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "এ মাসের বিল তৈরি করুন: সিস্টেম প্রতিটি ইউনিটের জন্য অনন্য Verum Pay QR কোড তৈরি করে পোর্টাল, ইমেইল বা WhatsApp-এ পাঠায়।",
  "Nenhum documento nesta categoria": "এই বিভাগে কোনো নথি নেই",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "জরিমানা, নোটিশ, কার্যবিবরণী ও রসিদের লেটারহেড নথি এখানে স্বয়ংক্রিয়ভাবে সংরক্ষিত হয় এবং বছরের পর বছর থাকে।",
  "Nenhum acesso criado ainda": "এখনো কোনো অ্যাকাউন্ট তৈরি হয়নি",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "ব্যবস্থাপক, কোষাধ্যক্ষ, ব্যবস্থাপনা কোম্পানি ও বাসিন্দারা যেন লগইন করতে পারেন সে জন্য প্রথম ইমেইল ও পাসওয়ার্ড নিবন্ধন করুন।",
  "Não foi possível carregar os dados": "ডেটা লোড করা যায়নি",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "সংযোগ পরীক্ষা করে আবার চেষ্টা করুন। সমস্যা থাকলে সহায়তা দলের সাথে যোগাযোগ করুন।",
};
