/* বাংলা */
export default {
  "Condomínio": "আবাসন", "Unidades": "ইউনিট", "Pessoas": "ব্যক্তি", "Financeiro": "অর্থ",
  "Cobranças QR": "QR বিল", "Multas": "জরিমানা", "Comunicados": "নোটিশ", "Documentos": "নথি",
  "Manutenção": "রক্ষণাবেক্ষণ", "Portaria": "রিসেপশন", "Gerenciar Acessos": "অ্যাক্সেস ব্যবস্থাপনা", 
  "Visão geral do condomínio em tempo real": "আবাসনের রিয়েল-টাইম সারসংক্ষেপ",
  "Cadastro-mãe: dados legais, gestão e regras internas": "মূল রেকর্ড: আইনি তথ্য, ব্যবস্থাপনা ও অভ্যন্তরীণ নিয়ম",

  /* subtítulos dinâmicos do cabeçalho */
  "unidade": "ইউনিট", "unidades": "ইউনিট", "bloco/torre": "ব্লক/টাওয়ার", "blocos/torres": "ব্লক/টাওয়ার",
  "pessoa cadastrada": "নিবন্ধিত ব্যক্তি", "pessoas cadastradas": "নিবন্ধিত ব্যক্তি",
  "aprovações do síndico ativas": "ম্যানেজারের অনুমোদন সক্রিয়",
  "cobrança em aberto": "বকেয়া বিল", "cobranças em aberto": "বকেয়া বিল", "vencidas": "মেয়াদোত্তীর্ণ",
  "multa/advertência registrada": "নিবন্ধিত জরিমানা/সতর্কতা", "multas/advertências registradas": "নিবন্ধিত জরিমানা/সতর্কতা",
  "comunicado publicado": "প্রকাশিত বিজ্ঞপ্তি", "comunicados publicados": "প্রকাশিত বিজ্ঞপ্তি",
  "documento arquivado": "সংরক্ষিত নথি", "documentos arquivados": "সংরক্ষিত নথি",
  "chamado em aberto": "খোলা সার্ভিস অনুরোধ", "chamados em aberto": "খোলা সার্ভিস অনুরোধ",
  /* teste gratuito de 30 dias */
  "Ative seu teste gratuito de 30 dias — cadastre o cartão; nada será cobrado agora.": "আপনার ৩০ দিনের বিনামূল্যে ট্রায়াল চালু করুন — কার্ড যুক্ত করুন; এখন কিছুই কাটা হবে না।",
  "O período de avaliação terminou. Ative a assinatura para continuar.": "ট্রায়াল সময় শেষ। চালিয়ে যেতে সাবস্ক্রিপশন সক্রিয় করুন।",
  "Iniciar teste gratuito de 30 dias": "৩০ দিনের বিনামূল্যে ট্রায়াল শুরু করুন",

  "A troca de plano durante o teste gratuito é cobrada imediatamente — aguarde o fim do teste para trocar.": "ট্রায়াল চলাকালীন প্ল্যান পরিবর্তনে সঙ্গে সঙ্গে চার্জ হয় — পরিবর্তনের জন্য ট্রায়াল শেষ হওয়া পর্যন্ত অপেক্ষা করুন।",
  "Teste gratuito — termina em": "বিনামূল্যে ট্রায়াল — শেষ হবে", "dia(s)": "দিনে",
  "Depois, a cobrança é feita automaticamente no cartão cadastrado.": "তারপর নিবন্ধিত কার্ড থেকে স্বয়ংক্রিয়ভাবে চার্জ কাটা হবে।",

  "Tenho um código de ativação": "আমার একটি অ্যাক্টিভেশন কোড আছে", "Código de ativação": "অ্যাক্টিভেশন কোড",
  "Ativar": "সক্রিয় করুন", "Ativando…": "সক্রিয় করা হচ্ছে…",

  "Código aplicado. Se o acesso não liberar em instantes, use \"Já paguei — verificar\".": "কোড প্রয়োগ হয়েছে। কিছুক্ষণের মধ্যে অ্যাক্সেস না খুললে \"Já paguei — verificar\" ব্যবহার করুন।",

  "Cancelar assinatura": "সাবস্ক্রিপশন বাতিল করুন",
  "Cancelar a assinatura? O acesso continua até o fim do período já pago e nenhuma cobrança futura será feita.": "সাবস্ক্রিপশন বাতিল করবেন? পরিশোধিত মেয়াদের শেষ পর্যন্ত অ্যাক্সেস থাকবে এবং ভবিষ্যতে কোনো চার্জ কাটা হবে না।",
  "Cancelamento agendado — o acesso continua até": "বাতিল নির্ধারিত — অ্যাক্সেস থাকবে",
  "Assinatura cancelada.": "সাবস্ক্রিপশন বাতিল হয়েছে।",
  "Assinatura cancelada em": "সাবস্ক্রিপশন বাতিল হয়েছে", "o acesso será desativado em": "অ্যাক্সেস নিষ্ক্রিয় হবে",
  "Nenhuma cobrança futura será feita.": "ভবিষ্যতে কোনো চার্জ কাটা হবে না।",
  "Acima da franquia do plano": "প্ল্যানের অন্তর্ভুক্ত সীমার বেশি",
  "o excedente é cobrado por unidade adicional na fatura da licença.": "অতিরিক্ত প্রতিটি ইউনিটের চার্জ লাইসেন্স বিলে যোগ হবে।",

  "Controle de acessos, entregas e ocorrências": "প্রবেশ, ডেলিভারি ও ঘটনার নিয়ন্ত্রণ",

  "Notificações": "বিজ্ঞপ্তি", "Alternar tema": "থিম বদলান", "Idioma": "ভাষা", "Perfil de acesso": "অ্যাক্সেস ভূমিকা",
  "Diretor": "পরিচালক", "Síndico": "ব্যবস্থাপক", "Tesouraria": "কোষাধ্যক্ষ", "Administradora": "ব্যবস্থাপনা কোম্পানি", "Morador": "বাসিন্দা",
  "Visão estratégica, aprovações e auditoria": "কৌশলগত দৃষ্টি, অনুমোদন ও নিরীক্ষা",
  "Operação, multas, comunicados e manutenção": "পরিচালনা, জরিমানা, নোটিশ ও রক্ষণাবেক্ষণ",
  "Financeiro, cobranças e conciliação": "অর্থ, বিল ও সমন্বয়",

  "Boletos, comprovantes, comunicados e chamados": "বিল, রসিদ, নোটিশ ও অনুরোধ",
  "Gestão condominial premium · powered by Serve Now Global": "প্রিমিয়াম আবাসন ব্যবস্থাপনা · powered by Serve Now Global",
  "Criar acesso do diretor": "পরিচালকের অ্যাকাউন্ট তৈরি করুন",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "এটি প্রথম প্রবেশ। এখানে তৈরি অ্যাকাউন্টটি এই ভূমিকায় লগইনে ব্যবহৃত হবে:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Acessos.": "। এই ভূমিকা \"অ্যাক্সেস ব্যবস্থাপনা\"-তে অন্য ভূমিকার ইমেইল ও পাসওয়ার্ড নিবন্ধন করতে পারবে।",
  "Nome completo": "পুরো নাম", "E-mail": "ইমেইল", "Senha": "পাসওয়ার্ড", "Confirmar senha": "পাসওয়ার্ড নিশ্চিত করুন",
  "Criar conta e continuar": "অ্যাকাউন্ট তৈরি করে এগিয়ে যান",
  "Já tem prédio cadastrado? Fazer login": "ভবন আগে থেকেই নিবন্ধিত? লগইন করুন",
  "Entrar como": "যে ভূমিকায় লগইন", "Trocar perfil": "ভূমিকা বদলান", "Voltar ao cadastro": "নিবন্ধনে ফিরে যান",
  "Entrar": "লগইন", "Verificando conta...": "অ্যাকাউন্ট যাচাই হচ্ছে...",
  "E-mail ou senha incorretos.": "ইমেইল বা পাসওয়ার্ড ভুল।",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Acessos.": "ইমেইল বা পাসওয়ার্ড ভুল। পরিচালককে \"অ্যাক্সেস ব্যবস্থাপনা\"-তে আপনার অ্যাকাউন্ট যাচাই করতে বলুন।",

  "Não foi possível verificar sua conta agora.": "এখন আপনার অ্যাকাউন্ট যাচাই করা গেল না।",

  "As senhas não conferem.": "পাসওয়ার্ড দুটি মিলছে না।",
  "Nenhum acesso de": "এই ভূমিকার কোনো অ্যাকাউন্ট নেই:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Acessos.": "। পরিচালককে \"অ্যাক্সেস ব্যবস্থাপনা\"-তে এটি তৈরি করতে বলুন।",
  "Tema claro": "হালকা থিম", "Tema escuro": "গাঢ় থিম",

  "Seu nome": "আপনার নাম", "voce@exemplo.com": "you@example.com", "Repita a senha": "পাসওয়ার্ড আবার লিখুন",
  "Saldo em caixa": "নগদ স্থিতি", "Inadimplência": "বকেয়ার হার", "Receitas de": "আয় —", "Despesas de": "ব্যয় —",
  "Nova cobrança": "নতুন বিল", "Novo gasto": "নতুন ব্যয়", "Nova multa": "নতুন জরিমানা", "Novo comunicado": "নতুন নোটিশ", "Novo chamado": "নতুন অনুরোধ",
  "Evolução financeira do mês — dia a dia": "মাসের আর্থিক গতিধারা — দিন অনুযায়ী",
  "Distribuição de receitas": "আয়ের বণ্টন", "Despesas por categoria": "বিভাগ অনুযায়ী ব্যয়",
  "Inadimplência ao longo do tempo": "সময়ের সাথে বকেয়া", 
  "Aprovações pendentes": "অনুমোদনের অপেক্ষায়", "Alertas do dia": "আজকের সতর্কতা", "Ver todas →": "সব দেখুন →",
  "Sem despesas em": "কোনো ব্যয় নেই:", "Sem receitas em": "কোনো আয় নেই:", "Dia": "দিন",
  "Receita": "আয়", "Despesa": "ব্যয়", "Multa": "জরিমানা",
  "aguarda decisão do síndico": "ব্যবস্থাপকের সিদ্ধান্তের অপেক্ষায়",
  "cobrança(s) vencida(s) somando": "টি বকেয়া বিল, মোট",
  "sem responsável designado": "কোনো দায়িত্বপ্রাপ্ত নেই",
  "Pago": "পরিশোধিত", "Entrada": "প্রাপ্ত", "Parcial": "আংশিক", "Em aberto": "খোলা", "Aguardando": "অপেক্ষমাণ", "Vencida": "বকেয়া", "Emitida": "ইস্যুকৃত",
  "Ocupada": "বসবাসরত", "Alugada": "ভাড়া দেওয়া", "Vaga": "খালি", "Ativo": "সক্রিয়", "Em teste": "পরীক্ষামূলক", "Inadimplente": "বকেয়াদার",
  "Prazo de defesa": "আপত্তির সময়সীমা", "Multa aplicada": "জরিমানা কার্যকর", "Advertência": "সতর্কীকরণ",
  "Em andamento": "চলমান", "Concluído": "সম্পন্ন", "No condomínio": "আবাসনে আছে", "Saiu": "বেরিয়ে গেছে", "Retirado": "গৃহীত",
  "Ocorrência": "ঘটনা", "Cancelada": "বাতিল", "Cancelado": "বাতিল", "Vendida": "বিক্রীত", "Reservada": "সংরক্ষিত", "Inativa": "নিষ্ক্রিয়",
  "Alta": "উচ্চ", "Média": "মাঝারি", "Baixa": "নিম্ন",
  "Todos os status": "সব অবস্থা", "Todos os papéis": "সব ভূমিকা", "Todos": "সব", "Pagas": "পরিশোধিত", "Emitidas": "ইস্যুকৃত", "Vencidas": "বকেয়া",
  "Abertos": "খোলা", "Concluídos": "সম্পন্ন",
  "Nome": "নাম", "Papel": "ভূমিকা", "Unidade": "ইউনিট", "Telefone": "ফোন", "Status": "অবস্থা",
  "Data": "তারিখ", "Tipo": "ধরন", "Categoria": "বিভাগ", "Descrição": "বর্ণনা", "Valor": "পরিমাণ",
  "Responsável": "দায়িত্বপ্রাপ্ত", "Competência": "সময়কাল", "Vencimento": "শেষ তারিখ", "Plano": "প্ল্যান", "Mensalidade": "মাসিক ফি", "Mensal": "মাসিক", "Anual": "বার্ষিক", "Anuidade": "বার্ষিক ফি", 
  "Planos": "প্ল্যান",
  "Últimos comunicados": "সর্বশেষ নোটিশ", "Minha situação": "আমার অবস্থা", "Cobranças da unidade": "ইউনিটের বিল",
  "Unidade / apartamento": "ইউনিট / ফ্ল্যাট", "Cadastre unidades primeiro na tela Unidades.": "আগে \"ইউনিট\" পর্দায় ইউনিট নিবন্ধন করুন।",
  "Nenhuma cobrança para esta unidade ainda.": "এই ইউনিটের জন্য এখনো কোনো বিল নেই।",
  "Toque para ler": "পড়তে ট্যাপ করুন",
  "Destino": "লক্ষ্য", "Todas as unidades (rateio pela fração)": "সব ইউনিট (অংশ অনুযায়ী ভাগ)",

  "Será gerada 1 cobrança para": "১টি বিল তৈরি হবে:",
  "O morador verá o aviso no portal dele.": "বাসিন্দা তার পোর্টালে বিজ্ঞপ্তিটি দেখবেন।",
  "Serão geradas": "সিস্টেম তৈরি করবে", 
  "Gerar cobrança": "বিল তৈরি করুন", "Gerar": "তৈরি করুন", "cobranças": "টি বিল",
  "Cobrança de": "বিল:", "vencida": "(বকেয়া)", "Nova cobrança de": "নতুন বিল:",
  "vence em": "শেষ তারিখ", "venceu em": "শেষ তারিখ পেরিয়েছে:",

  "Você pode apresentar defesa até": "এই তারিখ পর্যন্ত আপত্তি জানাতে পারবেন:",
  "Procure a administração do condomínio.": "আবাসন কর্তৃপক্ষের সাথে যোগাযোগ করুন।",
  "Movimentação de hoje": "আজকের গতিবিধি", "Nenhum chamado aqui": "এখানে কোনো অনুরোধ নেই", "sem custo lançado": "কোনো খরচ লেখা হয়নি",
  "Nome fantasia *": "ব্যবসায়িক নাম *", "Razão social": "আইনি নাম", "CNPJ *": "কোম্পানির কর নম্বর *", "CPF ou RG do diretor *": "আপনার পরিচয়পত্র নম্বর (পরিচালক) *",
  "Porte": "আকার", "Endereço completo *": "পূর্ণ ঠিকানা *", "Nome fantasia": "ব্যবসায়িক নাম", "CNPJ": "কোম্পানির কর নম্বর",
  "Inscrição municipal": "পৌর নিবন্ধন", "Torres / blocos": "টাওয়ার / ব্লক", "Unidades / vagas": "ইউনিট / পার্কিং",
  "Endereço completo": "পূর্ণ ঠিকানা", "Administradora responsável": "দায়িত্বপ্রাপ্ত ব্যবস্থাপনা কোম্পানি", "Síndico atual": "বর্তমান ব্যবস্থাপক",
  "Diretor administrativo": "প্রশাসনিক পরিচালক", "Início da gestão": "মেয়াদের শুরু", 
  "Horário de silêncio": "নীরবতার সময়", "Mudanças": "বাসা বদল", "Obras": "সংস্কার কাজ", "Visitantes": "অতিথি", "Animais": "পোষা প্রাণী",
  "Áreas comuns": "সাধারণ এলাকা", "Logo (upload)": "লোগো (আপলোড)", "Cor primária do portal": "পোর্টালের মূল রং",
  "Responsável financeiro": "আর্থিক দায়িত্বপ্রাপ্ত", "Área privativa (m²)": "ব্যক্তিগত আয়তন (m²)",
  "Vagas vinculadas": "সংযুক্ত পার্কিং", "Número": "নম্বর", "Bloco / torre": "ব্লক / টাওয়ার", "Andar": "তলা",
  "Número (ou início do intervalo)": "নম্বর (বা পরিসরের শুরু)", "Até o número (opcional)": "যে নম্বর পর্যন্ত (ঐচ্ছিক)",
  "Ex.: 402, 1 ou 1D": "যেমন: 402, 1 বা 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "যেমন: 100 বা 4D — খালি রাখলে একটিই তৈরি হবে",

  "Papel no condomínio": "আবাসনে ভূমিকা", "Unidade vinculada": "সংযুক্ত ইউনিট",
  "Data de entrada": "প্রবেশের তারিখ", "Documento (upload)": "নথি (আপলোড)",
  "Fundo de reserva": "সংরক্ষিত তহবিল", "Fundo de obras": "সংস্কার তহবিল", "Valor ($)": "পরিমাণ ($)",
  "Subcategoria / centro de custo": "উপবিভাগ / ব্যয় কেন্দ্র", "Forma de pagamento": "পরিশোধ পদ্ধতি", "Rateio": "বণ্টন",
  "Nota fiscal (anexo)": "চালান (সংযুক্তি)", "Aguardando pagamento": "পরিশোধের অপেক্ষায়",
  "Base de cálculo": "হিসাবের ভিত্তি", "Canais de envio": "পাঠানোর মাধ্যম",
  "Aplicadas em 2026": "২০২৬-এ প্রয়োগকৃত", "Em prazo de defesa": "আপত্তির সময়সীমার মধ্যে", "Arrecadado em multas": "জরিমানা থেকে আদায়",
  "Categoria da infração": "লঙ্ঘনের বিভাগ", "Unidade responsável": "দায়ী ইউনিট", "Data e hora": "তারিখ ও সময়",
  "Tipo de penalidade": "শাস্তির ধরন", "Valor (se multa)": "পরিমাণ (জরিমানা হলে)", "Prazo para defesa": "আপত্তির শেষ তারিখ",
  "Base normativa": "বিধিগত ভিত্তি", "Descrição detalhada": "বিস্তারিত বর্ণনা",
  "Provas (foto, vídeo, áudio ou documento)": "প্রমাণ (ছবি, ভিডিও, অডিও বা নথি)",
  "Destinatários": "প্রাপক", "Título": "শিরোনাম", "Mensagem": "বার্তা", "Canais": "মাধ্যম",
  "Unidade (se aplicável)": "ইউনিট (প্রযোজ্য হলে)", "Prioridade": "অগ্রাধিকার", "Prazo": "সময়সীমা",
  "Custo estimado": "আনুমানিক খরচ", "Fotos / vídeos": "ছবি / ভিডিও", "Descrição do problema": "সমস্যার বর্ণনা",
  "Acessos registrados": "নথিভুক্ত প্রবেশ", "Visitantes no condomínio": "আবাসনে অতিথি",
  "Entregas registradas": "নথিভুক্ত ডেলিভারি", "Vagas de visitante livres": "খালি অতিথি পার্কিং",
  "Nome / empresa": "নাম / কোম্পানি", "Unidade de destino": "গন্তব্য ইউনিট", "Janela de horário": "সময়সীমা",
  "Veículo (opcional)": "গাড়ি (ঐচ্ছিক)", 

  "Nova unidade": "নতুন ইউনিট", "Nova pessoa": "নতুন ব্যক্তি", "Novo lançamento": "নতুন এন্ট্রি",
  "Gerar cobranças da competência": "সময়কালের বিল তৈরি করুন", "Registrar infração": "লঙ্ঘন নথিভুক্ত করুন",
  "Novo documento timbrado": "নতুন লেটারহেড নথি", "Abrir chamado de manutenção": "রক্ষণাবেক্ষণ অনুরোধ খুলুন",
  "Pré-autorizar entrada": "প্রবেশের পূর্বানুমোদন", "Novo acesso": "নতুন অ্যাকাউন্ট", 
  "Abrir chamado": "অনুরোধ খুলুন",
  "Cancelar": "বাতিল", "Fechar": "বন্ধ করুন", "Exportar": "রপ্তানি", "Lançamento": "এন্ট্রি", "Pessoa": "ব্যক্তি",
  "Cadastrar unidade": "ইউনিট নিবন্ধন", "Criar unidade": "ইউনিট তৈরি করুন", "Cadastrar": "নিবন্ধন",
  "Salvar alterações": "পরিবর্তন সংরক্ষণ করুন", "Gerar cobranças": "বিল তৈরি করুন", "Gerar cobranças do mês": "এ মাসের বিল তৈরি করুন",
  "Reenviar": "পুনরায় পাঠান", "Baixar": "ডাউনলোড", "Enviar por WhatsApp": "WhatsApp-এ পাঠান", "Imprimir PDF": "PDF প্রিন্ট করুন",
  "Enviar ao responsável": "দায়িত্বপ্রাপ্তকে পাঠান", "Cancelar multa": "জরিমানা বাতিল করুন", "Aprovar (síndico)": "অনুমোদন (ব্যবস্থাপক)",
  "Enviar para aprovação": "অনুমোদনের জন্য পাঠান", "Ver": "দেখুন", "Publicar e enviar": "প্রকাশ করে পাঠান",
  "Criar documento timbrado": "লেটারহেড নথি তৈরি করুন", "Gerar PDF": "PDF তৈরি করুন",
  "Gerar QR de acesso": "প্রবেশ QR তৈরি করুন", "Registrar ocorrência": "ঘটনা নথিভুক্ত করুন",
  "Autorizar e gerar QR": "অনুমোদন দিয়ে QR তৈরি করুন", "Adicionar acesso": "অ্যাকাউন্ট যোগ করুন", "Remover": "মুছুন",
  "Criar acesso": "অ্যাকাউন্ট তৈরি করুন", 
  "Pagar": "পরিশোধ করুন", "Copiar código": "কোড কপি করুন", 
  "Tentar novamente": "আবার চেষ্টা করুন", "Voltar e trocar perfil": "ফিরে গিয়ে ভূমিকা বদলান", "Sair": "লগআউট",
  "Lançar e enviar para aprovação": "এন্ট্রি করে অনুমোদনে পাঠান", 
  "Salvando…": "সংরক্ষণ হচ্ছে…", "Criando…": "তৈরি হচ্ছে…", "Gerando…": "তৈরি হচ্ছে…", "Publicando…": "প্রকাশ হচ্ছে…",
  "Abrindo…": "খোলা হচ্ছে…", "Autorizando…": "অনুমোদন হচ্ছে…", "Enviando…": "পাঠানো হচ্ছে…",
  "Extrato": "বিবরণী",
  "Início": "হোম", "Pagamentos": "পরিশোধ", "Avisos": "নোটিশ",

  "Buscar por nome…": "নাম দিয়ে খুঁজুন…", "Buscar lançamento…": "এন্ট্রি খুঁজুন…",
  "Buscar por unidade ou responsável…": "ইউনিট বা দায়িত্বপ্রাপ্ত দিয়ে খুঁজুন…",
  "Nenhuma unidade encontrada": "কোনো ইউনিট পাওয়া যায়নি",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "খোঁজ বা ফিল্টার বদলান, অথবা এই আবাসনের প্রথম ইউনিট নিবন্ধন করুন।",
  "Nenhuma pessoa encontrada": "কোনো ব্যক্তি পাওয়া যায়নি",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "বিভ্রান্তি এড়াতে মালিক, ভাড়াটে, কর্মচারী ও সেবাদাতাদের আলাদা ভূমিকায় নিবন্ধন করুন।",
  "Nenhum lançamento neste período": "এই সময়ে কোনো এন্ট্রি নেই",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "নগদ প্রবাহ অনুসরণ শুরু করতে সময়কালের প্রথম আয় বা ব্যয় লিখুন।",
  "Nenhuma cobrança nesta competência": "এই সময়ে কোনো বিল নেই",

  "Nenhum documento nesta categoria": "এই বিভাগে কোনো নথি নেই",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "জরিমানা, নোটিশ, কার্যবিবরণী ও রসিদের লেটারহেড নথি এখানে স্বয়ংক্রিয়ভাবে সংরক্ষিত হয় এবং বছরের পর বছর থাকে।",
  "Nenhum acesso criado ainda": "এখনো কোনো অ্যাকাউন্ট তৈরি হয়নি",

  "Não foi possível carregar os dados": "ডেটা লোড করা যায়নি",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "সংযোগ পরীক্ষা করে আবার চেষ্টা করুন। সমস্যা থাকলে সহায়তা দলের সাথে যোগাযোগ করুন।",
};
