/* Français */
export default {
  "Condomínio": "Copropriété", "Unidades": "Unités", "Pessoas": "Personnes", "Financeiro": "Finances",
  "Cobranças QR": "Paiements QR", "Multas": "Amendes", "Comunicados": "Annonces", "Documentos": "Documents",
  "Manutenção": "Maintenance", "Portaria": "Accueil", "Gerenciar Emails": "Gérer les e-mails", "Painel SaaS": "Panneau SaaS",
  "Visão geral do condomínio em tempo real": "Vue d'ensemble de la copropriété en temps réel",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Fiche principale : données légales, gestion et règles internes",
  "96 unidades · 2 torres + térreo comercial": "96 unités · 2 tours + rez-de-chaussée commercial",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "Rôles séparés : propriétaire, locataire, employé et prestataire",
  "Competência 06/2026 · aprovações do síndico ativas": "Période 06/2026 · approbations du syndic actives",
  "QR Code Verum Pay com baixa automática": "QR Code Verum Pay avec règlement automatique",
  "Fluxo com prova, defesa e aprovação": "Processus avec preuve, défense et approbation",
  "Envio por portal, e-mail e WhatsApp": "Envoi par portail, e-mail et WhatsApp",
  "Arquivo timbrado com retenção histórica": "Archives à en-tête avec conservation historique",
  "Ordens de serviço por categoria e prioridade": "Ordres de service par catégorie et priorité",
  "Controle de acessos, entregas e ocorrências": "Contrôle des accès, livraisons et incidents",
  "Clientes, planos, licenças e implantação": "Clients, forfaits, licences et déploiement",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "E-mails et mots de passe des profils syndic, trésorerie, gestionnaire et résident",
  "Notificações": "Notifications", "Alternar tema": "Changer de thème", "Idioma": "Langue", "Perfil de acesso": "Profil d'accès",
  "Diretor": "Directeur", "Síndico": "Syndic", "Tesouraria": "Trésorerie", "Administradora": "Gestionnaire", "Morador": "Résident",
  "Visão estratégica, aprovações e auditoria": "Vision stratégique, approbations et audit",
  "Operação, multas, comunicados e manutenção": "Opérations, amendes, annonces et maintenance",
  "Financeiro, cobranças e conciliação": "Finances, paiements et rapprochement",
  "Gestão SaaS: clientes, planos e licenças": "Gestion SaaS : clients, forfaits et licences",
  "Boletos, comprovantes, comunicados e chamados": "Factures, reçus, annonces et demandes",
  "Gestão condominial premium · powered by Verum Pay": "Gestion de copropriété premium · powered by Verum Pay",
  "Criar acesso do diretor": "Créer l'accès du directeur",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Ceci est le premier accès. Le compte créé ici servira à se connecter en tant que",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": ", qui pourra enregistrer les e-mails et mots de passe des autres profils dans Gérer les e-mails.",
  "Nome completo": "Nom complet", "E-mail": "E-mail", "Senha": "Mot de passe", "Confirmar senha": "Confirmer le mot de passe",
  "Criar conta e continuar": "Créer le compte et continuer",
  "Já tem prédio cadastrado? Fazer login": "Immeuble déjà enregistré ? Se connecter",
  "Entrar como": "Se connecter en tant que", "Trocar perfil": "Changer de profil", "Voltar ao cadastro": "Retour à l'inscription",
  "Entrar": "Se connecter", "Verificando conta...": "Vérification du compte...",
  "E-mail ou senha incorretos.": "E-mail ou mot de passe incorrect.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "E-mail ou mot de passe incorrect. Demandez au directeur de vérifier votre accès dans Gérer les e-mails.",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "Aucun accès directeur trouvé sur cet appareil. Revenez en arrière et créez l'accès du directeur.",
  "Não foi possível verificar sua conta agora.": "Impossible de vérifier votre compte pour le moment.",
  "A senha deve ter pelo menos 4 caracteres.": "Le mot de passe doit contenir au moins 4 caractères.",
  "As senhas não conferem.": "Les mots de passe ne correspondent pas.",
  "Nenhum acesso de": "Aucun accès pour",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "n'a encore été créé. Demandez au directeur de l'enregistrer dans Gérer les e-mails.",
  "Tema claro": "Thème clair", "Tema escuro": "Thème sombre",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "Aucun accès avec ce nom. Demandez au directeur de l'enregistrer dans Gérer les e-mails.",
  "Senha incorreta para este nome.": "Mot de passe incorrect pour ce nom.",
  "Seu nome": "Votre nom", "voce@exemplo.com": "vous@exemple.com", "Mínimo 4 caracteres": "4 caractères minimum", "Repita a senha": "Répétez le mot de passe",
  "Saldo em caixa": "Solde de trésorerie", "Inadimplência": "Impayés", "Receitas de": "Revenus de", "Despesas de": "Dépenses de",
  "Nova cobrança": "Nouveau paiement", "Novo gasto": "Nouvelle dépense", "Nova multa": "Nouvelle amende", "Novo comunicado": "Nouvelle annonce", "Novo chamado": "Nouvelle demande",
  "Evolução financeira do mês — dia a dia": "Évolution financière du mois — jour par jour",
  "Distribuição de receitas": "Répartition des revenus", "Despesas por categoria": "Dépenses par catégorie",
  "Inadimplência ao longo do tempo": "Impayés dans le temps", "Atividade recente": "Activité récente",
  "Aprovações pendentes": "Approbations en attente", "Alertas do dia": "Alertes du jour", "Ver todas →": "Tout voir →",
  "Sem despesas em": "Aucune dépense en", "Sem receitas em": "Aucun revenu en", "Dia": "Jour",
  "Receita": "Revenu", "Despesa": "Dépense", "Multa": "Amende",
  "aguarda decisão do síndico": "attend la décision du syndic",
  "cobrança(s) vencida(s) somando": "paiement(s) en retard totalisant",
  "sem responsável designado": "sans responsable désigné",
  "Pago": "Payé", "Parcial": "Partiel", "Em aberto": "Ouvert", "Aguardando": "En attente", "Vencida": "En retard", "Emitida": "Émise",
  "Ocupada": "Occupée", "Alugada": "Louée", "Vaga": "Libre", "Ativo": "Actif", "Em teste": "En essai", "Inadimplente": "En impayé",
  "Prazo de defesa": "Délai de défense", "Multa aplicada": "Amende appliquée", "Advertência": "Avertissement",
  "Em andamento": "En cours", "Concluído": "Terminé", "No condomínio": "Sur place", "Saiu": "Parti", "Retirado": "Retiré",
  "Ocorrência": "Incident", "Cancelada": "Annulée", "Cancelado": "Annulé", "Vendida": "Vendue", "Reservada": "Réservée", "Inativa": "Inactive",
  "Alta": "Haute", "Média": "Moyenne", "Baixa": "Basse",
  "Todos os status": "Tous les statuts", "Todos os papéis": "Tous les rôles", "Todos": "Tous", "Pagas": "Payées", "Emitidas": "Émises", "Vencidas": "En retard",
  "Abertos": "Ouvertes", "Concluídos": "Terminées",
  "Nome": "Nom", "Papel": "Rôle", "Unidade": "Unité", "CPF/CNPJ": "Nº fiscal", "Telefone": "Téléphone", "Status": "Statut",
  "Data": "Date", "Tipo": "Type", "Categoria": "Catégorie", "Descrição": "Description", "Valor": "Montant",
  "Responsável": "Responsable", "Competência": "Période", "Vencimento": "Échéance", "Plano": "Forfait", "Mensalidade": "Mensualité", "Renovação": "Renouvellement",
  "Evolução da receita recorrente": "Évolution des revenus récurrents", "Planos": "Forfaits",
  "Últimos comunicados": "Dernières annonces", "Minha situação": "Ma situation", "Cobranças da unidade": "Paiements de l'unité",
  "Unidade / apartamento": "Unité / appartement", "Cadastre unidades primeiro na tela Unidades.": "Enregistrez d'abord des unités dans l'écran Unités.",
  "Nenhuma cobrança para esta unidade ainda.": "Aucun paiement pour cette unité pour l'instant.",
  "Toque para ler": "Appuyez pour lire",
  "Destino": "Destinataire", "Todas as unidades (rateio pela fração)": "Toutes les unités (réparti par quote-part)",
  "Valor da cobrança (R$)": "Montant du paiement (R$)",
  "Será gerada 1 cobrança para": "1 paiement sera généré pour",
  "O morador verá o aviso no portal dele.": "Le résident verra l'avis dans son portail.",
  "Serão geradas": "Le système générera", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "paiements (unités avec responsable financier), répartis par quote-part idéale.",
  "Gerar cobrança": "Générer le paiement", "Gerar": "Générer", "cobranças": "paiements",
  "Cobrança de": "Paiement de", "vencida": "en retard", "Nova cobrança de": "Nouveau paiement de",
  "vence em": "échéance le", "venceu em": "échu le",
  "Multas da unidade": "Amendes de l'unité",
  "Você pode apresentar defesa até": "Vous pouvez présenter une défense jusqu'au",
  "Procure a administração do condomínio.": "Contactez l'administration de la copropriété.",
  "Movimentação de hoje": "Mouvements du jour", "Nenhum chamado aqui": "Aucune demande ici", "sem custo lançado": "aucun coût enregistré",
  "Nome fantasia *": "Nom commercial *", "Razão social": "Raison sociale", "CNPJ *": "Nº fiscal de l'entreprise *", "Seu CPF (diretor) *": "Votre nº fiscal (directeur) *",
  "Porte": "Taille", "Endereço completo *": "Adresse complète *", "Nome fantasia": "Nom commercial", "CNPJ": "Nº fiscal de l'entreprise",
  "Inscrição municipal": "Immatriculation municipale", "Torres / blocos": "Tours / bâtiments", "Unidades / vagas": "Unités / places",
  "Endereço completo": "Adresse complète", "Administradora responsável": "Société gestionnaire", "Síndico atual": "Syndic actuel",
  "Diretor administrativo": "Directeur administratif", "Início da gestão": "Début du mandat", "Status do contrato SaaS": "Statut du contrat SaaS",
  "Horário de silêncio": "Heures de silence", "Mudanças": "Déménagements", "Obras": "Travaux", "Visitantes": "Visiteurs", "Animais": "Animaux",
  "Áreas comuns": "Espaces communs", "Logo (upload)": "Logo (envoi)", "Cor primária do portal": "Couleur principale du portail",
  "Responsável financeiro": "Responsable financier", "Fração ideal (%)": "Quote-part idéale (%)", "Área privativa (m²)": "Surface privative (m²)",
  "Vagas vinculadas": "Places liées", "Número": "Numéro", "Bloco / torre": "Bâtiment / tour", "Andar": "Étage",
  "Número (ou início do intervalo)": "Numéro (ou début de l'intervalle)", "Até o número (opcional)": "Jusqu'au numéro (facultatif)",
  "Ex.: 402, 1 ou 1D": "Ex. : 402, 1 ou 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Ex. : 100 ou 4D — vide n'en crée qu'une",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "Remplissez « Jusqu'au numéro » pour créer plusieurs unités à la fois : 1 à 100 crée 1, 2… 100 ; 1D à 4D crée 1D, 2D, 3D et 4D. Les numéros déjà existants dans le bâtiment sont ignorés. Type, étage, statut et quote-part s'appliquent à toutes.",
  "CPF ou CNPJ": "Nº fiscal", "Papel no condomínio": "Rôle dans la copropriété", "Unidade vinculada": "Unité liée",
  "Data de entrada": "Date d'entrée", "Documento (upload)": "Document (envoi)",
  "Fundo de reserva": "Fonds de réserve", "Fundo de obras": "Fonds travaux", "Valor (R$)": "Montant (R$)",
  "Subcategoria / centro de custo": "Sous-catégorie / centre de coûts", "Forma de pagamento": "Mode de paiement", "Rateio": "Répartition",
  "Nota fiscal (anexo)": "Facture (pièce jointe)", "Aguardando pagamento": "En attente de paiement",
  "Valor total a ratear (R$)": "Montant total à répartir (R$)", "Base de cálculo": "Base de calcul", "Canais de envio": "Canaux d'envoi",
  "Aplicadas em 2026": "Appliquées en 2026", "Em prazo de defesa": "En délai de défense", "Arrecadado em multas": "Collecté en amendes",
  "Categoria da infração": "Catégorie de l'infraction", "Unidade responsável": "Unité responsable", "Data e hora": "Date et heure",
  "Tipo de penalidade": "Type de sanction", "Valor (se multa)": "Montant (si amende)", "Prazo para defesa": "Délai de défense",
  "Base normativa": "Base réglementaire", "Descrição detalhada": "Description détaillée",
  "Provas (foto, vídeo, áudio ou documento)": "Preuves (photo, vidéo, audio ou document)",
  "Destinatários": "Destinataires", "Título": "Titre", "Mensagem": "Message", "Canais": "Canaux",
  "Unidade (se aplicável)": "Unité (le cas échéant)", "Conteúdo": "Contenu", "Prioridade": "Priorité", "Prazo": "Délai",
  "Custo estimado": "Coût estimé", "Fotos / vídeos": "Photos / vidéos", "Descrição do problema": "Description du problème",
  "Acessos registrados": "Accès enregistrés", "Visitantes no condomínio": "Visiteurs sur place",
  "Entregas registradas": "Livraisons enregistrées", "Vagas de visitante livres": "Places visiteurs libres",
  "Nome / empresa": "Nom / entreprise", "Unidade de destino": "Unité de destination", "Janela de horário": "Plage horaire",
  "Veículo (opcional)": "Véhicule (facultatif)", "Condomínios ativos": "Copropriétés actives",
  "Receita recorrente (MRR)": "Revenus récurrents (MRR)", "Em período de teste": "En période d'essai",
  "Nova unidade": "Nouvelle unité", "Nova pessoa": "Nouvelle personne", "Novo lançamento": "Nouvelle écriture",
  "Gerar cobranças da competência": "Générer les paiements de la période", "Registrar infração": "Enregistrer une infraction",
  "Novo documento timbrado": "Nouveau document à en-tête", "Abrir chamado de manutenção": "Ouvrir une demande de maintenance",
  "Pré-autorizar entrada": "Préautoriser une entrée", "Novo acesso": "Nouvel accès", "Contratar novo condomínio": "Intégrer une nouvelle copropriété",
  "Abrir chamado": "Ouvrir une demande",
  "Cancelar": "Annuler", "Fechar": "Fermer", "Exportar": "Exporter", "Lançamento": "Écriture", "Pessoa": "Personne",
  "Cadastrar unidade": "Enregistrer l'unité", "Criar unidade": "Créer l'unité", "Cadastrar": "Enregistrer",
  "Salvar alterações": "Enregistrer les modifications", "Gerar cobranças": "Générer les paiements", "Gerar cobranças do mês": "Générer les paiements du mois",
  "Reenviar": "Renvoyer", "Baixar": "Télécharger", "Enviar por WhatsApp": "Envoyer par WhatsApp", "Imprimir PDF": "Imprimer le PDF",
  "Enviar ao responsável": "Envoyer au responsable", "Cancelar multa": "Annuler l'amende", "Aprovar (síndico)": "Approuver (syndic)",
  "Enviar para aprovação": "Envoyer pour approbation", "Ver": "Voir", "Publicar e enviar": "Publier et envoyer",
  "Criar documento timbrado": "Créer un document à en-tête", "Gerar PDF": "Générer le PDF",
  "Gerar QR de acesso": "Générer le QR d'accès", "Registrar ocorrência": "Enregistrer un incident",
  "Autorizar e gerar QR": "Autoriser et générer le QR", "Adicionar acesso": "Ajouter un accès", "Remover": "Supprimer",
  "Criar acesso": "Créer l'accès", "Novo cliente": "Nouveau client", "Bloquear acesso": "Bloquer l'accès", "Abrir painel": "Ouvrir le panneau",
  "Iniciar implantação": "Démarrer le déploiement", "Pagar": "Payer", "Copiar código": "Copier le code", "Enviar chamado": "Envoyer la demande",
  "Tentar novamente": "Réessayer", "Voltar e trocar perfil": "Revenir et changer de profil", "Sair": "Se déconnecter",
  "Lançar e enviar para aprovação": "Saisir et envoyer pour approbation", "Criar condomínio e começar": "Créer la copropriété et commencer",
  "Salvando…": "Enregistrement…", "Criando…": "Création…", "Gerando…": "Génération…", "Publicando…": "Publication…",
  "Abrindo…": "Ouverture…", "Autorizando…": "Autorisation…", "Enviando…": "Envoi…",
  "Boletos e QR": "Factures et QR", "Extrato": "Relevé",
  "Início": "Accueil", "Pagamentos": "Paiements", "Avisos": "Avis",
  "Buscar por número, bloco ou responsável…": "Rechercher par numéro, bâtiment ou responsable…",
  "Buscar por nome…": "Rechercher par nom…", "Buscar lançamento…": "Rechercher une écriture…",
  "Buscar por unidade ou responsável…": "Rechercher par unité ou responsable…",
  "Nenhuma unidade encontrada": "Aucune unité trouvée",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Ajustez la recherche ou les filtres, ou enregistrez la première unité de cette copropriété.",
  "Nenhuma pessoa encontrada": "Aucune personne trouvée",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Enregistrez propriétaires, locataires, employés et prestataires avec des rôles séparés pour éviter toute confusion.",
  "Nenhum lançamento neste período": "Aucune écriture sur cette période",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Saisissez le premier revenu ou la première dépense de la période pour suivre la trésorerie.",
  "Nenhuma cobrança nesta competência": "Aucun paiement sur cette période",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "Générez les paiements du mois : le système crée un QR Code Verum Pay unique par unité et l'envoie via portail, e-mail ou WhatsApp.",
  "Nenhum documento nesta categoria": "Aucun document dans cette catégorie",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Les documents à en-tête (amendes, annonces, procès-verbaux, reçus) sont archivés automatiquement ici, conservés pendant des années.",
  "Nenhum acesso criado ainda": "Aucun accès créé pour l'instant",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "Enregistrez le premier e-mail et mot de passe pour que syndic, trésorerie, gestionnaire et résidents puissent se connecter.",
  "Não foi possível carregar os dados": "Impossible de charger les données",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Vérifiez la connexion et réessayez. Si le problème persiste, contactez le support.",
};
