/* Français */
export default {
  "Condomínio": "Copropriété", "Unidades": "Unités", "Pessoas": "Personnes", "Financeiro": "Finances",
  "Cobranças QR": "Paiements QR", "Multas": "Amendes", "Comunicados": "Annonces", "Documentos": "Documents",
  "Manutenção": "Maintenance", "Portaria": "Accueil", "Gerenciar Acessos": "Gérer les accès", 
  "Visão geral do condomínio em tempo real": "Vue d'ensemble de la copropriété en temps réel",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Fiche principale : données légales, gestion et règles internes",

  /* subtítulos dinâmicos do cabeçalho */
  "unidade": "unité", "unidades": "unités", "bloco/torre": "bâtiment/tour", "blocos/torres": "bâtiments/tours",
  "pessoa cadastrada": "personne enregistrée", "pessoas cadastradas": "personnes enregistrées",
  "aprovações do síndico ativas": "approbations du syndic actives",
  "cobrança em aberto": "paiement en attente", "cobranças em aberto": "paiements en attente", "vencidas": "en retard",
  "multa/advertência registrada": "amende/avertissement enregistré", "multas/advertências registradas": "amendes/avertissements enregistrés",
  "comunicado publicado": "communiqué publié", "comunicados publicados": "communiqués publiés",
  "documento arquivado": "document archivé", "documentos arquivados": "documents archivés",
  "chamado em aberto": "ordre de service ouvert", "chamados em aberto": "ordres de service ouverts",
  /* teste gratuito de 30 dias */
  "Ative seu teste gratuito de 30 dias — cadastre o cartão; nada será cobrado agora.": "Activez votre essai gratuit de 30 jours — enregistrez la carte ; rien n'est débité maintenant.",
  "O período de avaliação terminou. Ative a assinatura para continuar.": "La période d'essai est terminée. Activez l'abonnement pour continuer.",
  "Iniciar teste gratuito de 30 dias": "Démarrer l'essai gratuit de 30 jours",

  "A troca de plano durante o teste gratuito é cobrada imediatamente — aguarde o fim do teste para trocar.": "Le changement de forfait pendant l'essai gratuit est facturé immédiatement — attendez la fin de l'essai pour changer.",
  "Teste gratuito — termina em": "Essai gratuit — se termine dans", "dia(s)": "jour(s)",
  "Depois, a cobrança é feita automaticamente no cartão cadastrado.": "Ensuite, le prélèvement est effectué automatiquement sur la carte enregistrée.",

  "Tenho um código de ativação": "J'ai un code d'activation", "Código de ativação": "Code d'activation",
  "Ativar": "Activer", "Ativando…": "Activation…",

  "Código aplicado. Se o acesso não liberar em instantes, use \"Já paguei — verificar\".": "Code appliqué. Si l'accès ne se débloque pas d'ici peu, utilisez \"Já paguei — verificar\".",

  "Cancelar assinatura": "Annuler l'abonnement",
  "Cancelar a assinatura? O acesso continua até o fim do período já pago e nenhuma cobrança futura será feita.": "Annuler l'abonnement ? L'accès continue jusqu'à la fin de la période déjà payée et aucun prélèvement futur ne sera effectué.",
  "Cancelamento agendado — o acesso continua até": "Annulation programmée — l'accès continue jusqu'au",
  "Assinatura cancelada.": "Abonnement annulé.",
  "Assinatura cancelada em": "Abonnement annulé le", "o acesso será desativado em": "l'accès sera désactivé le",
  "Nenhuma cobrança futura será feita.": "Aucun prélèvement futur ne sera effectué.",
  "Acima da franquia do plano": "Au-delà du quota inclus dans le forfait",
  "o excedente é cobrado por unidade adicional na fatura da licença.": "l'excédent est facturé par unité supplémentaire sur la facture de la licence.",

  "Controle de acessos, entregas e ocorrências": "Contrôle des accès, livraisons et incidents",

  "Notificações": "Notifications", "Alternar tema": "Changer de thème", "Idioma": "Langue", "Perfil de acesso": "Profil d'accès",
  "Diretor": "Directeur", "Síndico": "Syndic", "Tesouraria": "Trésorerie", "Administradora": "Gestionnaire", "Morador": "Résident",
  "Visão estratégica, aprovações e auditoria": "Vision stratégique, approbations et audit",
  "Operação, multas, comunicados e manutenção": "Opérations, amendes, annonces et maintenance",
  "Financeiro, cobranças e conciliação": "Finances, paiements et rapprochement",

  "Boletos, comprovantes, comunicados e chamados": "Factures, reçus, annonces et demandes",
  "Gestão condominial premium · powered by Serve Now Global": "Gestion de copropriété premium · powered by Serve Now Global",
  "Criar acesso do diretor": "Créer l'accès du directeur",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Ceci est le premier accès. Le compte créé ici servira à se connecter en tant que",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Acessos.": ", qui pourra enregistrer les e-mails et mots de passe des autres profils dans Gérer les accès.",
  "Nome completo": "Nom complet", "E-mail": "E-mail", "Senha": "Mot de passe", "Confirmar senha": "Confirmer le mot de passe",
  "Criar conta e continuar": "Créer le compte et continuer",
  "Já tem prédio cadastrado? Fazer login": "Immeuble déjà enregistré ? Se connecter",
  "Entrar como": "Se connecter en tant que", "Trocar perfil": "Changer de profil", "Voltar ao cadastro": "Retour à l'inscription",
  "Entrar": "Se connecter", "Verificando conta...": "Vérification du compte...",
  "E-mail ou senha incorretos.": "E-mail ou mot de passe incorrect.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Acessos.": "E-mail ou mot de passe incorrect. Demandez au directeur de vérifier votre accès dans Gérer les accès.",

  "Não foi possível verificar sua conta agora.": "Impossible de vérifier votre compte pour le moment.",

  "As senhas não conferem.": "Les mots de passe ne correspondent pas.",
  "Nenhum acesso de": "Aucun accès pour",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Acessos.": "n'a encore été créé. Demandez au directeur de l'enregistrer dans Gérer les accès.",
  "Tema claro": "Thème clair", "Tema escuro": "Thème sombre",

  "Seu nome": "Votre nom", "voce@exemplo.com": "vous@exemple.com", "Repita a senha": "Répétez le mot de passe",
  "Saldo em caixa": "Solde de trésorerie", "Inadimplência": "Impayés", "Receitas de": "Revenus de", "Despesas de": "Dépenses de",
  "Nova cobrança": "Nouveau paiement", "Novo gasto": "Nouvelle dépense", "Nova multa": "Nouvelle amende", "Novo comunicado": "Nouvelle annonce", "Novo chamado": "Nouvelle demande",
  "Evolução financeira do mês — dia a dia": "Évolution financière du mois — jour par jour",
  "Distribuição de receitas": "Répartition des revenus", "Despesas por categoria": "Dépenses par catégorie",
  "Inadimplência ao longo do tempo": "Impayés dans le temps", 
  "Aprovações pendentes": "Approbations en attente", "Alertas do dia": "Alertes du jour", "Ver todas →": "Tout voir →",
  "Sem despesas em": "Aucune dépense en", "Sem receitas em": "Aucun revenu en", "Dia": "Jour",
  "Receita": "Revenu", "Despesa": "Dépense", "Multa": "Amende",
  "aguarda decisão do síndico": "attend la décision du syndic",
  "cobrança(s) vencida(s) somando": "paiement(s) en retard totalisant",
  "sem responsável designado": "sans responsable désigné",
  "Pago": "Payé", "Entrada": "Encaissée", "Parcial": "Partiel", "Em aberto": "Ouvert", "Aguardando": "En attente", "Vencida": "En retard", "Emitida": "Émise",
  "Ocupada": "Occupée", "Alugada": "Louée", "Vaga": "Libre", "Ativo": "Actif", "Em teste": "En essai", "Inadimplente": "En impayé",
  "Prazo de defesa": "Délai de défense", "Multa aplicada": "Amende appliquée", "Advertência": "Avertissement",
  "Em andamento": "En cours", "Concluído": "Terminé", "No condomínio": "Sur place", "Saiu": "Parti", "Retirado": "Retiré",
  "Ocorrência": "Incident", "Cancelada": "Annulée", "Cancelado": "Annulé", "Vendida": "Vendue", "Reservada": "Réservée", "Inativa": "Inactive",
  "Alta": "Haute", "Média": "Moyenne", "Baixa": "Basse",
  "Todos os status": "Tous les statuts", "Todos os papéis": "Tous les rôles", "Todos": "Tous", "Pagas": "Payées", "Emitidas": "Émises", "Vencidas": "En retard",
  "Abertos": "Ouvertes", "Concluídos": "Terminées",
  "Nome": "Nom", "Papel": "Rôle", "Unidade": "Unité", "Telefone": "Téléphone", "Status": "Statut",
  "Data": "Date", "Tipo": "Type", "Categoria": "Catégorie", "Descrição": "Description", "Valor": "Montant",
  "Responsável": "Responsable", "Competência": "Période", "Vencimento": "Échéance", "Plano": "Forfait", "Mensalidade": "Mensualité", "Mensal": "Mensuel", "Anual": "Annuel", "Anuidade": "Annuité", 
  "Planos": "Forfaits",
  "Últimos comunicados": "Dernières annonces", "Minha situação": "Ma situation", "Cobranças da unidade": "Paiements de l'unité",
  "Unidade / apartamento": "Unité / appartement", "Cadastre unidades primeiro na tela Unidades.": "Enregistrez d'abord des unités dans l'écran Unités.",
  "Nenhuma cobrança para esta unidade ainda.": "Aucun paiement pour cette unité pour l'instant.",
  "Toque para ler": "Appuyez pour lire",
  "Destino": "Destinataire", "Todas as unidades (rateio pela fração)": "Toutes les unités (réparti par quote-part)",

  "Será gerada 1 cobrança para": "1 paiement sera généré pour",
  "O morador verá o aviso no portal dele.": "Le résident verra l'avis dans son portail.",
  "Serão geradas": "Le système générera", 
  "Gerar cobrança": "Générer le paiement", "Gerar": "Générer", "cobranças": "paiements",
  "Cobrança de": "Paiement de", "vencida": "en retard", "Nova cobrança de": "Nouveau paiement de",
  "vence em": "échéance le", "venceu em": "échu le",

  "Você pode apresentar defesa até": "Vous pouvez présenter une défense jusqu'au",
  "Procure a administração do condomínio.": "Contactez l'administration de la copropriété.",
  "Movimentação de hoje": "Mouvements du jour", "Nenhum chamado aqui": "Aucune demande ici", "sem custo lançado": "aucun coût enregistré",
  "Nome fantasia *": "Nom commercial *", "Razão social": "Raison sociale", "CNPJ *": "Nº fiscal de l'entreprise *", "CPF ou RG do diretor *": "Nº fiscal ou pièce d'identité (directeur) *",
  "Porte": "Taille", "Endereço completo *": "Adresse complète *", "Nome fantasia": "Nom commercial", "CNPJ": "Nº fiscal de l'entreprise",
  "Inscrição municipal": "Immatriculation municipale", "Torres / blocos": "Tours / bâtiments", "Unidades / vagas": "Unités / places",
  "Endereço completo": "Adresse complète", "Administradora responsável": "Société gestionnaire", "Síndico atual": "Syndic actuel",
  "Diretor administrativo": "Directeur administratif", "Início da gestão": "Début du mandat", 
  "Horário de silêncio": "Heures de silence", "Mudanças": "Déménagements", "Obras": "Travaux", "Visitantes": "Visiteurs", "Animais": "Animaux",
  "Áreas comuns": "Espaces communs", "Logo (upload)": "Logo (envoi)", "Cor primária do portal": "Couleur principale du portail",
  "Responsável financeiro": "Responsable financier", "Área privativa (m²)": "Surface privative (m²)",
  "Vagas vinculadas": "Places liées", "Número": "Numéro", "Bloco / torre": "Bâtiment / tour", "Andar": "Étage",
  "Número (ou início do intervalo)": "Numéro (ou début de l'intervalle)", "Até o número (opcional)": "Jusqu'au numéro (facultatif)",
  "Ex.: 402, 1 ou 1D": "Ex. : 402, 1 ou 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Ex. : 100 ou 4D — vide n'en crée qu'une",

  "Papel no condomínio": "Rôle dans la copropriété", "Unidade vinculada": "Unité liée",
  "Data de entrada": "Date d'entrée", "Documento (upload)": "Document (envoi)",
  "Fundo de reserva": "Fonds de réserve", "Fundo de obras": "Fonds travaux", "Valor ($)": "Montant ($)",
  "Subcategoria / centro de custo": "Sous-catégorie / centre de coûts", "Forma de pagamento": "Mode de paiement", "Rateio": "Répartition",
  "Nota fiscal (anexo)": "Facture (pièce jointe)", "Aguardando pagamento": "En attente de paiement",
  "Base de cálculo": "Base de calcul", "Canais de envio": "Canaux d'envoi",
  "Aplicadas em 2026": "Appliquées en 2026", "Em prazo de defesa": "En délai de défense", "Arrecadado em multas": "Collecté en amendes",
  "Categoria da infração": "Catégorie de l'infraction", "Unidade responsável": "Unité responsable", "Data e hora": "Date et heure",
  "Tipo de penalidade": "Type de sanction", "Valor (se multa)": "Montant (si amende)", "Prazo para defesa": "Délai de défense",
  "Base normativa": "Base réglementaire", "Descrição detalhada": "Description détaillée",
  "Provas (foto, vídeo, áudio ou documento)": "Preuves (photo, vidéo, audio ou document)",
  "Destinatários": "Destinataires", "Título": "Titre", "Mensagem": "Message", "Canais": "Canaux",
  "Unidade (se aplicável)": "Unité (le cas échéant)", "Prioridade": "Priorité", "Prazo": "Délai",
  "Custo estimado": "Coût estimé", "Fotos / vídeos": "Photos / vidéos", "Descrição do problema": "Description du problème",
  "Acessos registrados": "Accès enregistrés", "Visitantes no condomínio": "Visiteurs sur place",
  "Entregas registradas": "Livraisons enregistrées", "Vagas de visitante livres": "Places visiteurs libres",
  "Nome / empresa": "Nom / entreprise", "Unidade de destino": "Unité de destination", "Janela de horário": "Plage horaire",
  "Veículo (opcional)": "Véhicule (facultatif)", 

  "Nova unidade": "Nouvelle unité", "Nova pessoa": "Nouvelle personne", "Novo lançamento": "Nouvelle écriture",
  "Gerar cobranças da competência": "Générer les paiements de la période", "Registrar infração": "Enregistrer une infraction",
  "Novo documento timbrado": "Nouveau document à en-tête", "Abrir chamado de manutenção": "Ouvrir une demande de maintenance",
  "Pré-autorizar entrada": "Préautoriser une entrée", "Novo acesso": "Nouvel accès", 
  "Abrir chamado": "Ouvrir une demande",
  "Cancelar": "Annuler", "Fechar": "Fermer", "Exportar": "Exporter", "Lançamento": "Écriture", "Pessoa": "Personne",
  "Cadastrar unidade": "Enregistrer l'unité", "Criar unidade": "Créer l'unité", "Cadastrar": "Enregistrer",
  "Salvar alterações": "Enregistrer les modifications", "Gerar cobranças": "Générer les paiements", "Gerar cobranças do mês": "Générer les paiements du mois",
  "Reenviar": "Renvoyer", "Baixar": "Télécharger", "Enviar por WhatsApp": "Envoyer par WhatsApp", "Imprimir PDF": "Imprimer le PDF",
  "Enviar ao responsável": "Envoyer au responsable", "Cancelar multa": "Annuler l'amende", "Aprovar (síndico)": "Approuver (syndic)",
  "Enviar para aprovação": "Envoyer pour approbation", "Ver": "Voir", "Publicar e enviar": "Publier et envoyer",
  "Criar documento timbrado": "Créer un document à en-tête", "Gerar PDF": "Générer le PDF",
  "Gerar QR de acesso": "Générer le QR d'accès", "Registrar ocorrência": "Enregistrer un incident",
  "Autorizar e gerar QR": "Autoriser et générer le QR", "Adicionar acesso": "Ajouter un accès", "Remover": "Supprimer",
  "Criar acesso": "Créer l'accès", 
  "Pagar": "Payer", "Copiar código": "Copier le code", 
  "Tentar novamente": "Réessayer", "Voltar e trocar perfil": "Revenir et changer de profil", "Sair": "Se déconnecter",
  "Lançar e enviar para aprovação": "Saisir et envoyer pour approbation", 
  "Salvando…": "Enregistrement…", "Criando…": "Création…", "Gerando…": "Génération…", "Publicando…": "Publication…",
  "Abrindo…": "Ouverture…", "Autorizando…": "Autorisation…", "Enviando…": "Envoi…",
  "Extrato": "Relevé",
  "Início": "Accueil", "Pagamentos": "Paiements", "Avisos": "Avis",

  "Buscar por nome…": "Rechercher par nom…", "Buscar lançamento…": "Rechercher une écriture…",
  "Buscar por unidade ou responsável…": "Rechercher par unité ou responsable…",
  "Nenhuma unidade encontrada": "Aucune unité trouvée",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Ajustez la recherche ou les filtres, ou enregistrez la première unité de cette copropriété.",
  "Nenhuma pessoa encontrada": "Aucune personne trouvée",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Enregistrez propriétaires, locataires, employés et prestataires avec des rôles séparés pour éviter toute confusion.",
  "Nenhum lançamento neste período": "Aucune écriture sur cette période",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Saisissez le premier revenu ou la première dépense de la période pour suivre la trésorerie.",
  "Nenhuma cobrança nesta competência": "Aucun paiement sur cette période",

  "Nenhum documento nesta categoria": "Aucun document dans cette catégorie",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Les documents à en-tête (amendes, annonces, procès-verbaux, reçus) sont archivés automatiquement ici, conservés pendant des années.",
  "Nenhum acesso criado ainda": "Aucun accès créé pour l'instant",

  "Não foi possível carregar os dados": "Impossible de charger les données",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Vérifiez la connexion et réessayez. Si le problème persiste, contactez le support.",
};
