/* हिन्दी */
export default {
  "Condomínio": "सोसाइटी", "Unidades": "यूनिट", "Pessoas": "लोग", "Financeiro": "वित्त",
  "Cobranças QR": "QR भुगतान", "Multas": "जुर्माने", "Comunicados": "सूचनाएँ", "Documentos": "दस्तावेज़",
  "Manutenção": "रखरखाव", "Portaria": "रिसेप्शन", "Gerenciar Emails": "ईमेल प्रबंधन", "Painel SaaS": "SaaS पैनल",
  "Visão geral do condomínio em tempo real": "सोसाइटी का रीयल-टाइम अवलोकन",
  "Cadastro-mãe: dados legais, gestão e regras internas": "मुख्य रिकॉर्ड: कानूनी विवरण, प्रबंधन और आंतरिक नियम",
  "96 unidades · 2 torres + térreo comercial": "96 यूनिट · 2 टावर + व्यावसायिक भूतल",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "अलग-अलग भूमिकाएँ: मालिक, किरायेदार, कर्मचारी और सेवा प्रदाता",
  "Competência 06/2026 · aprovações do síndico ativas": "अवधि 06/2026 · प्रबंधक की स्वीकृतियाँ सक्रिय",
  "QR Code Verum Pay com baixa automática": "स्वचालित मिलान वाला Verum Pay QR कोड",
  "Fluxo com prova, defesa e aprovação": "सबूत, आपत्ति और स्वीकृति की प्रक्रिया",
  "Envio por portal, e-mail e WhatsApp": "पोर्टल, ईमेल और WhatsApp से भेजना",
  "Arquivo timbrado com retenção histórica": "लेटरहेड दस्तावेज़ों का दीर्घकालिक संग्रह",
  "Ordens de serviço por categoria e prioridade": "श्रेणी और प्राथमिकता के अनुसार कार्य आदेश",
  "Controle de acessos, entregas e ocorrências": "प्रवेश, डिलीवरी और घटनाओं का प्रबंधन",
  "Clientes, planos, licenças e implantação": "ग्राहक, प्लान, लाइसेंस और सेटअप",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "प्रबंधक, कोषाध्यक्ष, प्रबंधन कंपनी और निवासियों के लॉगिन विवरण",
  "Notificações": "सूचनाएँ", "Alternar tema": "थीम बदलें", "Idioma": "भाषा", "Perfil de acesso": "एक्सेस भूमिका",
  "Diretor": "निदेशक", "Síndico": "प्रबंधक", "Tesouraria": "कोषाध्यक्ष", "Administradora": "प्रबंधन कंपनी", "Morador": "निवासी",
  "Visão estratégica, aprovações e auditoria": "रणनीतिक दृष्टि, स्वीकृतियाँ और ऑडिट",
  "Operação, multas, comunicados e manutenção": "संचालन, जुर्माने, सूचनाएँ और रखरखाव",
  "Financeiro, cobranças e conciliação": "वित्त, भुगतान और मिलान",
  "Gestão SaaS: clientes, planos e licenças": "SaaS प्रबंधन: ग्राहक, प्लान और लाइसेंस",
  "Boletos, comprovantes, comunicados e chamados": "बिल, रसीदें, सूचनाएँ और अनुरोध",
  "Gestão condominial premium · powered by Verum Pay": "प्रीमियम सोसाइटी प्रबंधन · powered by Verum Pay",
  "Criar acesso do diretor": "निदेशक खाता बनाएँ",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "यह पहला लॉगिन है। यहाँ बनाया गया खाता इस भूमिका से लॉगिन के लिए इस्तेमाल होगा:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": "। यह भूमिका \"ईमेल प्रबंधन\" में बाकी भूमिकाओं के ईमेल और पासवर्ड दर्ज कर सकेगी।",
  "Nome completo": "पूरा नाम", "E-mail": "ईमेल", "Senha": "पासवर्ड", "Confirmar senha": "पासवर्ड की पुष्टि करें",
  "Criar conta e continuar": "खाता बनाएँ और आगे बढ़ें",
  "Já tem prédio cadastrado? Fazer login": "इमारत पहले से पंजीकृत है? लॉगिन करें",
  "Entrar como": "इस रूप में लॉगिन करें", "Trocar perfil": "भूमिका बदलें", "Voltar ao cadastro": "पंजीकरण पर वापस जाएँ",
  "Entrar": "लॉगिन", "Verificando conta...": "खाता सत्यापित हो रहा है...",
  "E-mail ou senha incorretos.": "ईमेल या पासवर्ड गलत है।",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "ईमेल या पासवर्ड गलत है। निदेशक से \"ईमेल प्रबंधन\" में अपना खाता जाँचने को कहें।",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "इस डिवाइस पर निदेशक खाता नहीं मिला। वापस जाकर निदेशक खाता बनाएँ।",
  "Não foi possível verificar sua conta agora.": "अभी आपका खाता सत्यापित नहीं हो सका।",
  "A senha deve ter pelo menos 4 caracteres.": "पासवर्ड कम से कम 4 अक्षरों का होना चाहिए।",
  "As senhas não conferem.": "पासवर्ड मेल नहीं खाते।",
  "Nenhum acesso de": "इस भूमिका का कोई खाता नहीं:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "। निदेशक से \"ईमेल प्रबंधन\" में इसे बनाने को कहें।",
  "Tema claro": "लाइट थीम", "Tema escuro": "डार्क थीम",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "इस नाम का कोई खाता नहीं। निदेशक से \"ईमेल प्रबंधन\" में पंजीकरण करने को कहें।",
  "Senha incorreta para este nome.": "इस नाम के लिए पासवर्ड गलत है।",
  "Seu nome": "आपका नाम", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "कम से कम 4 अक्षर", "Repita a senha": "पासवर्ड दोबारा लिखें",
  "Saldo em caixa": "नकद शेष", "Inadimplência": "बकाया दर", "Receitas de": "आय —", "Despesas de": "व्यय —",
  "Nova cobrança": "नया भुगतान", "Novo gasto": "नया खर्च", "Nova multa": "नया जुर्माना", "Novo comunicado": "नई सूचना", "Novo chamado": "नया अनुरोध",
  "Evolução financeira do mês — dia a dia": "महीने की वित्तीय स्थिति — दिन-प्रतिदिन",
  "Distribuição de receitas": "आय का वितरण", "Despesas por categoria": "श्रेणी अनुसार व्यय",
  "Inadimplência ao longo do tempo": "समय के साथ बकाया", "Atividade recente": "हाल की गतिविधि",
  "Aprovações pendentes": "लंबित स्वीकृतियाँ", "Alertas do dia": "आज की चेतावनियाँ", "Ver todas →": "सभी देखें →",
  "Sem despesas em": "कोई व्यय नहीं:", "Sem receitas em": "कोई आय नहीं:", "Dia": "दिन",
  "Receita": "आय", "Despesa": "व्यय", "Multa": "जुर्माना",
  "aguarda decisão do síndico": "प्रबंधक के निर्णय की प्रतीक्षा में",
  "cobrança(s) vencida(s) somando": "बकाया भुगतान, कुल",
  "sem responsável designado": "कोई ज़िम्मेदार नियुक्त नहीं",
  "Pago": "भुगतान हुआ", "Parcial": "आंशिक", "Em aberto": "खुला", "Aguardando": "प्रतीक्षा में", "Vencida": "बकाया", "Emitida": "जारी",
  "Ocupada": "आबाद", "Alugada": "किराए पर", "Vaga": "खाली", "Ativo": "सक्रिय", "Em teste": "परीक्षण में", "Inadimplente": "बकाएदार",
  "Prazo de defesa": "आपत्ति अवधि", "Multa aplicada": "जुर्माना लागू", "Advertência": "चेतावनी",
  "Em andamento": "प्रगति में", "Concluído": "पूर्ण", "No condomínio": "परिसर में", "Saiu": "बाहर गया", "Retirado": "प्राप्त किया",
  "Ocorrência": "घटना", "Cancelada": "रद्द", "Cancelado": "रद्द", "Vendida": "बिकी", "Reservada": "आरक्षित", "Inativa": "निष्क्रिय",
  "Alta": "उच्च", "Média": "मध्यम", "Baixa": "निम्न",
  "Todos os status": "सभी स्थितियाँ", "Todos os papéis": "सभी भूमिकाएँ", "Todos": "सभी", "Pagas": "भुगतान हुए", "Emitidas": "जारी", "Vencidas": "बकाया",
  "Abertos": "खुले", "Concluídos": "पूर्ण",
  "Nome": "नाम", "Papel": "भूमिका", "Unidade": "यूनिट", "CPF/CNPJ": "पहचान संख्या", "Telefone": "फ़ोन", "Status": "स्थिति",
  "Data": "तारीख़", "Tipo": "प्रकार", "Categoria": "श्रेणी", "Descrição": "विवरण", "Valor": "राशि",
  "Responsável": "ज़िम्मेदार", "Competência": "अवधि", "Vencimento": "देय तिथि", "Plano": "प्लान", "Mensalidade": "मासिक शुल्क", "Renovação": "नवीनीकरण",
  "Evolução da receita recorrente": "आवर्ती आय की प्रगति", "Planos": "प्लान",
  "Últimos comunicados": "ताज़ा सूचनाएँ", "Minha situação": "मेरी स्थिति", "Cobranças da unidade": "यूनिट के भुगतान",
  "Unidade / apartamento": "यूनिट / फ्लैट", "Cadastre unidades primeiro na tela Unidades.": "पहले \"यूनिट\" स्क्रीन में यूनिट पंजीकृत करें।",
  "Nenhuma cobrança para esta unidade ainda.": "इस यूनिट के लिए अभी कोई भुगतान नहीं।",
  "Toque para ler": "पढ़ने के लिए टैप करें",
  "Destino": "लक्ष्य", "Todas as unidades (rateio pela fração)": "सभी यूनिट (हिस्से के अनुसार बँटवारा)",
  "Valor da cobrança (R$)": "भुगतान राशि (R$)",
  "Será gerada 1 cobrança para": "1 भुगतान बनाया जाएगा:",
  "O morador verá o aviso no portal dele.": "निवासी को अपने पोर्टल में सूचना दिखेगी।",
  "Serão geradas": "सिस्टम बनाएगा", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "भुगतान (वित्तीय ज़िम्मेदार वाली यूनिट), आदर्श हिस्से से बाँटे गए।",
  "Gerar cobrança": "भुगतान बनाएँ", "Gerar": "बनाएँ", "cobranças": "भुगतान",
  "Cobrança de": "भुगतान:", "vencida": "(बकाया)", "Nova cobrança de": "नया भुगतान:",
  "vence em": "देय तिथि", "venceu em": "देय तिथि बीत गई:",
  "Multas da unidade": "यूनिट के जुर्माने",
  "Você pode apresentar defesa até": "आप इस तारीख़ तक आपत्ति दर्ज कर सकते हैं:",
  "Procure a administração do condomínio.": "सोसाइटी प्रशासन से संपर्क करें।",
  "Movimentação de hoje": "आज की गतिविधि", "Nenhum chamado aqui": "यहाँ कोई अनुरोध नहीं", "sem custo lançado": "कोई लागत दर्ज नहीं",
  "Nome fantasia *": "व्यावसायिक नाम *", "Razão social": "कानूनी नाम", "CNPJ *": "कंपनी कर संख्या *", "Seu CPF (diretor) *": "आपकी पहचान संख्या (निदेशक) *",
  "Porte": "आकार", "Endereço completo *": "पूरा पता *", "Nome fantasia": "व्यावसायिक नाम", "CNPJ": "कंपनी कर संख्या",
  "Inscrição municipal": "नगरपालिका पंजीकरण", "Torres / blocos": "टावर / ब्लॉक", "Unidades / vagas": "यूनिट / पार्किंग",
  "Endereço completo": "पूरा पता", "Administradora responsável": "ज़िम्मेदार प्रबंधन कंपनी", "Síndico atual": "वर्तमान प्रबंधक",
  "Diretor administrativo": "प्रशासनिक निदेशक", "Início da gestão": "कार्यकाल की शुरुआत", "Status do contrato SaaS": "SaaS अनुबंध की स्थिति",
  "Horário de silêncio": "शांति के घंटे", "Mudanças": "शिफ्टिंग", "Obras": "निर्माण कार्य", "Visitantes": "आगंतुक", "Animais": "पालतू जानवर",
  "Áreas comuns": "साझा क्षेत्र", "Logo (upload)": "लोगो (अपलोड)", "Cor primária do portal": "पोर्टल का मुख्य रंग",
  "Responsável financeiro": "वित्तीय ज़िम्मेदार", "Fração ideal (%)": "आदर्श हिस्सा (%)", "Área privativa (m²)": "निजी क्षेत्रफल (m²)",
  "Vagas vinculadas": "जुड़ी पार्किंग", "Número": "संख्या", "Bloco / torre": "ब्लॉक / टावर", "Andar": "मंज़िल",
  "Número (ou início do intervalo)": "संख्या (या सीमा की शुरुआत)", "Até o número (opcional)": "इस संख्या तक (वैकल्पिक)",
  "Ex.: 402, 1 ou 1D": "उदा.: 402, 1 या 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "उदा.: 100 या 4D — खाली रहने पर केवल एक बनेगी",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "\"इस संख्या तक\" भरकर एक साथ कई यूनिट बनाएँ: 1 से 100 बनाएगा 1, 2… 100; 1D से 4D बनाएगा 1D, 2D, 3D और 4D। ब्लॉक में पहले से मौजूद संख्याएँ छोड़ दी जाती हैं। प्रकार, मंज़िल, स्थिति और हिस्सा सब पर लागू होंगे।",
  "CPF ou CNPJ": "पहचान संख्या", "Papel no condomínio": "सोसाइटी में भूमिका", "Unidade vinculada": "जुड़ी यूनिट",
  "Data de entrada": "प्रवेश तिथि", "Documento (upload)": "दस्तावेज़ (अपलोड)",
  "Fundo de reserva": "आरक्षित निधि", "Fundo de obras": "निर्माण निधि", "Valor (R$)": "राशि (R$)",
  "Subcategoria / centro de custo": "उपश्रेणी / लागत केंद्र", "Forma de pagamento": "भुगतान का तरीका", "Rateio": "बँटवारा",
  "Nota fiscal (anexo)": "चालान (संलग्नक)", "Aguardando pagamento": "भुगतान की प्रतीक्षा",
  "Valor total a ratear (R$)": "बाँटने की कुल राशि (R$)", "Base de cálculo": "गणना का आधार", "Canais de envio": "भेजने के माध्यम",
  "Aplicadas em 2026": "2026 में लागू", "Em prazo de defesa": "आपत्ति अवधि में", "Arrecadado em multas": "जुर्मानों से वसूली",
  "Categoria da infração": "उल्लंघन की श्रेणी", "Unidade responsável": "ज़िम्मेदार यूनिट", "Data e hora": "तारीख़ और समय",
  "Tipo de penalidade": "दंड का प्रकार", "Valor (se multa)": "राशि (यदि जुर्माना)", "Prazo para defesa": "आपत्ति की समय-सीमा",
  "Base normativa": "नियामक आधार", "Descrição detalhada": "विस्तृत विवरण",
  "Provas (foto, vídeo, áudio ou documento)": "सबूत (फ़ोटो, वीडियो, ऑडियो या दस्तावेज़)",
  "Destinatários": "प्राप्तकर्ता", "Título": "शीर्षक", "Mensagem": "संदेश", "Canais": "माध्यम",
  "Unidade (se aplicável)": "यूनिट (यदि लागू हो)", "Conteúdo": "सामग्री", "Prioridade": "प्राथमिकता", "Prazo": "समय-सीमा",
  "Custo estimado": "अनुमानित लागत", "Fotos / vídeos": "फ़ोटो / वीडियो", "Descrição do problema": "समस्या का विवरण",
  "Acessos registrados": "दर्ज प्रवेश", "Visitantes no condomínio": "परिसर में आगंतुक",
  "Entregas registradas": "दर्ज डिलीवरी", "Vagas de visitante livres": "खाली अतिथि पार्किंग",
  "Nome / empresa": "नाम / कंपनी", "Unidade de destino": "लक्षित यूनिट", "Janela de horário": "समय अवधि",
  "Veículo (opcional)": "वाहन (वैकल्पिक)", "Condomínios ativos": "सक्रिय सोसाइटियाँ",
  "Receita recorrente (MRR)": "आवर्ती आय (MRR)", "Em período de teste": "परीक्षण अवधि में",
  "Nova unidade": "नई यूनिट", "Nova pessoa": "नया व्यक्ति", "Novo lançamento": "नई प्रविष्टि",
  "Gerar cobranças da competência": "अवधि के भुगतान बनाएँ", "Registrar infração": "उल्लंघन दर्ज करें",
  "Novo documento timbrado": "नया लेटरहेड दस्तावेज़", "Abrir chamado de manutenção": "रखरखाव अनुरोध खोलें",
  "Pré-autorizar entrada": "प्रवेश पूर्व-स्वीकृत करें", "Novo acesso": "नया खाता", "Contratar novo condomínio": "नई सोसाइटी जोड़ें",
  "Abrir chamado": "अनुरोध खोलें",
  "Cancelar": "रद्द करें", "Fechar": "बंद करें", "Exportar": "निर्यात", "Lançamento": "प्रविष्टि", "Pessoa": "व्यक्ति",
  "Cadastrar unidade": "यूनिट पंजीकृत करें", "Criar unidade": "यूनिट बनाएँ", "Cadastrar": "पंजीकृत करें",
  "Salvar alterações": "बदलाव सहेजें", "Gerar cobranças": "भुगतान बनाएँ", "Gerar cobranças do mês": "इस महीने के भुगतान बनाएँ",
  "Reenviar": "फिर भेजें", "Baixar": "डाउनलोड", "Enviar por WhatsApp": "WhatsApp से भेजें", "Imprimir PDF": "PDF प्रिंट करें",
  "Enviar ao responsável": "ज़िम्मेदार को भेजें", "Cancelar multa": "जुर्माना रद्द करें", "Aprovar (síndico)": "स्वीकृत करें (प्रबंधक)",
  "Enviar para aprovação": "स्वीकृति के लिए भेजें", "Ver": "देखें", "Publicar e enviar": "प्रकाशित करें और भेजें",
  "Criar documento timbrado": "लेटरहेड दस्तावेज़ बनाएँ", "Gerar PDF": "PDF बनाएँ",
  "Gerar QR de acesso": "प्रवेश QR बनाएँ", "Registrar ocorrência": "घटना दर्ज करें",
  "Autorizar e gerar QR": "स्वीकृत कर QR बनाएँ", "Adicionar acesso": "खाता जोड़ें", "Remover": "हटाएँ",
  "Criar acesso": "खाता बनाएँ", "Novo cliente": "नया ग्राहक", "Bloquear acesso": "पहुँच रोकें", "Abrir painel": "पैनल खोलें",
  "Iniciar implantação": "सेटअप शुरू करें", "Pagar": "भुगतान करें", "Copiar código": "कोड कॉपी करें", "Enviar chamado": "अनुरोध भेजें",
  "Tentar novamente": "फिर कोशिश करें", "Voltar e trocar perfil": "वापस जाकर भूमिका बदलें", "Sair": "लॉगआउट",
  "Lançar e enviar para aprovação": "दर्ज कर स्वीकृति के लिए भेजें", "Criar condomínio e começar": "सोसाइटी बनाएँ और शुरू करें",
  "Salvando…": "सहेजा जा रहा है…", "Criando…": "बनाया जा रहा है…", "Gerando…": "तैयार हो रहा है…", "Publicando…": "प्रकाशित हो रहा है…",
  "Abrindo…": "खुल रहा है…", "Autorizando…": "स्वीकृत हो रहा है…", "Enviando…": "भेजा जा रहा है…",
  "Boletos e QR": "बिल और QR", "Extrato": "विवरण",
  "Início": "होम", "Pagamentos": "भुगतान", "Avisos": "सूचनाएँ",
  "Buscar por número, bloco ou responsável…": "संख्या, ब्लॉक या ज़िम्मेदार से खोजें…",
  "Buscar por nome…": "नाम से खोजें…", "Buscar lançamento…": "प्रविष्टि खोजें…",
  "Buscar por unidade ou responsável…": "यूनिट या ज़िम्मेदार से खोजें…",
  "Nenhuma unidade encontrada": "कोई यूनिट नहीं मिली",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "खोज या फ़िल्टर बदलें, या इस सोसाइटी की पहली यूनिट पंजीकृत करें।",
  "Nenhuma pessoa encontrada": "कोई व्यक्ति नहीं मिला",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "भ्रम से बचने के लिए मालिकों, किरायेदारों, कर्मचारियों और सेवा प्रदाताओं को अलग भूमिकाओं में पंजीकृत करें।",
  "Nenhum lançamento neste período": "इस अवधि में कोई प्रविष्टि नहीं",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "नकदी पर नज़र रखने के लिए अवधि की पहली आय या व्यय दर्ज करें।",
  "Nenhuma cobrança nesta competência": "इस अवधि में कोई भुगतान नहीं",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "महीने के भुगतान बनाएँ: सिस्टम हर यूनिट के लिए अद्वितीय Verum Pay QR कोड बनाकर पोर्टल, ईमेल या WhatsApp से भेजता है।",
  "Nenhum documento nesta categoria": "इस श्रेणी में कोई दस्तावेज़ नहीं",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "जुर्मानों, सूचनाओं, कार्यवृत्तों और रसीदों के लेटरहेड दस्तावेज़ यहाँ स्वतः संग्रहीत होते हैं और वर्षों तक सुरक्षित रहते हैं।",
  "Nenhum acesso criado ainda": "अभी कोई खाता नहीं बना",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "पहला ईमेल और पासवर्ड बनाएँ ताकि प्रबंधक, कोषाध्यक्ष, प्रबंधन कंपनी और निवासी लॉगिन कर सकें।",
  "Não foi possível carregar os dados": "डेटा लोड नहीं हो सका",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "कनेक्शन जाँचकर फिर कोशिश करें। समस्या बनी रहे तो सहायता से संपर्क करें।",
};
