/* Bahasa Indonesia */
export default {
  "Condomínio": "Kompleks", "Unidades": "Unit", "Pessoas": "Orang", "Financeiro": "Keuangan",
  "Cobranças QR": "Tagihan QR", "Multas": "Denda", "Comunicados": "Pengumuman", "Documentos": "Dokumen",
  "Manutenção": "Pemeliharaan", "Portaria": "Resepsionis", "Gerenciar Acessos": "Kelola Akses", 
  "Visão geral do condomínio em tempo real": "Ikhtisar kompleks secara real-time",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Data induk: informasi hukum, pengelolaan, dan aturan internal",

  /* subtítulos dinâmicos do cabeçalho */
  "unidade": "unit", "unidades": "unit", "bloco/torre": "blok/menara", "blocos/torres": "blok/menara",
  "pessoa cadastrada": "orang terdaftar", "pessoas cadastradas": "orang terdaftar",
  "aprovações do síndico ativas": "persetujuan pengelola aktif",
  "cobrança em aberto": "tagihan belum dibayar", "cobranças em aberto": "tagihan belum dibayar", "vencidas": "jatuh tempo",
  "multa/advertência registrada": "denda/peringatan tercatat", "multas/advertências registradas": "denda/peringatan tercatat",
  "comunicado publicado": "pengumuman terbit", "comunicados publicados": "pengumuman terbit",
  "documento arquivado": "dokumen diarsipkan", "documentos arquivados": "dokumen diarsipkan",
  "chamado em aberto": "tiket terbuka", "chamados em aberto": "tiket terbuka",
  /* teste gratuito de 30 dias */
  "Ative seu teste gratuito de 30 dias — cadastre o cartão; nada será cobrado agora.": "Aktifkan uji coba gratis 30 hari — daftarkan kartu; tidak ada tagihan sekarang.",
  "O período de avaliação terminou. Ative a assinatura para continuar.": "Masa uji coba telah berakhir. Aktifkan langganan untuk melanjutkan.",
  "Iniciar teste gratuito de 30 dias": "Mulai uji coba gratis 30 hari",

  "A troca de plano durante o teste gratuito é cobrada imediatamente — aguarde o fim do teste para trocar.": "Ganti paket selama uji coba gratis langsung ditagih — tunggu uji coba berakhir untuk mengganti.",
  "Teste gratuito — termina em": "Uji coba gratis — berakhir dalam", "dia(s)": "hari",
  "Depois, a cobrança é feita automaticamente no cartão cadastrado.": "Setelah itu, tagihan otomatis ke kartu terdaftar.",

  "Tenho um código de ativação": "Saya punya kode aktivasi", "Código de ativação": "Kode aktivasi",
  "Ativar": "Aktifkan", "Ativando…": "Mengaktifkan…",

  "Código aplicado. Se o acesso não liberar em instantes, use \"Já paguei — verificar\".": "Kode diterapkan. Jika akses tidak terbuka sebentar lagi, gunakan \"Já paguei — verificar\".",

  "Cancelar assinatura": "Batalkan langganan",
  "Cancelar a assinatura? O acesso continua até o fim do período já pago e nenhuma cobrança futura será feita.": "Batalkan langganan? Akses berlanjut sampai akhir periode yang sudah dibayar dan tidak ada tagihan berikutnya.",
  "Cancelamento agendado — o acesso continua até": "Pembatalan dijadwalkan — akses berlanjut sampai",
  "Assinatura cancelada.": "Langganan dibatalkan.",
  "Assinatura cancelada em": "Langganan dibatalkan pada", "o acesso será desativado em": "akses akan dinonaktifkan pada",
  "Nenhuma cobrança futura será feita.": "Tidak ada tagihan berikutnya.",
  "Acima da franquia do plano": "Melebihi kuota paket",
  "o excedente é cobrado por unidade adicional na fatura da licença.": "kelebihan ditagih per unit tambahan pada tagihan lisensi.",

  "Controle de acessos, entregas e ocorrências": "Kontrol akses, paket, dan insiden",

  "Notificações": "Notifikasi", "Alternar tema": "Ganti tema", "Idioma": "Bahasa", "Perfil de acesso": "Peran akses",
  "Diretor": "Direktur", "Síndico": "Pengelola", "Tesouraria": "Bendahara", "Administradora": "Perusahaan pengelola", "Morador": "Penghuni",
  "Visão estratégica, aprovações e auditoria": "Pandangan strategis, persetujuan, dan audit",
  "Operação, multas, comunicados e manutenção": "Operasional, denda, pengumuman, dan pemeliharaan",
  "Financeiro, cobranças e conciliação": "Keuangan, tagihan, dan rekonsiliasi",

  "Boletos, comprovantes, comunicados e chamados": "Tagihan, bukti bayar, pengumuman, dan permintaan",
  "Gestão condominial premium · powered by Serve Now Global": "Pengelolaan kompleks premium · powered by Serve Now Global",
  "Criar acesso do diretor": "Buat akun direktur",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Ini akses pertama. Akun yang dibuat di sini akan dipakai untuk masuk sebagai",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Acessos.": ", yang dapat mendaftarkan email dan kata sandi peran lain di Kelola Akses.",
  "Nome completo": "Nama lengkap", "E-mail": "Email", "Senha": "Kata sandi", "Confirmar senha": "Konfirmasi kata sandi",
  "Criar conta e continuar": "Buat akun dan lanjutkan",
  "Já tem prédio cadastrado? Fazer login": "Gedung sudah terdaftar? Masuk",
  "Entrar como": "Masuk sebagai", "Trocar perfil": "Ganti peran", "Voltar ao cadastro": "Kembali ke pendaftaran",
  "Entrar": "Masuk", "Verificando conta...": "Memverifikasi akun...",
  "E-mail ou senha incorretos.": "Email atau kata sandi salah.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Acessos.": "Email atau kata sandi salah. Minta direktur memeriksa akun Anda di Kelola Akses.",

  "Não foi possível verificar sua conta agora.": "Akun Anda tidak dapat diverifikasi saat ini.",

  "As senhas não conferem.": "Kata sandi tidak cocok.",
  "Nenhum acesso de": "Belum ada akun untuk",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Acessos.": ". Minta direktur mendaftarkannya di Kelola Akses.",
  "Tema claro": "Tema terang", "Tema escuro": "Tema gelap",

  "Seu nome": "Nama Anda", "voce@exemplo.com": "anda@contoh.com", "Repita a senha": "Ulangi kata sandi",
  "Saldo em caixa": "Saldo kas", "Inadimplência": "Tunggakan", "Receitas de": "Pemasukan", "Despesas de": "Pengeluaran",
  "Nova cobrança": "Tagihan baru", "Novo gasto": "Pengeluaran baru", "Nova multa": "Denda baru", "Novo comunicado": "Pengumuman baru", "Novo chamado": "Permintaan baru",
  "Evolução financeira do mês — dia a dia": "Perkembangan keuangan bulan ini — per hari",
  "Distribuição de receitas": "Distribusi pemasukan", "Despesas por categoria": "Pengeluaran per kategori",
  "Inadimplência ao longo do tempo": "Tunggakan dari waktu ke waktu", 
  "Aprovações pendentes": "Menunggu persetujuan", "Alertas do dia": "Peringatan hari ini", "Ver todas →": "Lihat semua →",
  "Sem despesas em": "Tidak ada pengeluaran di", "Sem receitas em": "Tidak ada pemasukan di", "Dia": "Hari",
  "Receita": "Pemasukan", "Despesa": "Pengeluaran", "Multa": "Denda",
  "aguarda decisão do síndico": "menunggu keputusan pengelola",
  "cobrança(s) vencida(s) somando": "tagihan jatuh tempo dengan total",
  "sem responsável designado": "tanpa penanggung jawab",
  "Pago": "Lunas", "Entrada": "Diterima", "Parcial": "Sebagian", "Em aberto": "Terbuka", "Aguardando": "Menunggu", "Vencida": "Jatuh tempo", "Emitida": "Diterbitkan",
  "Ocupada": "Dihuni", "Alugada": "Disewakan", "Vaga": "Kosong", "Ativo": "Aktif", "Em teste": "Uji coba", "Inadimplente": "Menunggak",
  "Prazo de defesa": "Masa pembelaan", "Multa aplicada": "Denda diberlakukan", "Advertência": "Peringatan",
  "Em andamento": "Berjalan", "Concluído": "Selesai", "No condomínio": "Di kompleks", "Saiu": "Keluar", "Retirado": "Diambil",
  "Ocorrência": "Insiden", "Cancelada": "Dibatalkan", "Cancelado": "Dibatalkan", "Vendida": "Terjual", "Reservada": "Dipesan", "Inativa": "Nonaktif",
  "Alta": "Tinggi", "Média": "Sedang", "Baixa": "Rendah",
  "Todos os status": "Semua status", "Todos os papéis": "Semua peran", "Todos": "Semua", "Pagas": "Lunas", "Emitidas": "Diterbitkan", "Vencidas": "Jatuh tempo",
  "Abertos": "Terbuka", "Concluídos": "Selesai",
  "Nome": "Nama", "Papel": "Peran", "Unidade": "Unit", "Telefone": "Telepon", "Status": "Status",
  "Data": "Tanggal", "Tipo": "Jenis", "Categoria": "Kategori", "Descrição": "Deskripsi", "Valor": "Jumlah",
  "Responsável": "Penanggung jawab", "Competência": "Periode", "Vencimento": "Jatuh tempo", "Plano": "Paket", "Mensalidade": "Biaya bulanan", "Mensal": "Bulanan", "Anual": "Tahunan", "Anuidade": "Biaya tahunan", 
  "Planos": "Paket",
  "Últimos comunicados": "Pengumuman terbaru", "Minha situação": "Status saya", "Cobranças da unidade": "Tagihan unit",
  "Unidade / apartamento": "Unit / apartemen", "Cadastre unidades primeiro na tela Unidades.": "Daftarkan unit terlebih dahulu di layar Unit.",
  "Nenhuma cobrança para esta unidade ainda.": "Belum ada tagihan untuk unit ini.",
  "Toque para ler": "Ketuk untuk membaca",
  "Destino": "Tujuan", "Todas as unidades (rateio pela fração)": "Semua unit (dibagi menurut porsi)",

  "Será gerada 1 cobrança para": "Akan dibuat 1 tagihan untuk",
  "O morador verá o aviso no portal dele.": "Penghuni akan melihat pemberitahuan di portalnya.",
  "Serão geradas": "Sistem akan membuat", 
  "Gerar cobrança": "Buat tagihan", "Gerar": "Buat", "cobranças": "tagihan",
  "Cobrança de": "Tagihan", "vencida": "jatuh tempo", "Nova cobrança de": "Tagihan baru",
  "vence em": "jatuh tempo pada", "venceu em": "jatuh tempo pada",

  "Você pode apresentar defesa até": "Anda dapat mengajukan pembelaan hingga",
  "Procure a administração do condomínio.": "Hubungi pengelola kompleks.",
  "Movimentação de hoje": "Aktivitas hari ini", "Nenhum chamado aqui": "Tidak ada permintaan di sini", "sem custo lançado": "belum ada biaya dicatat",
  "Nome fantasia *": "Nama usaha *", "Razão social": "Nama resmi", "CNPJ *": "NPWP perusahaan *", "Seu CPF (diretor) *": "No. identitas Anda (direktur) *",
  "Porte": "Ukuran", "Endereço completo *": "Alamat lengkap *", "Nome fantasia": "Nama usaha", "CNPJ": "NPWP perusahaan",
  "Inscrição municipal": "Registrasi kota", "Torres / blocos": "Menara / blok", "Unidades / vagas": "Unit / parkir",
  "Endereço completo": "Alamat lengkap", "Administradora responsável": "Perusahaan pengelola", "Síndico atual": "Pengelola saat ini",
  "Diretor administrativo": "Direktur administrasi", "Início da gestão": "Awal masa jabatan", 
  "Horário de silêncio": "Jam tenang", "Mudanças": "Pindahan", "Obras": "Renovasi", "Visitantes": "Tamu", "Animais": "Hewan peliharaan",
  "Áreas comuns": "Area bersama", "Logo (upload)": "Logo (unggah)", "Cor primária do portal": "Warna utama portal",
  "Responsável financeiro": "Penanggung jawab keuangan", "Área privativa (m²)": "Luas pribadi (m²)",
  "Vagas vinculadas": "Parkir terkait", "Número": "Nomor", "Bloco / torre": "Blok / menara", "Andar": "Lantai",
  "Número (ou início do intervalo)": "Nomor (atau awal rentang)", "Até o número (opcional)": "Sampai nomor (opsional)",
  "Ex.: 402, 1 ou 1D": "Mis.: 402, 1 atau 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Mis.: 100 atau 4D — kosong hanya membuat satu",

  "Papel no condomínio": "Peran di kompleks", "Unidade vinculada": "Unit terkait",
  "Data de entrada": "Tanggal masuk", "Documento (upload)": "Dokumen (unggah)",
  "Fundo de reserva": "Dana cadangan", "Fundo de obras": "Dana renovasi", "Valor ($)": "Jumlah ($)",
  "Subcategoria / centro de custo": "Subkategori / pusat biaya", "Forma de pagamento": "Metode pembayaran", "Rateio": "Pembagian",
  "Nota fiscal (anexo)": "Faktur (lampiran)", "Aguardando pagamento": "Menunggu pembayaran",
  "Base de cálculo": "Dasar perhitungan", "Canais de envio": "Saluran pengiriman",
  "Aplicadas em 2026": "Diberlakukan pada 2026", "Em prazo de defesa": "Dalam masa pembelaan", "Arrecadado em multas": "Terkumpul dari denda",
  "Categoria da infração": "Kategori pelanggaran", "Unidade responsável": "Unit terkait", "Data e hora": "Tanggal dan waktu",
  "Tipo de penalidade": "Jenis sanksi", "Valor (se multa)": "Jumlah (jika denda)", "Prazo para defesa": "Batas pembelaan",
  "Base normativa": "Dasar aturan", "Descrição detalhada": "Deskripsi rinci",
  "Provas (foto, vídeo, áudio ou documento)": "Bukti (foto, video, audio, atau dokumen)",
  "Destinatários": "Penerima", "Título": "Judul", "Mensagem": "Pesan", "Canais": "Saluran",
  "Unidade (se aplicável)": "Unit (jika ada)", "Prioridade": "Prioritas", "Prazo": "Tenggat",
  "Custo estimado": "Perkiraan biaya", "Fotos / vídeos": "Foto / video", "Descrição do problema": "Deskripsi masalah",
  "Acessos registrados": "Akses tercatat", "Visitantes no condomínio": "Tamu di kompleks",
  "Entregas registradas": "Paket tercatat", "Vagas de visitante livres": "Parkir tamu kosong",
  "Nome / empresa": "Nama / perusahaan", "Unidade de destino": "Unit tujuan", "Janela de horário": "Rentang waktu",
  "Veículo (opcional)": "Kendaraan (opsional)", 

  "Nova unidade": "Unit baru", "Nova pessoa": "Orang baru", "Novo lançamento": "Catatan baru",
  "Gerar cobranças da competência": "Buat tagihan periode", "Registrar infração": "Catat pelanggaran",
  "Novo documento timbrado": "Dokumen berkop baru", "Abrir chamado de manutenção": "Buka permintaan pemeliharaan",
  "Pré-autorizar entrada": "Pra-otorisasi masuk", "Novo acesso": "Akun baru", 
  "Abrir chamado": "Buka permintaan",
  "Cancelar": "Batal", "Fechar": "Tutup", "Exportar": "Ekspor", "Lançamento": "Catatan", "Pessoa": "Orang",
  "Cadastrar unidade": "Daftarkan unit", "Criar unidade": "Buat unit", "Cadastrar": "Daftarkan",
  "Salvar alterações": "Simpan perubahan", "Gerar cobranças": "Buat tagihan", "Gerar cobranças do mês": "Buat tagihan bulan ini",
  "Reenviar": "Kirim ulang", "Baixar": "Unduh", "Enviar por WhatsApp": "Kirim via WhatsApp", "Imprimir PDF": "Cetak PDF",
  "Enviar ao responsável": "Kirim ke penanggung jawab", "Cancelar multa": "Batalkan denda", "Aprovar (síndico)": "Setujui (pengelola)",
  "Enviar para aprovação": "Kirim untuk persetujuan", "Ver": "Lihat", "Publicar e enviar": "Terbitkan dan kirim",
  "Criar documento timbrado": "Buat dokumen berkop", "Gerar PDF": "Buat PDF",
  "Gerar QR de acesso": "Buat QR akses", "Registrar ocorrência": "Catat insiden",
  "Autorizar e gerar QR": "Otorisasi dan buat QR", "Adicionar acesso": "Tambah akun", "Remover": "Hapus",
  "Criar acesso": "Buat akun", 
  "Pagar": "Bayar", "Copiar código": "Salin kode", 
  "Tentar novamente": "Coba lagi", "Voltar e trocar perfil": "Kembali dan ganti peran", "Sair": "Keluar",
  "Lançar e enviar para aprovação": "Catat dan kirim untuk persetujuan", 
  "Salvando…": "Menyimpan…", "Criando…": "Membuat…", "Gerando…": "Membuat…", "Publicando…": "Menerbitkan…",
  "Abrindo…": "Membuka…", "Autorizando…": "Mengotorisasi…", "Enviando…": "Mengirim…",
  "Extrato": "Riwayat",
  "Início": "Beranda", "Pagamentos": "Pembayaran", "Avisos": "Pemberitahuan",

  "Buscar por nome…": "Cari berdasarkan nama…", "Buscar lançamento…": "Cari catatan…",
  "Buscar por unidade ou responsável…": "Cari berdasarkan unit atau penanggung jawab…",
  "Nenhuma unidade encontrada": "Tidak ada unit ditemukan",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Ubah pencarian atau filter, atau daftarkan unit pertama kompleks ini.",
  "Nenhuma pessoa encontrada": "Tidak ada orang ditemukan",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Daftarkan pemilik, penyewa, karyawan, dan penyedia jasa dengan peran terpisah untuk menghindari kebingungan operasional.",
  "Nenhum lançamento neste período": "Tidak ada catatan pada periode ini",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Catat pemasukan atau pengeluaran pertama periode ini untuk mulai memantau kas.",
  "Nenhuma cobrança nesta competência": "Tidak ada tagihan pada periode ini",

  "Nenhum documento nesta categoria": "Tidak ada dokumen dalam kategori ini",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Dokumen berkop untuk denda, pengumuman, notulen, dan kuitansi diarsipkan otomatis di sini dan disimpan bertahun-tahun.",
  "Nenhum acesso criado ainda": "Belum ada akun dibuat",

  "Não foi possível carregar os dados": "Data tidak dapat dimuat",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Periksa koneksi dan coba lagi. Jika masalah berlanjut, hubungi dukungan.",
};
