/* Italiano */
export default {
  "Condomínio": "Condominio", "Unidades": "Unità", "Pessoas": "Persone", "Financeiro": "Finanze",
  "Cobranças QR": "Pagamenti QR", "Multas": "Multe", "Comunicados": "Comunicazioni", "Documentos": "Documenti",
  "Manutenção": "Manutenzione", "Portaria": "Portineria", "Gerenciar Emails": "Gestisci e-mail", "Painel SaaS": "Pannello SaaS",
  "Visão geral do condomínio em tempo real": "Panoramica del condominio in tempo reale",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Anagrafica principale: dati legali, gestione e regolamento interno",
  "96 unidades · 2 torres + térreo comercial": "96 unità · 2 torri + piano terra commerciale",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "Ruoli separati: proprietario, inquilino, dipendente e fornitore",
  "Competência 06/2026 · aprovações do síndico ativas": "Periodo 06/2026 · approvazioni dell'amministratore attive",
  "QR Code Verum Pay com baixa automática": "QR Code Verum Pay con registrazione automatica",
  "Fluxo com prova, defesa e aprovação": "Flusso con prova, difesa e approvazione",
  "Envio por portal, e-mail e WhatsApp": "Invio tramite portale, e-mail e WhatsApp",
  "Arquivo timbrado com retenção histórica": "Archivio intestato con conservazione storica",
  "Ordens de serviço por categoria e prioridade": "Ordini di lavoro per categoria e priorità",
  "Controle de acessos, entregas e ocorrências": "Controllo di accessi, consegne e incidenti",
  "Clientes, planos, licenças e implantação": "Clienti, piani, licenze e avviamento",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "E-mail e password di accesso per amministratore, tesoreria, società di gestione e residente",
  "Notificações": "Notifiche", "Alternar tema": "Cambia tema", "Idioma": "Lingua", "Perfil de acesso": "Profilo di accesso",
  "Diretor": "Direttore", "Síndico": "Amministratore", "Tesouraria": "Tesoreria", "Administradora": "Società di gestione", "Morador": "Residente",
  "Visão estratégica, aprovações e auditoria": "Visione strategica, approvazioni e audit",
  "Operação, multas, comunicados e manutenção": "Operatività, multe, comunicazioni e manutenzione",
  "Financeiro, cobranças e conciliação": "Finanze, pagamenti e riconciliazione",
  "Gestão SaaS: clientes, planos e licenças": "Gestione SaaS: clienti, piani e licenze",
  "Boletos, comprovantes, comunicados e chamados": "Bollette, ricevute, comunicazioni e richieste",
  "Gestão condominial premium · powered by Verum Pay": "Gestione condominiale premium · powered by Verum Pay",
  "Criar acesso do diretor": "Crea l'accesso del direttore",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Questo è il primo accesso. L'account creato qui servirà per accedere come",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": ", che potrà registrare le e-mail e le password degli altri profili in Gestisci e-mail.",
  "Nome completo": "Nome completo", "E-mail": "E-mail", "Senha": "Password", "Confirmar senha": "Conferma password",
  "Criar conta e continuar": "Crea account e continua",
  "Já tem prédio cadastrado? Fazer login": "Edificio già registrato? Accedi",
  "Entrar como": "Accedi come", "Trocar perfil": "Cambia profilo", "Voltar ao cadastro": "Torna alla registrazione",
  "Entrar": "Accedi", "Verificando conta...": "Verifica dell'account...",
  "E-mail ou senha incorretos.": "E-mail o password errati.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "E-mail o password errati. Chiedi al direttore di verificare il tuo accesso in Gestisci e-mail.",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "Nessun accesso direttore trovato su questo dispositivo. Torna indietro e crea l'accesso del direttore.",
  "Não foi possível verificar sua conta agora.": "Impossibile verificare l'account in questo momento.",
  "A senha deve ter pelo menos 4 caracteres.": "La password deve avere almeno 4 caratteri.",
  "As senhas não conferem.": "Le password non coincidono.",
  "Nenhum acesso de": "Nessun accesso per",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "è stato ancora creato. Chiedi al direttore di registrarlo in Gestisci e-mail.",
  "Tema claro": "Tema chiaro", "Tema escuro": "Tema scuro",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "Nessun accesso con questo nome. Chiedi al direttore di registrarlo in Gestisci e-mail.",
  "Senha incorreta para este nome.": "Password errata per questo nome.",
  "Seu nome": "Il tuo nome", "voce@exemplo.com": "tu@esempio.com", "Mínimo 4 caracteres": "Minimo 4 caratteri", "Repita a senha": "Ripeti la password",
  "Saldo em caixa": "Saldo di cassa", "Inadimplência": "Morosità", "Receitas de": "Entrate di", "Despesas de": "Uscite di",
  "Nova cobrança": "Nuovo pagamento", "Novo gasto": "Nuova spesa", "Nova multa": "Nuova multa", "Novo comunicado": "Nuova comunicazione", "Novo chamado": "Nuova richiesta",
  "Evolução financeira do mês — dia a dia": "Andamento finanziario del mese — giorno per giorno",
  "Distribuição de receitas": "Distribuzione delle entrate", "Despesas por categoria": "Uscite per categoria",
  "Inadimplência ao longo do tempo": "Morosità nel tempo", "Atividade recente": "Attività recente",
  "Aprovações pendentes": "Approvazioni in sospeso", "Alertas do dia": "Avvisi del giorno", "Ver todas →": "Vedi tutte →",
  "Sem despesas em": "Nessuna uscita in", "Sem receitas em": "Nessuna entrata in", "Dia": "Giorno",
  "Receita": "Entrata", "Despesa": "Uscita", "Multa": "Multa",
  "aguarda decisão do síndico": "in attesa della decisione dell'amministratore",
  "cobrança(s) vencida(s) somando": "pagamento/i scaduto/i per un totale di",
  "sem responsável designado": "senza responsabile assegnato",
  "Pago": "Pagato", "Parcial": "Parziale", "Em aberto": "Aperto", "Aguardando": "In attesa", "Vencida": "Scaduta", "Emitida": "Emessa",
  "Ocupada": "Occupata", "Alugada": "Affittata", "Vaga": "Libera", "Ativo": "Attivo", "Em teste": "In prova", "Inadimplente": "Moroso",
  "Prazo de defesa": "Termine per la difesa", "Multa aplicada": "Multa applicata", "Advertência": "Richiamo",
  "Em andamento": "In corso", "Concluído": "Completato", "No condomínio": "In sede", "Saiu": "Uscito", "Retirado": "Ritirato",
  "Ocorrência": "Incidente", "Cancelada": "Annullata", "Cancelado": "Annullato", "Vendida": "Venduta", "Reservada": "Riservata", "Inativa": "Inattiva",
  "Alta": "Alta", "Média": "Media", "Baixa": "Bassa",
  "Todos os status": "Tutti gli stati", "Todos os papéis": "Tutti i ruoli", "Todos": "Tutti", "Pagas": "Pagate", "Emitidas": "Emesse", "Vencidas": "Scadute",
  "Abertos": "Aperte", "Concluídos": "Completate",
  "Nome": "Nome", "Papel": "Ruolo", "Unidade": "Unità", "CPF/CNPJ": "Codice fiscale", "Telefone": "Telefono", "Status": "Stato",
  "Data": "Data", "Tipo": "Tipo", "Categoria": "Categoria", "Descrição": "Descrizione", "Valor": "Importo",
  "Responsável": "Responsabile", "Competência": "Periodo", "Vencimento": "Scadenza", "Plano": "Piano", "Mensalidade": "Canone mensile", "Renovação": "Rinnovo",
  "Evolução da receita recorrente": "Andamento dei ricavi ricorrenti", "Planos": "Piani",
  "Últimos comunicados": "Ultime comunicazioni", "Minha situação": "La mia situazione", "Cobranças da unidade": "Pagamenti dell'unità",
  "Unidade / apartamento": "Unità / appartamento", "Cadastre unidades primeiro na tela Unidades.": "Registra prima le unità nella schermata Unità.",
  "Nenhuma cobrança para esta unidade ainda.": "Ancora nessun pagamento per questa unità.",
  "Toque para ler": "Tocca per leggere",
  "Destino": "Destinatario", "Todas as unidades (rateio pela fração)": "Tutte le unità (ripartito per millesimi)",
  "Valor da cobrança (R$)": "Importo del pagamento (R$)",
  "Será gerada 1 cobrança para": "Verrà generato 1 pagamento per",
  "O morador verá o aviso no portal dele.": "Il residente vedrà l'avviso nel suo portale.",
  "Serão geradas": "Il sistema genererà", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "pagamenti (unità con responsabile finanziario), ripartiti per quota ideale.",
  "Gerar cobrança": "Genera pagamento", "Gerar": "Genera", "cobranças": "pagamenti",
  "Cobrança de": "Pagamento di", "vencida": "scaduto", "Nova cobrança de": "Nuovo pagamento di",
  "vence em": "scade il", "venceu em": "scaduto il",
  "Multas da unidade": "Multe dell'unità",
  "Você pode apresentar defesa até": "Puoi presentare una difesa entro il",
  "Procure a administração do condomínio.": "Contatta l'amministrazione del condominio.",
  "Movimentação de hoje": "Movimenti di oggi", "Nenhum chamado aqui": "Nessuna richiesta qui", "sem custo lançado": "nessun costo registrato",
  "Nome fantasia *": "Nome commerciale *", "Razão social": "Ragione sociale", "CNPJ *": "P. IVA *", "Seu CPF (diretor) *": "Il tuo codice fiscale (direttore) *",
  "Porte": "Dimensione", "Endereço completo *": "Indirizzo completo *", "Nome fantasia": "Nome commerciale", "CNPJ": "P. IVA",
  "Inscrição municipal": "Registrazione comunale", "Torres / blocos": "Torri / blocchi", "Unidades / vagas": "Unità / posti auto",
  "Endereço completo": "Indirizzo completo", "Administradora responsável": "Società di gestione responsabile", "Síndico atual": "Amministratore attuale",
  "Diretor administrativo": "Direttore amministrativo", "Início da gestão": "Inizio mandato", "Status do contrato SaaS": "Stato del contratto SaaS",
  "Horário de silêncio": "Orario di silenzio", "Mudanças": "Traslochi", "Obras": "Lavori", "Visitantes": "Visitatori", "Animais": "Animali",
  "Áreas comuns": "Aree comuni", "Logo (upload)": "Logo (caricamento)", "Cor primária do portal": "Colore principale del portale",
  "Responsável financeiro": "Responsabile finanziario", "Fração ideal (%)": "Quota millesimale (%)", "Área privativa (m²)": "Superficie privata (m²)",
  "Vagas vinculadas": "Posti auto collegati", "Número": "Numero", "Bloco / torre": "Blocco / torre", "Andar": "Piano",
  "Número (ou início do intervalo)": "Numero (o inizio dell'intervallo)", "Até o número (opcional)": "Fino al numero (facoltativo)",
  "Ex.: 402, 1 ou 1D": "Es.: 402, 1 o 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Es.: 100 o 4D — vuoto ne crea solo una",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "Compila \"Fino al numero\" per creare più unità in una volta: da 1 a 100 crea 1, 2… 100; da 1D a 4D crea 1D, 2D, 3D e 4D. I numeri già esistenti nel blocco vengono saltati. Tipo, piano, stato e quota valgono per tutte.",
  "CPF ou CNPJ": "Codice fiscale", "Papel no condomínio": "Ruolo nel condominio", "Unidade vinculada": "Unità collegata",
  "Data de entrada": "Data di ingresso", "Documento (upload)": "Documento (caricamento)",
  "Fundo de reserva": "Fondo di riserva", "Fundo de obras": "Fondo lavori", "Valor (R$)": "Importo (R$)",
  "Subcategoria / centro de custo": "Sottocategoria / centro di costo", "Forma de pagamento": "Metodo di pagamento", "Rateio": "Ripartizione",
  "Nota fiscal (anexo)": "Fattura (allegato)", "Aguardando pagamento": "In attesa di pagamento",
  "Valor total a ratear (R$)": "Importo totale da ripartire (R$)", "Base de cálculo": "Base di calcolo", "Canais de envio": "Canali di invio",
  "Aplicadas em 2026": "Applicate nel 2026", "Em prazo de defesa": "Nel termine per la difesa", "Arrecadado em multas": "Riscosso in multe",
  "Categoria da infração": "Categoria dell'infrazione", "Unidade responsável": "Unità responsabile", "Data e hora": "Data e ora",
  "Tipo de penalidade": "Tipo di sanzione", "Valor (se multa)": "Importo (se multa)", "Prazo para defesa": "Termine per la difesa",
  "Base normativa": "Base normativa", "Descrição detalhada": "Descrizione dettagliata",
  "Provas (foto, vídeo, áudio ou documento)": "Prove (foto, video, audio o documento)",
  "Destinatários": "Destinatari", "Título": "Titolo", "Mensagem": "Messaggio", "Canais": "Canali",
  "Unidade (se aplicável)": "Unità (se applicabile)", "Conteúdo": "Contenuto", "Prioridade": "Priorità", "Prazo": "Scadenza",
  "Custo estimado": "Costo stimato", "Fotos / vídeos": "Foto / video", "Descrição do problema": "Descrizione del problema",
  "Acessos registrados": "Accessi registrati", "Visitantes no condomínio": "Visitatori in sede",
  "Entregas registradas": "Consegne registrate", "Vagas de visitante livres": "Posti visitatori liberi",
  "Nome / empresa": "Nome / azienda", "Unidade de destino": "Unità di destinazione", "Janela de horário": "Fascia oraria",
  "Veículo (opcional)": "Veicolo (facoltativo)", "Condomínios ativos": "Condomini attivi",
  "Receita recorrente (MRR)": "Ricavi ricorrenti (MRR)", "Em período de teste": "In periodo di prova",
  "Nova unidade": "Nuova unità", "Nova pessoa": "Nuova persona", "Novo lançamento": "Nuova registrazione",
  "Gerar cobranças da competência": "Genera i pagamenti del periodo", "Registrar infração": "Registra infrazione",
  "Novo documento timbrado": "Nuovo documento intestato", "Abrir chamado de manutenção": "Apri richiesta di manutenzione",
  "Pré-autorizar entrada": "Preautorizza ingresso", "Novo acesso": "Nuovo accesso", "Contratar novo condomínio": "Attiva nuovo condominio",
  "Abrir chamado": "Apri richiesta",
  "Cancelar": "Annulla", "Fechar": "Chiudi", "Exportar": "Esporta", "Lançamento": "Registrazione", "Pessoa": "Persona",
  "Cadastrar unidade": "Registra unità", "Criar unidade": "Crea unità", "Cadastrar": "Registra",
  "Salvar alterações": "Salva modifiche", "Gerar cobranças": "Genera pagamenti", "Gerar cobranças do mês": "Genera i pagamenti del mese",
  "Reenviar": "Reinvia", "Baixar": "Scarica", "Enviar por WhatsApp": "Invia via WhatsApp", "Imprimir PDF": "Stampa PDF",
  "Enviar ao responsável": "Invia al responsabile", "Cancelar multa": "Annulla multa", "Aprovar (síndico)": "Approva (amministratore)",
  "Enviar para aprovação": "Invia per approvazione", "Ver": "Vedi", "Publicar e enviar": "Pubblica e invia",
  "Criar documento timbrado": "Crea documento intestato", "Gerar PDF": "Genera PDF",
  "Gerar QR de acesso": "Genera QR di accesso", "Registrar ocorrência": "Registra incidente",
  "Autorizar e gerar QR": "Autorizza e genera QR", "Adicionar acesso": "Aggiungi accesso", "Remover": "Rimuovi",
  "Criar acesso": "Crea accesso", "Novo cliente": "Nuovo cliente", "Bloquear acesso": "Blocca accesso", "Abrir painel": "Apri pannello",
  "Iniciar implantação": "Avvia attivazione", "Pagar": "Paga", "Copiar código": "Copia codice", "Enviar chamado": "Invia richiesta",
  "Tentar novamente": "Riprova", "Voltar e trocar perfil": "Torna e cambia profilo", "Sair": "Esci",
  "Lançar e enviar para aprovação": "Registra e invia per approvazione", "Criar condomínio e começar": "Crea il condominio e inizia",
  "Salvando…": "Salvataggio…", "Criando…": "Creazione…", "Gerando…": "Generazione…", "Publicando…": "Pubblicazione…",
  "Abrindo…": "Apertura…", "Autorizando…": "Autorizzazione…", "Enviando…": "Invio…",
  "Boletos e QR": "Bollette e QR", "Extrato": "Estratto conto",
  "Início": "Home", "Pagamentos": "Pagamenti", "Avisos": "Avvisi",
  "Buscar por número, bloco ou responsável…": "Cerca per numero, blocco o responsabile…",
  "Buscar por nome…": "Cerca per nome…", "Buscar lançamento…": "Cerca registrazione…",
  "Buscar por unidade ou responsável…": "Cerca per unità o responsabile…",
  "Nenhuma unidade encontrada": "Nessuna unità trovata",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Modifica la ricerca o i filtri, oppure registra la prima unità di questo condominio.",
  "Nenhuma pessoa encontrada": "Nessuna persona trovata",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Registra proprietari, inquilini, dipendenti e fornitori con ruoli separati per evitare confusione operativa.",
  "Nenhum lançamento neste período": "Nessuna registrazione in questo periodo",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Registra la prima entrata o uscita del periodo per iniziare a monitorare la cassa.",
  "Nenhuma cobrança nesta competência": "Nessun pagamento in questo periodo",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "Genera i pagamenti del mese: il sistema crea un QR Code Verum Pay unico per unità e lo invia tramite portale, e-mail o WhatsApp.",
  "Nenhum documento nesta categoria": "Nessun documento in questa categoria",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "I documenti intestati di multe, comunicazioni, verbali e ricevute vengono archiviati automaticamente qui, conservati per anni.",
  "Nenhum acesso criado ainda": "Nessun accesso creato finora",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "Registra la prima e-mail e password perché amministratore, tesoreria, società di gestione e residenti possano accedere.",
  "Não foi possível carregar os dados": "Impossibile caricare i dati",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Verifica la connessione e riprova. Se il problema persiste, contatta l'assistenza.",
};
