/* 日本語 */
export default {
  "Condomínio": "マンション", "Unidades": "住戸", "Pessoas": "住民・関係者", "Financeiro": "会計",
  "Cobranças QR": "QR請求", "Multas": "違約金", "Comunicados": "お知らせ", "Documentos": "書類",
  "Manutenção": "メンテナンス", "Portaria": "受付", "Gerenciar Emails": "メール管理", "Painel SaaS": "SaaSパネル",
  "Visão geral do condomínio em tempo real": "マンションのリアルタイム概況",
  "Cadastro-mãe: dados legais, gestão e regras internas": "基本情報：法的データ、管理、内部規約",
  "96 unidades · 2 torres + térreo comercial": "96住戸 · 2棟 + 商業フロア",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "役割を分離：所有者、入居者、従業員、業者",
  "Competência 06/2026 · aprovações do síndico ativas": "対象月 06/2026 · 管理者承認が有効",
  "QR Code Verum Pay com baixa automática": "Verum Pay QRコードで自動消込",
  "Fluxo com prova, defesa e aprovação": "証拠・異議申立て・承認のフロー",
  "Envio por portal, e-mail e WhatsApp": "ポータル・メール・WhatsAppで送信",
  "Arquivo timbrado com retenção histórica": "レターヘッド書類を長期保管",
  "Ordens de serviço por categoria e prioridade": "カテゴリと優先度別の作業指示",
  "Controle de acessos, entregas e ocorrências": "入退館・宅配・インシデントの管理",
  "Clientes, planos, licenças e implantação": "顧客、プラン、ライセンス、導入",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "管理者・会計・管理会社・入居者のログイン情報",
  "Notificações": "通知", "Alternar tema": "テーマ切替", "Idioma": "言語", "Perfil de acesso": "アクセス権限",
  "Diretor": "理事長", "Síndico": "管理者", "Tesouraria": "会計", "Administradora": "管理会社", "Morador": "入居者",
  "Visão estratégica, aprovações e auditoria": "戦略ビュー、承認、監査",
  "Operação, multas, comunicados e manutenção": "運営、違約金、お知らせ、メンテナンス",
  "Financeiro, cobranças e conciliação": "会計、請求、照合",
  "Gestão SaaS: clientes, planos e licenças": "SaaS管理：顧客、プラン、ライセンス",
  "Boletos, comprovantes, comunicados e chamados": "請求書、領収書、お知らせ、依頼",
  "Gestão condominial premium · powered by Verum Pay": "プレミアムマンション管理 · powered by Verum Pay",
  "Criar acesso do diretor": "理事長アカウントの作成",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "初回アクセスです。ここで作成したアカウントは次の役割でのログインに使われます：",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": "。この役割は「メール管理」で他の役割のメールとパスワードを登録できます。",
  "Nome completo": "氏名", "E-mail": "メール", "Senha": "パスワード", "Confirmar senha": "パスワード（確認）",
  "Criar conta e continuar": "アカウントを作成して続行",
  "Já tem prédio cadastrado? Fazer login": "登録済みの建物がありますか？ログイン",
  "Entrar como": "ログインする役割", "Trocar perfil": "役割を変更", "Voltar ao cadastro": "登録に戻る",
  "Entrar": "ログイン", "Verificando conta...": "アカウントを確認中...",
  "E-mail ou senha incorretos.": "メールまたはパスワードが違います。",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "メールまたはパスワードが違います。理事長に「メール管理」でアカウントの確認を依頼してください。",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "この端末に理事長アカウントが見つかりません。戻って理事長アカウントを作成してください。",
  "Não foi possível verificar sua conta agora.": "現在アカウントを確認できません。",
  "A senha deve ter pelo menos 4 caracteres.": "パスワードは4文字以上必要です。",
  "As senhas não conferem.": "パスワードが一致しません。",
  "Nenhum acesso de": "次の役割のアカウントがありません：",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "。理事長に「メール管理」での登録を依頼してください。",
  "Tema claro": "ライトテーマ", "Tema escuro": "ダークテーマ",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "この名前のアカウントがありません。理事長に「メール管理」での登録を依頼してください。",
  "Senha incorreta para este nome.": "この名前のパスワードが違います。",
  "Seu nome": "お名前", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "4文字以上", "Repita a senha": "パスワードを再入力",
  "Saldo em caixa": "現金残高", "Inadimplência": "滞納率", "Receitas de": "収入：", "Despesas de": "支出：",
  "Nova cobrança": "新規請求", "Novo gasto": "新規支出", "Nova multa": "新規違約金", "Novo comunicado": "新規お知らせ", "Novo chamado": "新規依頼",
  "Evolução financeira do mês — dia a dia": "今月の収支推移 — 日別",
  "Distribuição de receitas": "収入の内訳", "Despesas por categoria": "カテゴリ別支出",
  "Inadimplência ao longo do tempo": "滞納率の推移", "Atividade recente": "最近のアクティビティ",
  "Aprovações pendentes": "承認待ち", "Alertas do dia": "本日のアラート", "Ver todas →": "すべて見る →",
  "Sem despesas em": "支出なし：", "Sem receitas em": "収入なし：", "Dia": "日",
  "Receita": "収入", "Despesa": "支出", "Multa": "違約金",
  "aguarda decisão do síndico": "管理者の判断待ち",
  "cobrança(s) vencida(s) somando": "件の延滞請求、合計",
  "sem responsável designado": "担当者未割当",
  "Pago": "支払済", "Parcial": "一部", "Em aberto": "未払", "Aguardando": "待機中", "Vencida": "延滞", "Emitida": "発行済",
  "Ocupada": "入居中", "Alugada": "賃貸中", "Vaga": "空室", "Ativo": "有効", "Em teste": "試用中", "Inadimplente": "滞納",
  "Prazo de defesa": "異議申立期間", "Multa aplicada": "違約金確定", "Advertência": "警告",
  "Em andamento": "対応中", "Concluído": "完了", "No condomínio": "館内", "Saiu": "退出", "Retirado": "受取済",
  "Ocorrência": "インシデント", "Cancelada": "キャンセル", "Cancelado": "キャンセル", "Vendida": "売却済", "Reservada": "予約済", "Inativa": "無効",
  "Alta": "高", "Média": "中", "Baixa": "低",
  "Todos os status": "すべての状態", "Todos os papéis": "すべての役割", "Todos": "すべて", "Pagas": "支払済", "Emitidas": "発行済", "Vencidas": "延滞",
  "Abertos": "未対応", "Concluídos": "完了",
  "Nome": "名前", "Papel": "役割", "Unidade": "住戸", "CPF/CNPJ": "身分証番号", "Telefone": "電話", "Status": "状態",
  "Data": "日付", "Tipo": "種類", "Categoria": "カテゴリ", "Descrição": "説明", "Valor": "金額",
  "Responsável": "担当者", "Competência": "対象月", "Vencimento": "期日", "Plano": "プラン", "Mensalidade": "月額", "Renovação": "更新",
  "Evolução da receita recorrente": "継続収益の推移", "Planos": "プラン",
  "Últimos comunicados": "最新のお知らせ", "Minha situação": "マイステータス", "Cobranças da unidade": "住戸の請求",
  "Unidade / apartamento": "住戸 / 部屋", "Cadastre unidades primeiro na tela Unidades.": "先に「住戸」画面で住戸を登録してください。",
  "Nenhuma cobrança para esta unidade ainda.": "この住戸への請求はまだありません。",
  "Toque para ler": "タップして読む",
  "Destino": "宛先", "Todas as unidades (rateio pela fração)": "全住戸（持分割合で按分）",
  "Valor da cobrança (R$)": "請求金額 (R$)",
  "Será gerada 1 cobrança para": "次の宛先に1件の請求を作成します：",
  "O morador verá o aviso no portal dele.": "入居者は自分のポータルで通知を確認できます。",
  "Serão geradas": "作成される請求：", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "件（会計責任者のいる住戸）、持分割合で按分。",
  "Gerar cobrança": "請求を作成", "Gerar": "作成", "cobranças": "件の請求",
  "Cobrança de": "請求：", "vencida": "（延滞）", "Nova cobrança de": "新しい請求：",
  "vence em": "期日", "venceu em": "期日超過：",
  "Multas da unidade": "住戸の違約金",
  "Você pode apresentar defesa até": "次の期日まで異議申立てができます：",
  "Procure a administração do condomínio.": "管理事務所にお問い合わせください。",
  "Movimentação de hoje": "本日の入退館", "Nenhum chamado aqui": "依頼はありません", "sem custo lançado": "費用未計上",
  "Nome fantasia *": "通称名 *", "Razão social": "正式名称", "CNPJ *": "法人番号 *", "Seu CPF (diretor) *": "あなたの身分証番号（理事長）*",
  "Porte": "規模", "Endereço completo *": "住所 *", "Nome fantasia": "通称名", "CNPJ": "法人番号",
  "Inscrição municipal": "市登録番号", "Torres / blocos": "棟", "Unidades / vagas": "住戸 / 駐車場",
  "Endereço completo": "住所", "Administradora responsável": "担当管理会社", "Síndico atual": "現管理者",
  "Diretor administrativo": "管理担当理事", "Início da gestão": "任期開始", "Status do contrato SaaS": "SaaS契約状況",
  "Horário de silêncio": "静粛時間", "Mudanças": "引越し", "Obras": "工事", "Visitantes": "来訪者", "Animais": "ペット",
  "Áreas comuns": "共用部", "Logo (upload)": "ロゴ（アップロード）", "Cor primária do portal": "ポータルのメインカラー",
  "Responsável financeiro": "会計責任者", "Fração ideal (%)": "持分割合 (%)", "Área privativa (m²)": "専有面積 (m²)",
  "Vagas vinculadas": "紐づく駐車場", "Número": "番号", "Bloco / torre": "棟", "Andar": "階",
  "Número (ou início do intervalo)": "番号（または範囲の開始）", "Até o número (opcional)": "終了番号（任意）",
  "Ex.: 402, 1 ou 1D": "例：402、1、1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "例：100 または 4D — 空欄なら1件のみ作成",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "「終了番号」を入力すると複数の住戸を一括作成できます：1〜100 は 1、2…100 を、1D〜4D は 1D、2D、3D、4D を作成します。棟内で既存の番号はスキップされます。種類・階・状態・持分は全戸に適用されます。",
  "CPF ou CNPJ": "身分証番号", "Papel no condomínio": "マンション内の役割", "Unidade vinculada": "紐づく住戸",
  "Data de entrada": "入居日", "Documento (upload)": "書類（アップロード）",
  "Fundo de reserva": "修繕積立金", "Fundo de obras": "工事基金", "Valor (R$)": "金額 (R$)",
  "Subcategoria / centro de custo": "サブカテゴリ / コストセンター", "Forma de pagamento": "支払方法", "Rateio": "按分",
  "Nota fiscal (anexo)": "領収書（添付）", "Aguardando pagamento": "支払待ち",
  "Valor total a ratear (R$)": "按分する総額 (R$)", "Base de cálculo": "計算基準", "Canais de envio": "送信チャネル",
  "Aplicadas em 2026": "2026年の適用件数", "Em prazo de defesa": "異議申立期間中", "Arrecadado em multas": "違約金収入",
  "Categoria da infração": "違反カテゴリ", "Unidade responsável": "対象住戸", "Data e hora": "日時",
  "Tipo de penalidade": "処分の種類", "Valor (se multa)": "金額（違約金の場合）", "Prazo para defesa": "異議申立期限",
  "Base normativa": "規約上の根拠", "Descrição detalhada": "詳細説明",
  "Provas (foto, vídeo, áudio ou documento)": "証拠（写真・動画・音声・書類）",
  "Destinatários": "宛先", "Título": "タイトル", "Mensagem": "メッセージ", "Canais": "チャネル",
  "Unidade (se aplicável)": "住戸（該当する場合）", "Conteúdo": "内容", "Prioridade": "優先度", "Prazo": "期限",
  "Custo estimado": "概算費用", "Fotos / vídeos": "写真 / 動画", "Descrição do problema": "問題の説明",
  "Acessos registrados": "入退館記録", "Visitantes no condomínio": "館内の来訪者",
  "Entregas registradas": "宅配記録", "Vagas de visitante livres": "空き来客用駐車場",
  "Nome / empresa": "名前 / 会社", "Unidade de destino": "訪問先住戸", "Janela de horário": "時間帯",
  "Veículo (opcional)": "車両（任意）", "Condomínios ativos": "契約中のマンション",
  "Receita recorrente (MRR)": "継続収益 (MRR)", "Em período de teste": "試用期間中",
  "Nova unidade": "新規住戸", "Nova pessoa": "新規人物", "Novo lançamento": "新規仕訳",
  "Gerar cobranças da competência": "当月の請求を作成", "Registrar infração": "違反を登録",
  "Novo documento timbrado": "新規レターヘッド書類", "Abrir chamado de manutenção": "メンテナンス依頼を作成",
  "Pré-autorizar entrada": "入館を事前承認", "Novo acesso": "新規アカウント", "Contratar novo condomínio": "新規マンション契約",
  "Abrir chamado": "依頼を作成",
  "Cancelar": "キャンセル", "Fechar": "閉じる", "Exportar": "エクスポート", "Lançamento": "仕訳", "Pessoa": "人物",
  "Cadastrar unidade": "住戸を登録", "Criar unidade": "住戸を作成", "Cadastrar": "登録",
  "Salvar alterações": "変更を保存", "Gerar cobranças": "請求を作成", "Gerar cobranças do mês": "今月の請求を作成",
  "Reenviar": "再送信", "Baixar": "ダウンロード", "Enviar por WhatsApp": "WhatsAppで送信", "Imprimir PDF": "PDFを印刷",
  "Enviar ao responsável": "担当者に送信", "Cancelar multa": "違約金を取消", "Aprovar (síndico)": "承認（管理者）",
  "Enviar para aprovação": "承認に回す", "Ver": "表示", "Publicar e enviar": "公開して送信",
  "Criar documento timbrado": "レターヘッド書類を作成", "Gerar PDF": "PDFを作成",
  "Gerar QR de acesso": "入館QRを作成", "Registrar ocorrência": "インシデントを登録",
  "Autorizar e gerar QR": "承認してQRを作成", "Adicionar acesso": "アカウントを追加", "Remover": "削除",
  "Criar acesso": "アカウントを作成", "Novo cliente": "新規顧客", "Bloquear acesso": "アクセスを停止", "Abrir painel": "パネルを開く",
  "Iniciar implantação": "導入を開始", "Pagar": "支払う", "Copiar código": "コードをコピー", "Enviar chamado": "依頼を送信",
  "Tentar novamente": "再試行", "Voltar e trocar perfil": "戻って役割を変更", "Sair": "ログアウト",
  "Lançar e enviar para aprovação": "計上して承認に回す", "Criar condomínio e começar": "マンションを作成して開始",
  "Salvando…": "保存中…", "Criando…": "作成中…", "Gerando…": "生成中…", "Publicando…": "公開中…",
  "Abrindo…": "作成中…", "Autorizando…": "承認中…", "Enviando…": "送信中…",
  "Boletos e QR": "請求書とQR", "Extrato": "明細",
  "Início": "ホーム", "Pagamentos": "支払い", "Avisos": "お知らせ",
  "Buscar por número, bloco ou responsável…": "番号・棟・担当者で検索…",
  "Buscar por nome…": "名前で検索…", "Buscar lançamento…": "仕訳を検索…",
  "Buscar por unidade ou responsável…": "住戸または担当者で検索…",
  "Nenhuma unidade encontrada": "住戸が見つかりません",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "検索条件を調整するか、このマンションの最初の住戸を登録してください。",
  "Nenhuma pessoa encontrada": "該当者が見つかりません",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "所有者・入居者・従業員・業者を役割別に登録し、運用の混乱を防ぎましょう。",
  "Nenhum lançamento neste período": "この期間の仕訳はありません",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "当月最初の収入または支出を登録して、資金管理を始めましょう。",
  "Nenhuma cobrança nesta competência": "当月の請求はありません",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "今月の請求を作成しましょう：システムが住戸ごとに固有のVerum Pay QRコードを作成し、ポータル・メール・WhatsAppで送信します。",
  "Nenhum documento nesta categoria": "このカテゴリの書類はありません",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "違約金・お知らせ・議事録・領収書のレターヘッド書類はここに自動保管され、長期保存されます。",
  "Nenhum acesso criado ainda": "アカウントはまだありません",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "管理者・会計・管理会社・入居者がログインできるよう、最初のメールとパスワードを登録してください。",
  "Não foi possível carregar os dados": "データを読み込めませんでした",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "接続を確認して再試行してください。問題が続く場合はサポートにご連絡ください。",
};
