/* 한국어 */
export default {
  "Condomínio": "단지", "Unidades": "세대", "Pessoas": "인원", "Financeiro": "재무",
  "Cobranças QR": "QR 청구", "Multas": "과태료", "Comunicados": "공지", "Documentos": "문서",
  "Manutenção": "유지보수", "Portaria": "관리실", "Gerenciar Emails": "이메일 관리", "Painel SaaS": "SaaS 패널",
  "Visão geral do condomínio em tempo real": "단지 실시간 현황",
  "Cadastro-mãe: dados legais, gestão e regras internas": "기본 정보: 법적 데이터, 관리, 내부 규정",
  "96 unidades · 2 torres + térreo comercial": "96세대 · 2개 동 + 상가 1층",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "역할 분리: 소유주, 임차인, 직원, 협력업체",
  "Competência 06/2026 · aprovações do síndico ativas": "귀속월 06/2026 · 관리소장 승인 활성",
  "QR Code Verum Pay com baixa automática": "자동 정산되는 Verum Pay QR 코드",
  "Fluxo com prova, defesa e aprovação": "증빙·소명·승인 절차",
  "Envio por portal, e-mail e WhatsApp": "포털, 이메일, WhatsApp으로 발송",
  "Arquivo timbrado com retenção histórica": "레터헤드 문서 장기 보관",
  "Ordens de serviço por categoria e prioridade": "카테고리·우선순위별 작업 지시",
  "Controle de acessos, entregas e ocorrências": "출입·택배·사건 관리",
  "Clientes, planos, licenças e implantação": "고객, 요금제, 라이선스, 도입",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "관리소장·경리·관리회사·입주민의 로그인 정보",
  "Notificações": "알림", "Alternar tema": "테마 전환", "Idioma": "언어", "Perfil de acesso": "접근 역할",
  "Diretor": "이사장", "Síndico": "관리소장", "Tesouraria": "경리", "Administradora": "관리회사", "Morador": "입주민",
  "Visão estratégica, aprovações e auditoria": "전략 보기, 승인, 감사",
  "Operação, multas, comunicados e manutenção": "운영, 과태료, 공지, 유지보수",
  "Financeiro, cobranças e conciliação": "재무, 청구, 대사",
  "Gestão SaaS: clientes, planos e licenças": "SaaS 관리: 고객, 요금제, 라이선스",
  "Boletos, comprovantes, comunicados e chamados": "고지서, 영수증, 공지, 민원",
  "Gestão condominial premium · powered by Verum Pay": "프리미엄 단지 관리 · powered by Verum Pay",
  "Criar acesso do diretor": "이사장 계정 만들기",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "첫 접속입니다. 여기서 만든 계정은 다음 역할로 로그인할 때 사용됩니다:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": ". 이 역할은 '이메일 관리'에서 다른 역할의 이메일과 비밀번호를 등록할 수 있습니다.",
  "Nome completo": "성명", "E-mail": "이메일", "Senha": "비밀번호", "Confirmar senha": "비밀번호 확인",
  "Criar conta e continuar": "계정 만들고 계속",
  "Já tem prédio cadastrado? Fazer login": "이미 등록된 건물이 있나요? 로그인",
  "Entrar como": "로그인 역할", "Trocar perfil": "역할 변경", "Voltar ao cadastro": "등록으로 돌아가기",
  "Entrar": "로그인", "Verificando conta...": "계정 확인 중...",
  "E-mail ou senha incorretos.": "이메일 또는 비밀번호가 올바르지 않습니다.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "이메일 또는 비밀번호가 올바르지 않습니다. 이사장에게 '이메일 관리'에서 계정 확인을 요청하세요.",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "이 기기에서 이사장 계정을 찾을 수 없습니다. 돌아가서 이사장 계정을 만드세요.",
  "Não foi possível verificar sua conta agora.": "지금은 계정을 확인할 수 없습니다.",
  "A senha deve ter pelo menos 4 caracteres.": "비밀번호는 4자 이상이어야 합니다.",
  "As senhas não conferem.": "비밀번호가 일치하지 않습니다.",
  "Nenhum acesso de": "다음 역할의 계정이 없습니다:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": ". 이사장에게 '이메일 관리'에서 등록을 요청하세요.",
  "Tema claro": "라이트 테마", "Tema escuro": "다크 테마",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "이 이름의 계정이 없습니다. 이사장에게 '이메일 관리'에서 등록을 요청하세요.",
  "Senha incorreta para este nome.": "이 이름의 비밀번호가 올바르지 않습니다.",
  "Seu nome": "이름", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "4자 이상", "Repita a senha": "비밀번호 재입력",
  "Saldo em caixa": "현금 잔액", "Inadimplência": "연체율", "Receitas de": "수입:", "Despesas de": "지출:",
  "Nova cobrança": "새 청구", "Novo gasto": "새 지출", "Nova multa": "새 과태료", "Novo comunicado": "새 공지", "Novo chamado": "새 민원",
  "Evolução financeira do mês — dia a dia": "이달 재무 추이 — 일별",
  "Distribuição de receitas": "수입 구성", "Despesas por categoria": "카테고리별 지출",
  "Inadimplência ao longo do tempo": "연체율 추이", "Atividade recente": "최근 활동",
  "Aprovações pendentes": "승인 대기", "Alertas do dia": "오늘의 알림", "Ver todas →": "전체 보기 →",
  "Sem despesas em": "지출 없음:", "Sem receitas em": "수입 없음:", "Dia": "일",
  "Receita": "수입", "Despesa": "지출", "Multa": "과태료",
  "aguarda decisão do síndico": "관리소장의 결정 대기 중",
  "cobrança(s) vencida(s) somando": "건의 연체 청구, 합계",
  "sem responsável designado": "담당자 미지정",
  "Pago": "납부됨", "Parcial": "부분", "Em aberto": "미결", "Aguardando": "대기 중", "Vencida": "연체", "Emitida": "발행됨",
  "Ocupada": "거주 중", "Alugada": "임대 중", "Vaga": "공실", "Ativo": "활성", "Em teste": "체험 중", "Inadimplente": "연체 중",
  "Prazo de defesa": "소명 기간", "Multa aplicada": "과태료 확정", "Advertência": "경고",
  "Em andamento": "진행 중", "Concluído": "완료", "No condomínio": "단지 내", "Saiu": "퇴장", "Retirado": "수령됨",
  "Ocorrência": "사건", "Cancelada": "취소됨", "Cancelado": "취소됨", "Vendida": "매도됨", "Reservada": "예약됨", "Inativa": "비활성",
  "Alta": "높음", "Média": "중간", "Baixa": "낮음",
  "Todos os status": "모든 상태", "Todos os papéis": "모든 역할", "Todos": "전체", "Pagas": "납부됨", "Emitidas": "발행됨", "Vencidas": "연체",
  "Abertos": "미처리", "Concluídos": "완료",
  "Nome": "이름", "Papel": "역할", "Unidade": "세대", "CPF/CNPJ": "신분증 번호", "Telefone": "전화", "Status": "상태",
  "Data": "날짜", "Tipo": "유형", "Categoria": "카테고리", "Descrição": "설명", "Valor": "금액",
  "Responsável": "담당자", "Competência": "귀속월", "Vencimento": "만기일", "Plano": "요금제", "Mensalidade": "월 요금", "Renovação": "갱신",
  "Evolução da receita recorrente": "반복 수익 추이", "Planos": "요금제",
  "Últimos comunicados": "최신 공지", "Minha situação": "내 현황", "Cobranças da unidade": "세대 청구 내역",
  "Unidade / apartamento": "세대 / 호", "Cadastre unidades primeiro na tela Unidades.": "먼저 '세대' 화면에서 세대를 등록하세요.",
  "Nenhuma cobrança para esta unidade ainda.": "이 세대에는 아직 청구가 없습니다.",
  "Toque para ler": "눌러서 읽기",
  "Destino": "대상", "Todas as unidades (rateio pela fração)": "전체 세대(지분 비율로 배분)",
  "Valor da cobrança (R$)": "청구 금액 (R$)",
  "Será gerada 1 cobrança para": "다음 대상에 청구 1건이 생성됩니다:",
  "O morador verá o aviso no portal dele.": "입주민은 자신의 포털에서 알림을 확인합니다.",
  "Serão geradas": "생성될 청구:", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "건(재무 담당자가 있는 세대), 지분 비율로 배분.",
  "Gerar cobrança": "청구 생성", "Gerar": "생성", "cobranças": "건의 청구",
  "Cobrança de": "청구:", "vencida": "(연체)", "Nova cobrança de": "새 청구:",
  "vence em": "만기일", "venceu em": "만기 경과:",
  "Multas da unidade": "세대 과태료",
  "Você pode apresentar defesa até": "다음 날짜까지 소명할 수 있습니다:",
  "Procure a administração do condomínio.": "관리사무소에 문의하세요.",
  "Movimentação de hoje": "오늘의 출입", "Nenhum chamado aqui": "민원이 없습니다", "sem custo lançado": "비용 미등록",
  "Nome fantasia *": "상호 *", "Razão social": "법인명", "CNPJ *": "사업자 번호 *", "Seu CPF (diretor) *": "본인 신분증 번호(이사장) *",
  "Porte": "규모", "Endereço completo *": "전체 주소 *", "Nome fantasia": "상호", "CNPJ": "사업자 번호",
  "Inscrição municipal": "시 등록 번호", "Torres / blocos": "동", "Unidades / vagas": "세대 / 주차면",
  "Endereço completo": "전체 주소", "Administradora responsável": "담당 관리회사", "Síndico atual": "현 관리소장",
  "Diretor administrativo": "관리 이사", "Início da gestão": "임기 시작", "Status do contrato SaaS": "SaaS 계약 상태",
  "Horário de silêncio": "정숙 시간", "Mudanças": "이사", "Obras": "공사", "Visitantes": "방문객", "Animais": "반려동물",
  "Áreas comuns": "공용 공간", "Logo (upload)": "로고(업로드)", "Cor primária do portal": "포털 기본 색상",
  "Responsável financeiro": "재무 담당자", "Fração ideal (%)": "지분 비율 (%)", "Área privativa (m²)": "전용 면적 (m²)",
  "Vagas vinculadas": "연결된 주차면", "Número": "번호", "Bloco / torre": "동", "Andar": "층",
  "Número (ou início do intervalo)": "번호(또는 범위 시작)", "Até o número (opcional)": "끝 번호(선택)",
  "Ex.: 402, 1 ou 1D": "예: 402, 1 또는 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "예: 100 또는 4D — 비우면 1개만 생성",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "'끝 번호'를 입력하면 여러 세대를 한 번에 만들 수 있습니다. 1~100은 1, 2… 100을, 1D~4D는 1D, 2D, 3D, 4D를 생성합니다. 동에 이미 있는 번호는 건너뜁니다. 유형·층·상태·지분은 전체에 적용됩니다.",
  "CPF ou CNPJ": "신분증 번호", "Papel no condomínio": "단지 내 역할", "Unidade vinculada": "연결된 세대",
  "Data de entrada": "입주일", "Documento (upload)": "문서(업로드)",
  "Fundo de reserva": "수선충당금", "Fundo de obras": "공사 기금", "Valor (R$)": "금액 (R$)",
  "Subcategoria / centro de custo": "하위 카테고리 / 코스트센터", "Forma de pagamento": "결제 수단", "Rateio": "배분",
  "Nota fiscal (anexo)": "세금계산서(첨부)", "Aguardando pagamento": "결제 대기",
  "Valor total a ratear (R$)": "배분할 총액 (R$)", "Base de cálculo": "산정 기준", "Canais de envio": "발송 채널",
  "Aplicadas em 2026": "2026년 부과", "Em prazo de defesa": "소명 기간 중", "Arrecadado em multas": "과태료 수입",
  "Categoria da infração": "위반 카테고리", "Unidade responsável": "대상 세대", "Data e hora": "일시",
  "Tipo de penalidade": "처분 유형", "Valor (se multa)": "금액(과태료인 경우)", "Prazo para defesa": "소명 기한",
  "Base normativa": "규정 근거", "Descrição detalhada": "상세 설명",
  "Provas (foto, vídeo, áudio ou documento)": "증빙(사진, 영상, 음성, 문서)",
  "Destinatários": "수신자", "Título": "제목", "Mensagem": "메시지", "Canais": "채널",
  "Unidade (se aplicável)": "세대(해당 시)", "Conteúdo": "내용", "Prioridade": "우선순위", "Prazo": "기한",
  "Custo estimado": "예상 비용", "Fotos / vídeos": "사진 / 영상", "Descrição do problema": "문제 설명",
  "Acessos registrados": "출입 기록", "Visitantes no condomínio": "단지 내 방문객",
  "Entregas registradas": "택배 기록", "Vagas de visitante livres": "빈 방문객 주차면",
  "Nome / empresa": "이름 / 회사", "Unidade de destino": "방문 세대", "Janela de horário": "시간대",
  "Veículo (opcional)": "차량(선택)", "Condomínios ativos": "활성 단지",
  "Receita recorrente (MRR)": "반복 수익 (MRR)", "Em período de teste": "체험 기간 중",
  "Nova unidade": "새 세대", "Nova pessoa": "새 인원", "Novo lançamento": "새 회계 기록",
  "Gerar cobranças da competência": "귀속월 청구 생성", "Registrar infração": "위반 등록",
  "Novo documento timbrado": "새 레터헤드 문서", "Abrir chamado de manutenção": "유지보수 민원 등록",
  "Pré-autorizar entrada": "출입 사전 승인", "Novo acesso": "새 계정", "Contratar novo condomínio": "신규 단지 계약",
  "Abrir chamado": "민원 등록",
  "Cancelar": "취소", "Fechar": "닫기", "Exportar": "내보내기", "Lançamento": "회계 기록", "Pessoa": "인원",
  "Cadastrar unidade": "세대 등록", "Criar unidade": "세대 생성", "Cadastrar": "등록",
  "Salvar alterações": "변경 사항 저장", "Gerar cobranças": "청구 생성", "Gerar cobranças do mês": "이달 청구 생성",
  "Reenviar": "재발송", "Baixar": "다운로드", "Enviar por WhatsApp": "WhatsApp으로 보내기", "Imprimir PDF": "PDF 인쇄",
  "Enviar ao responsável": "담당자에게 보내기", "Cancelar multa": "과태료 취소", "Aprovar (síndico)": "승인(관리소장)",
  "Enviar para aprovação": "승인 요청", "Ver": "보기", "Publicar e enviar": "게시하고 발송",
  "Criar documento timbrado": "레터헤드 문서 생성", "Gerar PDF": "PDF 생성",
  "Gerar QR de acesso": "출입 QR 생성", "Registrar ocorrência": "사건 등록",
  "Autorizar e gerar QR": "승인하고 QR 생성", "Adicionar acesso": "계정 추가", "Remover": "삭제",
  "Criar acesso": "계정 생성", "Novo cliente": "신규 고객", "Bloquear acesso": "접근 차단", "Abrir painel": "패널 열기",
  "Iniciar implantação": "도입 시작", "Pagar": "결제", "Copiar código": "코드 복사", "Enviar chamado": "민원 제출",
  "Tentar novamente": "다시 시도", "Voltar e trocar perfil": "돌아가서 역할 변경", "Sair": "로그아웃",
  "Lançar e enviar para aprovação": "기록하고 승인 요청", "Criar condomínio e começar": "단지를 만들고 시작",
  "Salvando…": "저장 중…", "Criando…": "생성 중…", "Gerando…": "생성 중…", "Publicando…": "게시 중…",
  "Abrindo…": "여는 중…", "Autorizando…": "승인 중…", "Enviando…": "보내는 중…",
  "Boletos e QR": "고지서와 QR", "Extrato": "내역",
  "Início": "홈", "Pagamentos": "결제", "Avisos": "공지",
  "Buscar por número, bloco ou responsável…": "번호, 동, 담당자로 검색…",
  "Buscar por nome…": "이름으로 검색…", "Buscar lançamento…": "회계 기록 검색…",
  "Buscar por unidade ou responsável…": "세대 또는 담당자로 검색…",
  "Nenhuma unidade encontrada": "세대를 찾을 수 없습니다",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "검색이나 필터를 조정하거나, 이 단지의 첫 세대를 등록하세요.",
  "Nenhuma pessoa encontrada": "해당 인원이 없습니다",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "소유주, 임차인, 직원, 협력업체를 역할별로 등록해 운영 혼선을 방지하세요.",
  "Nenhum lançamento neste período": "이 기간의 회계 기록이 없습니다",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "이달의 첫 수입 또는 지출을 등록해 자금 흐름을 추적하세요.",
  "Nenhuma cobrança nesta competência": "이 귀속월에는 청구가 없습니다",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "이달 청구를 생성하세요. 시스템이 세대별 고유 Verum Pay QR 코드를 만들어 포털, 이메일, WhatsApp으로 발송합니다.",
  "Nenhum documento nesta categoria": "이 카테고리에는 문서가 없습니다",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "과태료, 공지, 회의록, 영수증의 레터헤드 문서가 자동으로 보관되며 수년간 유지됩니다.",
  "Nenhum acesso criado ainda": "아직 생성된 계정이 없습니다",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "관리소장, 경리, 관리회사, 입주민이 로그인할 수 있도록 첫 이메일과 비밀번호를 등록하세요.",
  "Não foi possível carregar os dados": "데이터를 불러올 수 없습니다",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "연결을 확인하고 다시 시도하세요. 문제가 계속되면 지원팀에 문의하세요.",
};
