/* Русский */
export default {
  "Condomínio": "ЖК", "Unidades": "Квартиры", "Pessoas": "Люди", "Financeiro": "Финансы",
  "Cobranças QR": "QR-платежи", "Multas": "Штрафы", "Comunicados": "Объявления", "Documentos": "Документы",
  "Manutenção": "Обслуживание", "Portaria": "Консьерж", "Gerenciar Emails": "Управление доступами", "Painel SaaS": "SaaS-панель",
  "Visão geral do condomínio em tempo real": "Обзор ЖК в реальном времени",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Основная карточка: юридические данные, управление и внутренние правила",
  "96 unidades · 2 torres + térreo comercial": "96 квартир · 2 башни + коммерческий этаж",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "Раздельные роли: собственник, арендатор, сотрудник и подрядчик",
  "Competência 06/2026 · aprovações do síndico ativas": "Период 06/2026 · согласования управляющего включены",
  "QR Code Verum Pay com baixa automática": "QR-код Verum Pay с автоматическим зачислением",
  "Fluxo com prova, defesa e aprovação": "Процесс с доказательствами, возражением и утверждением",
  "Envio por portal, e-mail e WhatsApp": "Отправка через портал, e-mail и WhatsApp",
  "Arquivo timbrado com retenção histórica": "Архив фирменных документов с длительным хранением",
  "Ordens de serviço por categoria e prioridade": "Заявки по категориям и приоритету",
  "Controle de acessos, entregas e ocorrências": "Контроль доступа, доставок и происшествий",
  "Clientes, planos, licenças e implantação": "Клиенты, тарифы, лицензии и внедрение",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "Логины и пароли для управляющего, бухгалтерии, УК и жильцов",
  "Notificações": "Уведомления", "Alternar tema": "Сменить тему", "Idioma": "Язык", "Perfil de acesso": "Профиль доступа",
  "Diretor": "Директор", "Síndico": "Управляющий", "Tesouraria": "Бухгалтерия", "Administradora": "Управляющая компания", "Morador": "Жилец",
  "Visão estratégica, aprovações e auditoria": "Стратегический обзор, согласования и аудит",
  "Operação, multas, comunicados e manutenção": "Операции, штрафы, объявления и обслуживание",
  "Financeiro, cobranças e conciliação": "Финансы, платежи и сверка",
  "Gestão SaaS: clientes, planos e licenças": "Управление SaaS: клиенты, тарифы и лицензии",
  "Boletos, comprovantes, comunicados e chamados": "Счета, квитанции, объявления и заявки",
  "Gestão condominial premium · powered by Verum Pay": "Премиальное управление ЖК · powered by Verum Pay",
  "Criar acesso do diretor": "Создать доступ директора",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Это первый вход. Созданный здесь аккаунт будет использоваться для входа как",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": ", который сможет создать логины и пароли остальных ролей в «Управлении доступами».",
  "Nome completo": "Полное имя", "E-mail": "E-mail", "Senha": "Пароль", "Confirmar senha": "Подтвердите пароль",
  "Criar conta e continuar": "Создать аккаунт и продолжить",
  "Já tem prédio cadastrado? Fazer login": "Здание уже зарегистрировано? Войти",
  "Entrar como": "Войти как", "Trocar perfil": "Сменить роль", "Voltar ao cadastro": "Назад к регистрации",
  "Entrar": "Войти", "Verificando conta...": "Проверка аккаунта...",
  "E-mail ou senha incorretos.": "Неверный e-mail или пароль.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "Неверный e-mail или пароль. Попросите директора проверить ваш доступ в «Управлении доступами».",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "На этом устройстве не найден доступ директора. Вернитесь и создайте доступ директора.",
  "Não foi possível verificar sua conta agora.": "Сейчас не удалось проверить ваш аккаунт.",
  "A senha deve ter pelo menos 4 caracteres.": "Пароль должен содержать не менее 4 символов.",
  "As senhas não conferem.": "Пароли не совпадают.",
  "Nenhum acesso de": "Нет доступа для роли:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": ". Попросите директора создать его в «Управлении доступами».",
  "Tema claro": "Светлая тема", "Tema escuro": "Тёмная тема",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "Нет доступа с таким именем. Попросите директора зарегистрировать его в «Управлении доступами».",
  "Senha incorreta para este nome.": "Неверный пароль для этого имени.",
  "Seu nome": "Ваше имя", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "Минимум 4 символа", "Repita a senha": "Повторите пароль",
  "Saldo em caixa": "Остаток средств", "Inadimplência": "Просрочка", "Receitas de": "Доходы за", "Despesas de": "Расходы за",
  "Nova cobrança": "Новый платёж", "Novo gasto": "Новый расход", "Nova multa": "Новый штраф", "Novo comunicado": "Новое объявление", "Novo chamado": "Новая заявка",
  "Evolução financeira do mês — dia a dia": "Финансовая динамика месяца — по дням",
  "Distribuição de receitas": "Структура доходов", "Despesas por categoria": "Расходы по категориям",
  "Inadimplência ao longo do tempo": "Динамика просрочки", "Atividade recente": "Последние события",
  "Aprovações pendentes": "Ожидают согласования", "Alertas do dia": "Сегодняшние уведомления", "Ver todas →": "Показать все →",
  "Sem despesas em": "Нет расходов за", "Sem receitas em": "Нет доходов за", "Dia": "День",
  "Receita": "Доход", "Despesa": "Расход", "Multa": "Штраф",
  "aguarda decisão do síndico": "ожидает решения управляющего",
  "cobrança(s) vencida(s) somando": "просроченных платежей на сумму",
  "sem responsável designado": "без назначенного ответственного",
  "Pago": "Оплачено", "Parcial": "Частично", "Em aberto": "Открыт", "Aguardando": "В ожидании", "Vencida": "Просрочен", "Emitida": "Выставлен",
  "Ocupada": "Заселена", "Alugada": "Сдана", "Vaga": "Свободна", "Ativo": "Активен", "Em teste": "Тест", "Inadimplente": "Должник",
  "Prazo de defesa": "Срок возражения", "Multa aplicada": "Штраф применён", "Advertência": "Предупреждение",
  "Em andamento": "В работе", "Concluído": "Завершено", "No condomínio": "На территории", "Saiu": "Ушёл", "Retirado": "Получено",
  "Ocorrência": "Происшествие", "Cancelada": "Отменена", "Cancelado": "Отменён", "Vendida": "Продана", "Reservada": "Забронирована", "Inativa": "Неактивна",
  "Alta": "Высокий", "Média": "Средний", "Baixa": "Низкий",
  "Todos os status": "Все статусы", "Todos os papéis": "Все роли", "Todos": "Все", "Pagas": "Оплаченные", "Emitidas": "Выставленные", "Vencidas": "Просроченные",
  "Abertos": "Открытые", "Concluídos": "Завершённые",
  "Nome": "Имя", "Papel": "Роль", "Unidade": "Квартира", "CPF/CNPJ": "ИНН/паспорт", "Telefone": "Телефон", "Status": "Статус",
  "Data": "Дата", "Tipo": "Тип", "Categoria": "Категория", "Descrição": "Описание", "Valor": "Сумма",
  "Responsável": "Ответственный", "Competência": "Период", "Vencimento": "Срок оплаты", "Plano": "Тариф", "Mensalidade": "Ежемесячный платёж", "Renovação": "Продление",
  "Evolução da receita recorrente": "Динамика регулярного дохода", "Planos": "Тарифы",
  "Últimos comunicados": "Последние объявления", "Minha situação": "Моя сводка", "Cobranças da unidade": "Платежи квартиры",
  "Unidade / apartamento": "Квартира", "Cadastre unidades primeiro na tela Unidades.": "Сначала зарегистрируйте квартиры на экране «Квартиры».",
  "Nenhuma cobrança para esta unidade ainda.": "Для этой квартиры пока нет платежей.",
  "Toque para ler": "Нажмите, чтобы прочитать",
  "Destino": "Получатель", "Todas as unidades (rateio pela fração)": "Все квартиры (распределение по доле)",
  "Valor da cobrança (R$)": "Сумма платежа (R$)",
  "Será gerada 1 cobrança para": "Будет создан 1 платёж для",
  "O morador verá o aviso no portal dele.": "Жилец увидит уведомление в своём портале.",
  "Serão geradas": "Система создаст", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "платежей (квартиры с финансовым ответственным), распределённых по идеальной доле.",
  "Gerar cobrança": "Создать платёж", "Gerar": "Создать", "cobranças": "платежей",
  "Cobrança de": "Платёж за", "vencida": "просрочен", "Nova cobrança de": "Новый платёж за",
  "vence em": "срок оплаты", "venceu em": "просрочен с",
  "Multas da unidade": "Штрафы квартиры",
  "Você pode apresentar defesa até": "Вы можете подать возражение до",
  "Procure a administração do condomínio.": "Обратитесь в администрацию ЖК.",
  "Movimentação de hoje": "Сегодняшние события", "Nenhum chamado aqui": "Заявок нет", "sem custo lançado": "затраты не указаны",
  "Nome fantasia *": "Коммерческое название *", "Razão social": "Юридическое название", "CNPJ *": "ИНН организации *", "Seu CPF (diretor) *": "Ваш ИНН/паспорт (директор) *",
  "Porte": "Размер", "Endereço completo *": "Полный адрес *", "Nome fantasia": "Коммерческое название", "CNPJ": "ИНН организации",
  "Inscrição municipal": "Муниципальная регистрация", "Torres / blocos": "Башни / корпуса", "Unidades / vagas": "Квартиры / парковочные места",
  "Endereço completo": "Полный адрес", "Administradora responsável": "Управляющая компания", "Síndico atual": "Текущий управляющий",
  "Diretor administrativo": "Административный директор", "Início da gestão": "Начало срока", "Status do contrato SaaS": "Статус SaaS-договора",
  "Horário de silêncio": "Часы тишины", "Mudanças": "Переезды", "Obras": "Ремонтные работы", "Visitantes": "Посетители", "Animais": "Животные",
  "Áreas comuns": "Общие зоны", "Logo (upload)": "Логотип (загрузка)", "Cor primária do portal": "Основной цвет портала",
  "Responsável financeiro": "Финансовый ответственный", "Fração ideal (%)": "Идеальная доля (%)", "Área privativa (m²)": "Площадь (м²)",
  "Vagas vinculadas": "Привязанные парковочные места", "Número": "Номер", "Bloco / torre": "Корпус / башня", "Andar": "Этаж",
  "Número (ou início do intervalo)": "Номер (или начало диапазона)", "Até o número (opcional)": "До номера (необязательно)",
  "Ex.: 402, 1 ou 1D": "Напр.: 402, 1 или 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Напр.: 100 или 4D — пусто создаст только одну",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "Заполните «До номера», чтобы создать несколько квартир сразу: 1–100 создаст 1, 2… 100; 1D–4D создаст 1D, 2D, 3D и 4D. Существующие в корпусе номера пропускаются. Тип, этаж, статус и доля применяются ко всем.",
  "CPF ou CNPJ": "ИНН/паспорт", "Papel no condomínio": "Роль в ЖК", "Unidade vinculada": "Привязанная квартира",
  "Data de entrada": "Дата въезда", "Documento (upload)": "Документ (загрузка)",
  "Fundo de reserva": "Резервный фонд", "Fundo de obras": "Фонд ремонта", "Valor (R$)": "Сумма (R$)",
  "Subcategoria / centro de custo": "Подкатегория / центр затрат", "Forma de pagamento": "Способ оплаты", "Rateio": "Распределение",
  "Nota fiscal (anexo)": "Счёт-фактура (вложение)", "Aguardando pagamento": "Ожидает оплаты",
  "Valor total a ratear (R$)": "Общая сумма к распределению (R$)", "Base de cálculo": "База расчёта", "Canais de envio": "Каналы отправки",
  "Aplicadas em 2026": "Применено в 2026", "Em prazo de defesa": "В сроке возражения", "Arrecadado em multas": "Собрано штрафов",
  "Categoria da infração": "Категория нарушения", "Unidade responsável": "Ответственная квартира", "Data e hora": "Дата и время",
  "Tipo de penalidade": "Тип взыскания", "Valor (se multa)": "Сумма (если штраф)", "Prazo para defesa": "Срок возражения",
  "Base normativa": "Нормативная база", "Descrição detalhada": "Подробное описание",
  "Provas (foto, vídeo, áudio ou documento)": "Доказательства (фото, видео, аудио или документ)",
  "Destinatários": "Получатели", "Título": "Заголовок", "Mensagem": "Сообщение", "Canais": "Каналы",
  "Unidade (se aplicável)": "Квартира (если применимо)", "Conteúdo": "Содержимое", "Prioridade": "Приоритет", "Prazo": "Срок",
  "Custo estimado": "Оценочная стоимость", "Fotos / vídeos": "Фото / видео", "Descrição do problema": "Описание проблемы",
  "Acessos registrados": "Зарегистрированные проходы", "Visitantes no condomínio": "Посетители на территории",
  "Entregas registradas": "Зарегистрированные доставки", "Vagas de visitante livres": "Свободные гостевые места",
  "Nome / empresa": "Имя / компания", "Unidade de destino": "Квартира назначения", "Janela de horário": "Временной интервал",
  "Veículo (opcional)": "Автомобиль (необязательно)", "Condomínios ativos": "Активные ЖК",
  "Receita recorrente (MRR)": "Регулярный доход (MRR)", "Em período de teste": "На тестовом периоде",
  "Nova unidade": "Новая квартира", "Nova pessoa": "Новый человек", "Novo lançamento": "Новая запись",
  "Gerar cobranças da competência": "Создать платежи периода", "Registrar infração": "Зарегистрировать нарушение",
  "Novo documento timbrado": "Новый фирменный документ", "Abrir chamado de manutenção": "Создать заявку на обслуживание",
  "Pré-autorizar entrada": "Предварительно разрешить вход", "Novo acesso": "Новый доступ", "Contratar novo condomínio": "Подключить новый ЖК",
  "Abrir chamado": "Создать заявку",
  "Cancelar": "Отмена", "Fechar": "Закрыть", "Exportar": "Экспорт", "Lançamento": "Запись", "Pessoa": "Человек",
  "Cadastrar unidade": "Зарегистрировать квартиру", "Criar unidade": "Создать квартиру", "Cadastrar": "Зарегистрировать",
  "Salvar alterações": "Сохранить изменения", "Gerar cobranças": "Создать платежи", "Gerar cobranças do mês": "Создать платежи месяца",
  "Reenviar": "Отправить снова", "Baixar": "Скачать", "Enviar por WhatsApp": "Отправить в WhatsApp", "Imprimir PDF": "Печать PDF",
  "Enviar ao responsável": "Отправить ответственному", "Cancelar multa": "Отменить штраф", "Aprovar (síndico)": "Утвердить (управляющий)",
  "Enviar para aprovação": "Отправить на согласование", "Ver": "Просмотр", "Publicar e enviar": "Опубликовать и отправить",
  "Criar documento timbrado": "Создать фирменный документ", "Gerar PDF": "Создать PDF",
  "Gerar QR de acesso": "Создать QR для входа", "Registrar ocorrência": "Зарегистрировать происшествие",
  "Autorizar e gerar QR": "Разрешить и создать QR", "Adicionar acesso": "Добавить доступ", "Remover": "Удалить",
  "Criar acesso": "Создать доступ", "Novo cliente": "Новый клиент", "Bloquear acesso": "Заблокировать доступ", "Abrir painel": "Открыть панель",
  "Iniciar implantação": "Начать внедрение", "Pagar": "Оплатить", "Copiar código": "Скопировать код", "Enviar chamado": "Отправить заявку",
  "Tentar novamente": "Повторить", "Voltar e trocar perfil": "Назад к выбору роли", "Sair": "Выйти",
  "Lançar e enviar para aprovação": "Провести и отправить на согласование", "Criar condomínio e começar": "Создать ЖК и начать",
  "Salvando…": "Сохранение…", "Criando…": "Создание…", "Gerando…": "Генерация…", "Publicando…": "Публикация…",
  "Abrindo…": "Открытие…", "Autorizando…": "Разрешение…", "Enviando…": "Отправка…",
  "Boletos e QR": "Счета и QR", "Extrato": "Выписка",
  "Início": "Главная", "Pagamentos": "Платежи", "Avisos": "Объявления",
  "Buscar por número, bloco ou responsável…": "Поиск по номеру, корпусу или ответственному…",
  "Buscar por nome…": "Поиск по имени…", "Buscar lançamento…": "Поиск записи…",
  "Buscar por unidade ou responsável…": "Поиск по квартире или ответственному…",
  "Nenhuma unidade encontrada": "Квартиры не найдены",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Измените поиск или фильтры либо зарегистрируйте первую квартиру этого ЖК.",
  "Nenhuma pessoa encontrada": "Никто не найден",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Регистрируйте собственников, арендаторов, сотрудников и подрядчиков с раздельными ролями, чтобы избежать путаницы.",
  "Nenhum lançamento neste período": "Записей за этот период нет",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Внесите первый доход или расход периода, чтобы начать отслеживать кассу.",
  "Nenhuma cobrança nesta competência": "Платежей за этот период нет",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "Создайте платежи месяца: система формирует уникальный QR-код Verum Pay для каждой квартиры и отправляет через портал, e-mail или WhatsApp.",
  "Nenhum documento nesta categoria": "Документов в этой категории нет",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Фирменные документы по штрафам, объявлениям, протоколам и квитанциям автоматически архивируются здесь и хранятся годами.",
  "Nenhum acesso criado ainda": "Доступы ещё не созданы",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "Создайте первый логин и пароль, чтобы управляющий, бухгалтерия, УК и жильцы могли войти.",
  "Não foi possível carregar os dados": "Не удалось загрузить данные",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Проверьте соединение и повторите попытку. Если проблема сохраняется, обратитесь в поддержку.",
};
