/* Türkçe */
export default {
  "Condomínio": "Site", "Unidades": "Daireler", "Pessoas": "Kişiler", "Financeiro": "Finans",
  "Cobranças QR": "QR Tahsilat", "Multas": "Cezalar", "Comunicados": "Duyurular", "Documentos": "Belgeler",
  "Manutenção": "Bakım", "Portaria": "Danışma", "Gerenciar Emails": "E-posta Yönetimi", "Painel SaaS": "SaaS Paneli",
  "Visão geral do condomínio em tempo real": "Sitenin gerçek zamanlı genel görünümü",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Ana kayıt: yasal bilgiler, yönetim ve iç kurallar",
  "96 unidades · 2 torres + térreo comercial": "96 daire · 2 kule + ticari zemin kat",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "Ayrı roller: mal sahibi, kiracı, çalışan ve tedarikçi",
  "Competência 06/2026 · aprovações do síndico ativas": "Dönem 06/2026 · yönetici onayları etkin",
  "QR Code Verum Pay com baixa automática": "Otomatik mutabakatlı Verum Pay QR kodu",
  "Fluxo com prova, defesa e aprovação": "Kanıt, itiraz ve onay süreci",
  "Envio por portal, e-mail e WhatsApp": "Portal, e-posta ve WhatsApp ile gönderim",
  "Arquivo timbrado com retenção histórica": "Antetli belge arşivi, uzun süreli saklama",
  "Ordens de serviço por categoria e prioridade": "Kategori ve önceliğe göre iş emirleri",
  "Controle de acessos, entregas e ocorrências": "Giriş, teslimat ve olay yönetimi",
  "Clientes, planos, licenças e implantação": "Müşteriler, planlar, lisanslar ve kurulum",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "Yönetici, muhasebe, yönetim şirketi ve sakinlerin giriş bilgileri",
  "Notificações": "Bildirimler", "Alternar tema": "Tema değiştir", "Idioma": "Dil", "Perfil de acesso": "Erişim rolü",
  "Diretor": "Direktör", "Síndico": "Yönetici", "Tesouraria": "Muhasebe", "Administradora": "Yönetim şirketi", "Morador": "Sakin",
  "Visão estratégica, aprovações e auditoria": "Stratejik görünüm, onaylar ve denetim",
  "Operação, multas, comunicados e manutenção": "Operasyon, cezalar, duyurular ve bakım",
  "Financeiro, cobranças e conciliação": "Finans, tahsilat ve mutabakat",
  "Gestão SaaS: clientes, planos e licenças": "SaaS yönetimi: müşteriler, planlar ve lisanslar",
  "Boletos, comprovantes, comunicados e chamados": "Faturalar, makbuzlar, duyurular ve talepler",
  "Gestão condominial premium · powered by Verum Pay": "Premium site yönetimi · powered by Verum Pay",
  "Criar acesso do diretor": "Direktör hesabı oluştur",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Bu ilk giriş. Burada oluşturulan hesap şu rolle giriş için kullanılacak:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": ". Bu rol, diğer rollerin e-posta ve şifrelerini \"E-posta Yönetimi\"nde kaydedebilir.",
  "Nome completo": "Ad soyad", "E-mail": "E-posta", "Senha": "Şifre", "Confirmar senha": "Şifreyi onayla",
  "Criar conta e continuar": "Hesap oluştur ve devam et",
  "Já tem prédio cadastrado? Fazer login": "Kayıtlı bina var mı? Giriş yap",
  "Entrar como": "Şu rolle gir", "Trocar perfil": "Rol değiştir", "Voltar ao cadastro": "Kayda geri dön",
  "Entrar": "Giriş yap", "Verificando conta...": "Hesap doğrulanıyor...",
  "E-mail ou senha incorretos.": "E-posta veya şifre hatalı.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "E-posta veya şifre hatalı. Direktörden hesabınızı \"E-posta Yönetimi\"nde kontrol etmesini isteyin.",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "Bu cihazda direktör hesabı bulunamadı. Geri dönüp direktör hesabını oluşturun.",
  "Não foi possível verificar sua conta agora.": "Hesabınız şu anda doğrulanamadı.",
  "A senha deve ter pelo menos 4 caracteres.": "Şifre en az 4 karakter olmalıdır.",
  "As senhas não conferem.": "Şifreler eşleşmiyor.",
  "Nenhum acesso de": "Şu rol için hesap yok:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": ". Direktörden \"E-posta Yönetimi\"nde oluşturmasını isteyin.",
  "Tema claro": "Açık tema", "Tema escuro": "Koyu tema",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "Bu isimle hesap yok. Direktörden \"E-posta Yönetimi\"nde kaydetmesini isteyin.",
  "Senha incorreta para este nome.": "Bu isim için şifre hatalı.",
  "Seu nome": "Adınız", "voce@exemplo.com": "siz@ornek.com", "Mínimo 4 caracteres": "En az 4 karakter", "Repita a senha": "Şifreyi tekrarlayın",
  "Saldo em caixa": "Kasa bakiyesi", "Inadimplência": "Gecikme oranı", "Receitas de": "Gelirler:", "Despesas de": "Giderler:",
  "Nova cobrança": "Yeni tahsilat", "Novo gasto": "Yeni gider", "Nova multa": "Yeni ceza", "Novo comunicado": "Yeni duyuru", "Novo chamado": "Yeni talep",
  "Evolução financeira do mês — dia a dia": "Ayın mali gelişimi — gün gün",
  "Distribuição de receitas": "Gelir dağılımı", "Despesas por categoria": "Kategoriye göre giderler",
  "Inadimplência ao longo do tempo": "Zaman içinde gecikme", "Atividade recente": "Son etkinlik",
  "Aprovações pendentes": "Bekleyen onaylar", "Alertas do dia": "Günün uyarıları", "Ver todas →": "Tümünü gör →",
  "Sem despesas em": "Gider yok:", "Sem receitas em": "Gelir yok:", "Dia": "Gün",
  "Receita": "Gelir", "Despesa": "Gider", "Multa": "Ceza",
  "aguarda decisão do síndico": "yöneticinin kararını bekliyor",
  "cobrança(s) vencida(s) somando": "gecikmiş tahsilat, toplam",
  "sem responsável designado": "sorumlu atanmamış",
  "Pago": "Ödendi", "Parcial": "Kısmi", "Em aberto": "Açık", "Aguardando": "Beklemede", "Vencida": "Gecikmiş", "Emitida": "Düzenlendi",
  "Ocupada": "Dolu", "Alugada": "Kirada", "Vaga": "Boş", "Ativo": "Aktif", "Em teste": "Denemede", "Inadimplente": "Borçlu",
  "Prazo de defesa": "İtiraz süresi", "Multa aplicada": "Ceza uygulandı", "Advertência": "Uyarı",
  "Em andamento": "Devam ediyor", "Concluído": "Tamamlandı", "No condomínio": "Site içinde", "Saiu": "Ayrıldı", "Retirado": "Teslim alındı",
  "Ocorrência": "Olay", "Cancelada": "İptal edildi", "Cancelado": "İptal edildi", "Vendida": "Satıldı", "Reservada": "Rezerve", "Inativa": "Pasif",
  "Alta": "Yüksek", "Média": "Orta", "Baixa": "Düşük",
  "Todos os status": "Tüm durumlar", "Todos os papéis": "Tüm roller", "Todos": "Tümü", "Pagas": "Ödendi", "Emitidas": "Düzenlendi", "Vencidas": "Gecikmiş",
  "Abertos": "Açık", "Concluídos": "Tamamlandı",
  "Nome": "Ad", "Papel": "Rol", "Unidade": "Daire", "CPF/CNPJ": "Kimlik no", "Telefone": "Telefon", "Status": "Durum",
  "Data": "Tarih", "Tipo": "Tür", "Categoria": "Kategori", "Descrição": "Açıklama", "Valor": "Tutar",
  "Responsável": "Sorumlu", "Competência": "Dönem", "Vencimento": "Vade", "Plano": "Plan", "Mensalidade": "Aylık ücret", "Renovação": "Yenileme",
  "Evolução da receita recorrente": "Yinelenen gelirin gelişimi", "Planos": "Planlar",
  "Últimos comunicados": "Son duyurular", "Minha situação": "Durumum", "Cobranças da unidade": "Dairenin tahsilatları",
  "Unidade / apartamento": "Daire / apartman", "Cadastre unidades primeiro na tela Unidades.": "Önce \"Daireler\" ekranında daire kaydedin.",
  "Nenhuma cobrança para esta unidade ainda.": "Bu daire için henüz tahsilat yok.",
  "Toque para ler": "Okumak için dokunun",
  "Destino": "Hedef", "Todas as unidades (rateio pela fração)": "Tüm daireler (paya göre bölüştürülür)",
  "Valor da cobrança (R$)": "Tahsilat tutarı (R$)",
  "Será gerada 1 cobrança para": "Şunun için 1 tahsilat oluşturulacak:",
  "O morador verá o aviso no portal dele.": "Sakin, bildirimi kendi portalında görecek.",
  "Serão geradas": "Sistem şu kadar oluşturacak:", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "tahsilat (mali sorumlusu olan daireler), ideal paya göre bölüştürülmüş.",
  "Gerar cobrança": "Tahsilat oluştur", "Gerar": "Oluştur", "cobranças": "tahsilat",
  "Cobrança de": "Tahsilat:", "vencida": "(gecikmiş)", "Nova cobrança de": "Yeni tahsilat:",
  "vence em": "vade tarihi", "venceu em": "vadesi geçti:",
  "Multas da unidade": "Dairenin cezaları",
  "Você pode apresentar defesa até": "Şu tarihe kadar itiraz edebilirsiniz:",
  "Procure a administração do condomínio.": "Site yönetimine başvurun.",
  "Movimentação de hoje": "Bugünün hareketleri", "Nenhum chamado aqui": "Burada talep yok", "sem custo lançado": "maliyet girilmedi",
  "Nome fantasia *": "Ticari ad *", "Razão social": "Resmi unvan", "CNPJ *": "Şirket vergi no *", "Seu CPF (diretor) *": "Kimlik numaranız (direktör) *",
  "Porte": "Büyüklük", "Endereço completo *": "Tam adres *", "Nome fantasia": "Ticari ad", "CNPJ": "Şirket vergi no",
  "Inscrição municipal": "Belediye kaydı", "Torres / blocos": "Kuleler / bloklar", "Unidades / vagas": "Daireler / otoparklar",
  "Endereço completo": "Tam adres", "Administradora responsável": "Sorumlu yönetim şirketi", "Síndico atual": "Mevcut yönetici",
  "Diretor administrativo": "İdari direktör", "Início da gestão": "Görev başlangıcı", "Status do contrato SaaS": "SaaS sözleşme durumu",
  "Horário de silêncio": "Sessizlik saatleri", "Mudanças": "Taşınmalar", "Obras": "Tadilatlar", "Visitantes": "Ziyaretçiler", "Animais": "Evcil hayvanlar",
  "Áreas comuns": "Ortak alanlar", "Logo (upload)": "Logo (yükleme)", "Cor primária do portal": "Portalın ana rengi",
  "Responsável financeiro": "Mali sorumlu", "Fração ideal (%)": "İdeal pay (%)", "Área privativa (m²)": "Özel alan (m²)",
  "Vagas vinculadas": "Bağlı otoparklar", "Número": "Numara", "Bloco / torre": "Blok / kule", "Andar": "Kat",
  "Número (ou início do intervalo)": "Numara (veya aralık başlangıcı)", "Até o número (opcional)": "Şu numaraya kadar (isteğe bağlı)",
  "Ex.: 402, 1 ou 1D": "Örn.: 402, 1 veya 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Örn.: 100 veya 4D — boş bırakılırsa yalnızca bir tane oluşturur",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "Birden çok daireyi tek seferde oluşturmak için \"Şu numaraya kadar\" alanını doldurun: 1'den 100'e 1, 2… 100 oluşturur; 1D'den 4D'ye 1D, 2D, 3D ve 4D oluşturur. Blokta zaten var olan numaralar atlanır. Tür, kat, durum ve pay hepsine uygulanır.",
  "CPF ou CNPJ": "Kimlik no", "Papel no condomínio": "Sitedeki rol", "Unidade vinculada": "Bağlı daire",
  "Data de entrada": "Giriş tarihi", "Documento (upload)": "Belge (yükleme)",
  "Fundo de reserva": "Yedek fon", "Fundo de obras": "Tadilat fonu", "Valor (R$)": "Tutar (R$)",
  "Subcategoria / centro de custo": "Alt kategori / masraf merkezi", "Forma de pagamento": "Ödeme yöntemi", "Rateio": "Bölüştürme",
  "Nota fiscal (anexo)": "Fatura (ek)", "Aguardando pagamento": "Ödeme bekleniyor",
  "Valor total a ratear (R$)": "Bölüştürülecek toplam tutar (R$)", "Base de cálculo": "Hesaplama esası", "Canais de envio": "Gönderim kanalları",
  "Aplicadas em 2026": "2026'da uygulanan", "Em prazo de defesa": "İtiraz süresinde", "Arrecadado em multas": "Cezalardan tahsil edilen",
  "Categoria da infração": "İhlal kategorisi", "Unidade responsável": "Sorumlu daire", "Data e hora": "Tarih ve saat",
  "Tipo de penalidade": "Yaptırım türü", "Valor (se multa)": "Tutar (ceza ise)", "Prazo para defesa": "İtiraz süresi",
  "Base normativa": "Dayanak", "Descrição detalhada": "Ayrıntılı açıklama",
  "Provas (foto, vídeo, áudio ou documento)": "Kanıtlar (fotoğraf, video, ses veya belge)",
  "Destinatários": "Alıcılar", "Título": "Başlık", "Mensagem": "Mesaj", "Canais": "Kanallar",
  "Unidade (se aplicável)": "Daire (varsa)", "Conteúdo": "İçerik", "Prioridade": "Öncelik", "Prazo": "Süre",
  "Custo estimado": "Tahmini maliyet", "Fotos / vídeos": "Fotoğraf / video", "Descrição do problema": "Sorunun açıklaması",
  "Acessos registrados": "Kayıtlı girişler", "Visitantes no condomínio": "Sitedeki ziyaretçiler",
  "Entregas registradas": "Kayıtlı teslimatlar", "Vagas de visitante livres": "Boş ziyaretçi otoparkları",
  "Nome / empresa": "Ad / şirket", "Unidade de destino": "Hedef daire", "Janela de horário": "Zaman aralığı",
  "Veículo (opcional)": "Araç (isteğe bağlı)", "Condomínios ativos": "Aktif siteler",
  "Receita recorrente (MRR)": "Yinelenen gelir (MRR)", "Em período de teste": "Deneme süresinde",
  "Nova unidade": "Yeni daire", "Nova pessoa": "Yeni kişi", "Novo lançamento": "Yeni kayıt",
  "Gerar cobranças da competência": "Dönemin tahsilatlarını oluştur", "Registrar infração": "İhlal kaydet",
  "Novo documento timbrado": "Yeni antetli belge", "Abrir chamado de manutenção": "Bakım talebi aç",
  "Pré-autorizar entrada": "Girişi önceden onayla", "Novo acesso": "Yeni hesap", "Contratar novo condomínio": "Yeni site ekle",
  "Abrir chamado": "Talep aç",
  "Cancelar": "İptal", "Fechar": "Kapat", "Exportar": "Dışa aktar", "Lançamento": "Kayıt", "Pessoa": "Kişi",
  "Cadastrar unidade": "Daire kaydet", "Criar unidade": "Daire oluştur", "Cadastrar": "Kaydet",
  "Salvar alterações": "Değişiklikleri kaydet", "Gerar cobranças": "Tahsilat oluştur", "Gerar cobranças do mês": "Ayın tahsilatlarını oluştur",
  "Reenviar": "Yeniden gönder", "Baixar": "İndir", "Enviar por WhatsApp": "WhatsApp ile gönder", "Imprimir PDF": "PDF yazdır",
  "Enviar ao responsável": "Sorumluya gönder", "Cancelar multa": "Cezayı iptal et", "Aprovar (síndico)": "Onayla (yönetici)",
  "Enviar para aprovação": "Onaya gönder", "Ver": "Gör", "Publicar e enviar": "Yayınla ve gönder",
  "Criar documento timbrado": "Antetli belge oluştur", "Gerar PDF": "PDF oluştur",
  "Gerar QR de acesso": "Giriş QR'ı oluştur", "Registrar ocorrência": "Olay kaydet",
  "Autorizar e gerar QR": "Onayla ve QR oluştur", "Adicionar acesso": "Hesap ekle", "Remover": "Kaldır",
  "Criar acesso": "Hesap oluştur", "Novo cliente": "Yeni müşteri", "Bloquear acesso": "Erişimi engelle", "Abrir painel": "Paneli aç",
  "Iniciar implantação": "Kurulumu başlat", "Pagar": "Öde", "Copiar código": "Kodu kopyala", "Enviar chamado": "Talebi gönder",
  "Tentar novamente": "Tekrar dene", "Voltar e trocar perfil": "Geri dön ve rol değiştir", "Sair": "Çıkış",
  "Lançar e enviar para aprovação": "Kaydet ve onaya gönder", "Criar condomínio e começar": "Siteyi oluştur ve başla",
  "Salvando…": "Kaydediliyor…", "Criando…": "Oluşturuluyor…", "Gerando…": "Oluşturuluyor…", "Publicando…": "Yayınlanıyor…",
  "Abrindo…": "Açılıyor…", "Autorizando…": "Onaylanıyor…", "Enviando…": "Gönderiliyor…",
  "Boletos e QR": "Faturalar ve QR", "Extrato": "Hesap özeti",
  "Início": "Ana sayfa", "Pagamentos": "Ödemeler", "Avisos": "Duyurular",
  "Buscar por número, bloco ou responsável…": "Numara, blok veya sorumluya göre ara…",
  "Buscar por nome…": "Ada göre ara…", "Buscar lançamento…": "Kayıt ara…",
  "Buscar por unidade ou responsável…": "Daire veya sorumluya göre ara…",
  "Nenhuma unidade encontrada": "Daire bulunamadı",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Aramayı veya filtreleri değiştirin ya da bu sitenin ilk dairesini kaydedin.",
  "Nenhuma pessoa encontrada": "Kişi bulunamadı",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Karışıklığı önlemek için mal sahiplerini, kiracıları, çalışanları ve tedarikçileri ayrı rollerle kaydedin.",
  "Nenhum lançamento neste período": "Bu dönemde kayıt yok",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Kasayı takip etmeye başlamak için dönemin ilk gelir veya giderini kaydedin.",
  "Nenhuma cobrança nesta competência": "Bu dönemde tahsilat yok",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "Ayın tahsilatlarını oluşturun: sistem her daire için benzersiz bir Verum Pay QR kodu oluşturur ve portal, e-posta veya WhatsApp ile gönderir.",
  "Nenhum documento nesta categoria": "Bu kategoride belge yok",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Ceza, duyuru, tutanak ve makbuzların antetli belgeleri burada otomatik arşivlenir ve yıllarca saklanır.",
  "Nenhum acesso criado ainda": "Henüz hesap oluşturulmadı",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "Yönetici, muhasebe, yönetim şirketi ve sakinlerin giriş yapabilmesi için ilk e-posta ve şifreyi kaydedin.",
  "Não foi possível carregar os dados": "Veriler yüklenemedi",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Bağlantıyı kontrol edip tekrar deneyin. Sorun devam ederse destekle iletişime geçin.",
};
