/* Türkçe */
export default {
  "Condomínio": "Site", "Unidades": "Daireler", "Pessoas": "Kişiler", "Financeiro": "Finans",
  "Cobranças QR": "QR Tahsilat", "Multas": "Cezalar", "Comunicados": "Duyurular", "Documentos": "Belgeler",
  "Manutenção": "Bakım", "Portaria": "Danışma", "Gerenciar Acessos": "Erişim Yönetimi", 
  "Visão geral do condomínio em tempo real": "Sitenin gerçek zamanlı genel görünümü",
  "Cadastro-mãe: dados legais, gestão e regras internas": "Ana kayıt: yasal bilgiler, yönetim ve iç kurallar",

  /* subtítulos dinâmicos do cabeçalho */
  "unidade": "daire", "unidades": "daire", "bloco/torre": "blok/kule", "blocos/torres": "blok/kule",
  "pessoa cadastrada": "kayıtlı kişi", "pessoas cadastradas": "kayıtlı kişi",
  "aprovações do síndico ativas": "yönetici onayları etkin",
  "cobrança em aberto": "bekleyen tahsilat", "cobranças em aberto": "bekleyen tahsilat", "vencidas": "gecikmiş",
  "multa/advertência registrada": "kayıtlı ceza/uyarı", "multas/advertências registradas": "kayıtlı ceza/uyarı",
  "comunicado publicado": "yayımlanmış duyuru", "comunicados publicados": "yayımlanmış duyuru",
  "documento arquivado": "arşivlenmiş belge", "documentos arquivados": "arşivlenmiş belge",
  "chamado em aberto": "açık iş emri", "chamados em aberto": "açık iş emri",
  /* teste gratuito de 30 dias */
  "Ative seu teste gratuito de 30 dias — cadastre o cartão; nada será cobrado agora.": "30 günlük ücretsiz denemenizi başlatın — kartı kaydedin; şimdi ücret alınmaz.",
  "O período de avaliação terminou. Ative a assinatura para continuar.": "Deneme süresi sona erdi. Devam etmek için aboneliği etkinleştirin.",
  "Iniciar teste gratuito de 30 dias": "30 günlük ücretsiz denemeyi başlat",

  "A troca de plano durante o teste gratuito é cobrada imediatamente — aguarde o fim do teste para trocar.": "Deneme sırasında plan değişikliği anında ücretlendirilir — değiştirmek için denemenin bitmesini bekleyin.",
  "Teste gratuito — termina em": "Ücretsiz deneme — bitmesine", "dia(s)": "gün",
  "Depois, a cobrança é feita automaticamente no cartão cadastrado.": "Sonrasında ücret, kayıtlı karttan otomatik tahsil edilir.",

  "Tenho um código de ativação": "Bir etkinleştirme kodum var", "Código de ativação": "Etkinleştirme kodu",
  "Ativar": "Etkinleştir", "Ativando…": "Etkinleştiriliyor…",

  "Código aplicado. Se o acesso não liberar em instantes, use \"Já paguei — verificar\".": "Kod uygulandı. Erişim kısa sürede açılmazsa \"Já paguei — verificar\" düğmesini kullanın.",

  "Cancelar assinatura": "Aboneliği iptal et",
  "Cancelar a assinatura? O acesso continua até o fim do período já pago e nenhuma cobrança futura será feita.": "Abonelik iptal edilsin mi? Erişim, ödenmiş dönemin sonuna kadar devam eder ve gelecekte ücret alınmaz.",
  "Cancelamento agendado — o acesso continua até": "İptal planlandı — erişim şu tarihe kadar devam eder:",
  "Assinatura cancelada.": "Abonelik iptal edildi.",
  "Assinatura cancelada em": "Abonelik iptal tarihi:", "o acesso será desativado em": "erişim şu tarihte kapanacak:",
  "Nenhuma cobrança futura será feita.": "Gelecekte ücret alınmayacak.",
  "Acima da franquia do plano": "Plan dahilindeki limitin üzerinde",
  "o excedente é cobrado por unidade adicional na fatura da licença.": "aşım, lisans faturasında ek daire başına ücretlendirilir.",

  "Controle de acessos, entregas e ocorrências": "Giriş, teslimat ve olay yönetimi",

  "Notificações": "Bildirimler", "Alternar tema": "Tema değiştir", "Idioma": "Dil", "Perfil de acesso": "Erişim rolü",
  "Diretor": "Direktör", "Síndico": "Yönetici", "Tesouraria": "Muhasebe", "Administradora": "Yönetim şirketi", "Morador": "Sakin",
  "Visão estratégica, aprovações e auditoria": "Stratejik görünüm, onaylar ve denetim",
  "Operação, multas, comunicados e manutenção": "Operasyon, cezalar, duyurular ve bakım",
  "Financeiro, cobranças e conciliação": "Finans, tahsilat ve mutabakat",

  "Boletos, comprovantes, comunicados e chamados": "Faturalar, makbuzlar, duyurular ve talepler",
  "Gestão condominial premium · powered by Serve Now Global": "Premium site yönetimi · powered by Serve Now Global",
  "Criar acesso do diretor": "Direktör hesabı oluştur",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "Bu ilk giriş. Burada oluşturulan hesap şu rolle giriş için kullanılacak:",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Acessos.": ". Bu rol, diğer rollerin e-posta ve şifrelerini \"Erişim Yönetimi\"nde kaydedebilir.",
  "Nome completo": "Ad soyad", "E-mail": "E-posta", "Senha": "Şifre", "Confirmar senha": "Şifreyi onayla",
  "Criar conta e continuar": "Hesap oluştur ve devam et",
  "Já tem prédio cadastrado? Fazer login": "Kayıtlı bina var mı? Giriş yap",
  "Entrar como": "Şu rolle gir", "Trocar perfil": "Rol değiştir", "Voltar ao cadastro": "Kayda geri dön",
  "Entrar": "Giriş yap", "Verificando conta...": "Hesap doğrulanıyor...",
  "E-mail ou senha incorretos.": "E-posta veya şifre hatalı.",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Acessos.": "E-posta veya şifre hatalı. Direktörden hesabınızı \"Erişim Yönetimi\"nde kontrol etmesini isteyin.",

  "Não foi possível verificar sua conta agora.": "Hesabınız şu anda doğrulanamadı.",

  "As senhas não conferem.": "Şifreler eşleşmiyor.",
  "Nenhum acesso de": "Şu rol için hesap yok:",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Acessos.": ". Direktörden \"Erişim Yönetimi\"nde oluşturmasını isteyin.",
  "Tema claro": "Açık tema", "Tema escuro": "Koyu tema",

  "Seu nome": "Adınız", "voce@exemplo.com": "siz@ornek.com", "Repita a senha": "Şifreyi tekrarlayın",
  "Saldo em caixa": "Kasa bakiyesi", "Inadimplência": "Gecikme oranı", "Receitas de": "Gelirler:", "Despesas de": "Giderler:",
  "Nova cobrança": "Yeni tahsilat", "Novo gasto": "Yeni gider", "Nova multa": "Yeni ceza", "Novo comunicado": "Yeni duyuru", "Novo chamado": "Yeni talep",
  "Evolução financeira do mês — dia a dia": "Ayın mali gelişimi — gün gün",
  "Distribuição de receitas": "Gelir dağılımı", "Despesas por categoria": "Kategoriye göre giderler",
  "Inadimplência ao longo do tempo": "Zaman içinde gecikme", 
  "Aprovações pendentes": "Bekleyen onaylar", "Alertas do dia": "Günün uyarıları", "Ver todas →": "Tümünü gör →",
  "Sem despesas em": "Gider yok:", "Sem receitas em": "Gelir yok:", "Dia": "Gün",
  "Receita": "Gelir", "Despesa": "Gider", "Multa": "Ceza",
  "aguarda decisão do síndico": "yöneticinin kararını bekliyor",
  "cobrança(s) vencida(s) somando": "gecikmiş tahsilat, toplam",
  "sem responsável designado": "sorumlu atanmamış",
  "Pago": "Ödendi", "Entrada": "Tahsil edildi", "Parcial": "Kısmi", "Em aberto": "Açık", "Aguardando": "Beklemede", "Vencida": "Gecikmiş", "Emitida": "Düzenlendi",
  "Ocupada": "Dolu", "Alugada": "Kirada", "Vaga": "Boş", "Ativo": "Aktif", "Em teste": "Denemede", "Inadimplente": "Borçlu",
  "Prazo de defesa": "İtiraz süresi", "Multa aplicada": "Ceza uygulandı", "Advertência": "Uyarı",
  "Em andamento": "Devam ediyor", "Concluído": "Tamamlandı", "No condomínio": "Site içinde", "Saiu": "Ayrıldı", "Retirado": "Teslim alındı",
  "Ocorrência": "Olay", "Cancelada": "İptal edildi", "Cancelado": "İptal edildi", "Vendida": "Satıldı", "Reservada": "Rezerve", "Inativa": "Pasif",
  "Alta": "Yüksek", "Média": "Orta", "Baixa": "Düşük",
  "Todos os status": "Tüm durumlar", "Todos os papéis": "Tüm roller", "Todos": "Tümü", "Pagas": "Ödendi", "Emitidas": "Düzenlendi", "Vencidas": "Gecikmiş",
  "Abertos": "Açık", "Concluídos": "Tamamlandı",
  "Nome": "Ad", "Papel": "Rol", "Unidade": "Daire", "Telefone": "Telefon", "Status": "Durum",
  "Data": "Tarih", "Tipo": "Tür", "Categoria": "Kategori", "Descrição": "Açıklama", "Valor": "Tutar",
  "Responsável": "Sorumlu", "Competência": "Dönem", "Vencimento": "Vade", "Plano": "Plan", "Mensalidade": "Aylık ücret", "Mensal": "Aylık", "Anual": "Yıllık", "Anuidade": "Yıllık ücret", 
  "Planos": "Planlar",
  "Últimos comunicados": "Son duyurular", "Minha situação": "Durumum", "Cobranças da unidade": "Dairenin tahsilatları",
  "Unidade / apartamento": "Daire / apartman", "Cadastre unidades primeiro na tela Unidades.": "Önce \"Daireler\" ekranında daire kaydedin.",
  "Nenhuma cobrança para esta unidade ainda.": "Bu daire için henüz tahsilat yok.",
  "Toque para ler": "Okumak için dokunun",
  "Destino": "Hedef", "Todas as unidades (rateio pela fração)": "Tüm daireler (paya göre bölüştürülür)",

  "Será gerada 1 cobrança para": "Şunun için 1 tahsilat oluşturulacak:",
  "O morador verá o aviso no portal dele.": "Sakin, bildirimi kendi portalında görecek.",
  "Serão geradas": "Sistem şu kadar oluşturacak:", 
  "Gerar cobrança": "Tahsilat oluştur", "Gerar": "Oluştur", "cobranças": "tahsilat",
  "Cobrança de": "Tahsilat:", "vencida": "(gecikmiş)", "Nova cobrança de": "Yeni tahsilat:",
  "vence em": "vade tarihi", "venceu em": "vadesi geçti:",

  "Você pode apresentar defesa até": "Şu tarihe kadar itiraz edebilirsiniz:",
  "Procure a administração do condomínio.": "Site yönetimine başvurun.",
  "Movimentação de hoje": "Bugünün hareketleri", "Nenhum chamado aqui": "Burada talep yok", "sem custo lançado": "maliyet girilmedi",
  "Nome fantasia *": "Ticari ad *", "Razão social": "Resmi unvan", "CNPJ *": "Şirket vergi no *", "CPF ou RG do diretor *": "Kimlik numaranız (direktör) *",
  "Porte": "Büyüklük", "Endereço completo *": "Tam adres *", "Nome fantasia": "Ticari ad", "CNPJ": "Şirket vergi no",
  "Inscrição municipal": "Belediye kaydı", "Torres / blocos": "Kuleler / bloklar", "Unidades / vagas": "Daireler / otoparklar",
  "Endereço completo": "Tam adres", "Administradora responsável": "Sorumlu yönetim şirketi", "Síndico atual": "Mevcut yönetici",
  "Diretor administrativo": "İdari direktör", "Início da gestão": "Görev başlangıcı", 
  "Horário de silêncio": "Sessizlik saatleri", "Mudanças": "Taşınmalar", "Obras": "Tadilatlar", "Visitantes": "Ziyaretçiler", "Animais": "Evcil hayvanlar",
  "Áreas comuns": "Ortak alanlar", "Logo (upload)": "Logo (yükleme)", "Cor primária do portal": "Portalın ana rengi",
  "Responsável financeiro": "Mali sorumlu", "Área privativa (m²)": "Özel alan (m²)",
  "Vagas vinculadas": "Bağlı otoparklar", "Número": "Numara", "Bloco / torre": "Blok / kule", "Andar": "Kat",
  "Número (ou início do intervalo)": "Numara (veya aralık başlangıcı)", "Até o número (opcional)": "Şu numaraya kadar (isteğe bağlı)",
  "Ex.: 402, 1 ou 1D": "Örn.: 402, 1 veya 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "Örn.: 100 veya 4D — boş bırakılırsa yalnızca bir tane oluşturur",

  "Papel no condomínio": "Sitedeki rol", "Unidade vinculada": "Bağlı daire",
  "Data de entrada": "Giriş tarihi", "Documento (upload)": "Belge (yükleme)",
  "Fundo de reserva": "Yedek fon", "Fundo de obras": "Tadilat fonu", "Valor ($)": "Tutar ($)",
  "Subcategoria / centro de custo": "Alt kategori / masraf merkezi", "Forma de pagamento": "Ödeme yöntemi", "Rateio": "Bölüştürme",
  "Nota fiscal (anexo)": "Fatura (ek)", "Aguardando pagamento": "Ödeme bekleniyor",
  "Base de cálculo": "Hesaplama esası", "Canais de envio": "Gönderim kanalları",
  "Aplicadas em 2026": "2026'da uygulanan", "Em prazo de defesa": "İtiraz süresinde", "Arrecadado em multas": "Cezalardan tahsil edilen",
  "Categoria da infração": "İhlal kategorisi", "Unidade responsável": "Sorumlu daire", "Data e hora": "Tarih ve saat",
  "Tipo de penalidade": "Yaptırım türü", "Valor (se multa)": "Tutar (ceza ise)", "Prazo para defesa": "İtiraz süresi",
  "Base normativa": "Dayanak", "Descrição detalhada": "Ayrıntılı açıklama",
  "Provas (foto, vídeo, áudio ou documento)": "Kanıtlar (fotoğraf, video, ses veya belge)",
  "Destinatários": "Alıcılar", "Título": "Başlık", "Mensagem": "Mesaj", "Canais": "Kanallar",
  "Unidade (se aplicável)": "Daire (varsa)", "Prioridade": "Öncelik", "Prazo": "Süre",
  "Custo estimado": "Tahmini maliyet", "Fotos / vídeos": "Fotoğraf / video", "Descrição do problema": "Sorunun açıklaması",
  "Acessos registrados": "Kayıtlı girişler", "Visitantes no condomínio": "Sitedeki ziyaretçiler",
  "Entregas registradas": "Kayıtlı teslimatlar", "Vagas de visitante livres": "Boş ziyaretçi otoparkları",
  "Nome / empresa": "Ad / şirket", "Unidade de destino": "Hedef daire", "Janela de horário": "Zaman aralığı",
  "Veículo (opcional)": "Araç (isteğe bağlı)", 

  "Nova unidade": "Yeni daire", "Nova pessoa": "Yeni kişi", "Novo lançamento": "Yeni kayıt",
  "Gerar cobranças da competência": "Dönemin tahsilatlarını oluştur", "Registrar infração": "İhlal kaydet",
  "Novo documento timbrado": "Yeni antetli belge", "Abrir chamado de manutenção": "Bakım talebi aç",
  "Pré-autorizar entrada": "Girişi önceden onayla", "Novo acesso": "Yeni hesap", 
  "Abrir chamado": "Talep aç",
  "Cancelar": "İptal", "Fechar": "Kapat", "Exportar": "Dışa aktar", "Lançamento": "Kayıt", "Pessoa": "Kişi",
  "Cadastrar unidade": "Daire kaydet", "Criar unidade": "Daire oluştur", "Cadastrar": "Kaydet",
  "Salvar alterações": "Değişiklikleri kaydet", "Gerar cobranças": "Tahsilat oluştur", "Gerar cobranças do mês": "Ayın tahsilatlarını oluştur",
  "Reenviar": "Yeniden gönder", "Baixar": "İndir", "Enviar por WhatsApp": "WhatsApp ile gönder", "Imprimir PDF": "PDF yazdır",
  "Enviar ao responsável": "Sorumluya gönder", "Cancelar multa": "Cezayı iptal et", "Aprovar (síndico)": "Onayla (yönetici)",
  "Enviar para aprovação": "Onaya gönder", "Ver": "Gör", "Publicar e enviar": "Yayınla ve gönder",
  "Criar documento timbrado": "Antetli belge oluştur", "Gerar PDF": "PDF oluştur",
  "Gerar QR de acesso": "Giriş QR'ı oluştur", "Registrar ocorrência": "Olay kaydet",
  "Autorizar e gerar QR": "Onayla ve QR oluştur", "Adicionar acesso": "Hesap ekle", "Remover": "Kaldır",
  "Criar acesso": "Hesap oluştur", 
  "Pagar": "Öde", "Copiar código": "Kodu kopyala", 
  "Tentar novamente": "Tekrar dene", "Voltar e trocar perfil": "Geri dön ve rol değiştir", "Sair": "Çıkış",
  "Lançar e enviar para aprovação": "Kaydet ve onaya gönder", 
  "Salvando…": "Kaydediliyor…", "Criando…": "Oluşturuluyor…", "Gerando…": "Oluşturuluyor…", "Publicando…": "Yayınlanıyor…",
  "Abrindo…": "Açılıyor…", "Autorizando…": "Onaylanıyor…", "Enviando…": "Gönderiliyor…",
  "Extrato": "Hesap özeti",
  "Início": "Ana sayfa", "Pagamentos": "Ödemeler", "Avisos": "Duyurular",

  "Buscar por nome…": "Ada göre ara…", "Buscar lançamento…": "Kayıt ara…",
  "Buscar por unidade ou responsável…": "Daire veya sorumluya göre ara…",
  "Nenhuma unidade encontrada": "Daire bulunamadı",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "Aramayı veya filtreleri değiştirin ya da bu sitenin ilk dairesini kaydedin.",
  "Nenhuma pessoa encontrada": "Kişi bulunamadı",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "Karışıklığı önlemek için mal sahiplerini, kiracıları, çalışanları ve tedarikçileri ayrı rollerle kaydedin.",
  "Nenhum lançamento neste período": "Bu dönemde kayıt yok",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "Kasayı takip etmeye başlamak için dönemin ilk gelir veya giderini kaydedin.",
  "Nenhuma cobrança nesta competência": "Bu dönemde tahsilat yok",

  "Nenhum documento nesta categoria": "Bu kategoride belge yok",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "Ceza, duyuru, tutanak ve makbuzların antetli belgeleri burada otomatik arşivlenir ve yıllarca saklanır.",
  "Nenhum acesso criado ainda": "Henüz hesap oluşturulmadı",

  "Não foi possível carregar os dados": "Veriler yüklenemedi",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "Bağlantıyı kontrol edip tekrar deneyin. Sorun devam ederse destekle iletişime geçin.",
};
