/* 中文（简体） */
export default {
  "Condomínio": "小区", "Unidades": "单元", "Pessoas": "人员", "Financeiro": "财务",
  "Cobranças QR": "二维码收费", "Multas": "罚款", "Comunicados": "公告", "Documentos": "文件",
  "Manutenção": "维修", "Portaria": "门卫", "Gerenciar Emails": "管理邮箱", "Painel SaaS": "SaaS 面板",
  "Visão geral do condomínio em tempo real": "小区实时总览",
  "Cadastro-mãe: dados legais, gestão e regras internas": "主档案：法律信息、管理与内部规定",
  "96 unidades · 2 torres + térreo comercial": "96 个单元 · 2 栋楼 + 商业底层",
  "Papéis separados: proprietário, inquilino, funcionário e prestador": "角色分离：业主、租户、员工和服务商",
  "Competência 06/2026 · aprovações do síndico ativas": "账期 06/2026 · 物业经理审批已启用",
  "QR Code Verum Pay com baixa automática": "Verum Pay 二维码自动核销",
  "Fluxo com prova, defesa e aprovação": "含证据、申诉和审批的流程",
  "Envio por portal, e-mail e WhatsApp": "通过门户、邮件和 WhatsApp 发送",
  "Arquivo timbrado com retenção histórica": "带抬头的文件存档，长期保存",
  "Ordens de serviço por categoria e prioridade": "按类别和优先级的工单",
  "Controle de acessos, entregas e ocorrências": "出入、快递和事件管理",
  "Clientes, planos, licenças e implantação": "客户、套餐、许可与上线",
  "E-mails e senhas de acesso dos perfis síndico, tesouraria, administradora e morador": "物业经理、财务、管理公司和住户的登录邮箱与密码",
  "Notificações": "通知", "Alternar tema": "切换主题", "Idioma": "语言", "Perfil de acesso": "访问角色",
  "Diretor": "董事", "Síndico": "物业经理", "Tesouraria": "财务", "Administradora": "管理公司", "Morador": "住户",
  "Visão estratégica, aprovações e auditoria": "战略视图、审批与审计",
  "Operação, multas, comunicados e manutenção": "运营、罚款、公告与维修",
  "Financeiro, cobranças e conciliação": "财务、收费与对账",
  "Gestão SaaS: clientes, planos e licenças": "SaaS 管理：客户、套餐与许可",
  "Boletos, comprovantes, comunicados e chamados": "账单、凭证、公告与报修",
  "Gestão condominial premium · powered by Verum Pay": "高端小区管理 · powered by Verum Pay",
  "Criar acesso do diretor": "创建董事账号",
  "Este é o primeiro acesso. A conta criada aqui será usada para entrar como": "这是首次使用。在此创建的账号将用于以下角色登录：",
  ", que poderá cadastrar os e-mails e senhas dos demais perfis em Gerenciar Emails.": "，该角色可在“管理邮箱”中为其他角色设置邮箱和密码。",
  "Nome completo": "全名", "E-mail": "邮箱", "Senha": "密码", "Confirmar senha": "确认密码",
  "Criar conta e continuar": "创建账号并继续",
  "Já tem prédio cadastrado? Fazer login": "已注册楼宇？直接登录",
  "Entrar como": "登录身份", "Trocar perfil": "切换角色", "Voltar ao cadastro": "返回注册",
  "Entrar": "登录", "Verificando conta...": "正在验证账号...",
  "E-mail ou senha incorretos.": "邮箱或密码错误。",
  "E-mail ou senha incorretos. Peça ao diretor para conferir seu acesso em Gerenciar Emails.": "邮箱或密码错误。请让董事在“管理邮箱”中核对您的账号。",
  "Nenhum acesso de diretor foi encontrado neste dispositivo. Volte e crie o acesso do diretor.": "此设备上未找到董事账号。请返回并创建董事账号。",
  "Não foi possível verificar sua conta agora.": "暂时无法验证您的账号。",
  "A senha deve ter pelo menos 4 caracteres.": "密码至少需要 4 个字符。",
  "As senhas não conferem.": "两次输入的密码不一致。",
  "Nenhum acesso de": "尚无以下角色的账号：",
  "foi criado ainda. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "。请让董事在“管理邮箱”中创建。",
  "Tema claro": "浅色主题", "Tema escuro": "深色主题",
  "Nenhum acesso com este nome. Peça ao diretor para cadastrá-lo em Gerenciar Emails.": "没有此姓名的账号。请让董事在“管理邮箱”中登记。",
  "Senha incorreta para este nome.": "该姓名的密码不正确。",
  "Seu nome": "您的姓名", "voce@exemplo.com": "you@example.com", "Mínimo 4 caracteres": "至少 4 个字符", "Repita a senha": "再次输入密码",
  "Saldo em caixa": "现金余额", "Inadimplência": "欠费率", "Receitas de": "收入 —", "Despesas de": "支出 —",
  "Nova cobrança": "新收费", "Novo gasto": "新支出", "Nova multa": "新罚款", "Novo comunicado": "新公告", "Novo chamado": "新工单",
  "Evolução financeira do mês — dia a dia": "本月财务走势 — 逐日",
  "Distribuição de receitas": "收入分布", "Despesas por categoria": "按类别支出",
  "Inadimplência ao longo do tempo": "欠费率走势", "Atividade recente": "最近动态",
  "Aprovações pendentes": "待审批", "Alertas do dia": "今日提醒", "Ver todas →": "查看全部 →",
  "Sem despesas em": "无支出：", "Sem receitas em": "无收入：", "Dia": "日",
  "Receita": "收入", "Despesa": "支出", "Multa": "罚款",
  "aguarda decisão do síndico": "等待物业经理决定",
  "cobrança(s) vencida(s) somando": "笔逾期收费，合计",
  "sem responsável designado": "未指定负责人",
  "Pago": "已付", "Parcial": "部分", "Em aberto": "未结", "Aguardando": "等待中", "Vencida": "已逾期", "Emitida": "已开出",
  "Ocupada": "已入住", "Alugada": "已出租", "Vaga": "空置", "Ativo": "活跃", "Em teste": "试用中", "Inadimplente": "欠费",
  "Prazo de defesa": "申诉期", "Multa aplicada": "罚款已生效", "Advertência": "警告",
  "Em andamento": "进行中", "Concluído": "已完成", "No condomínio": "在小区内", "Saiu": "已离开", "Retirado": "已领取",
  "Ocorrência": "事件", "Cancelada": "已取消", "Cancelado": "已取消", "Vendida": "已出售", "Reservada": "已预订", "Inativa": "停用",
  "Alta": "高", "Média": "中", "Baixa": "低",
  "Todos os status": "所有状态", "Todos os papéis": "所有角色", "Todos": "全部", "Pagas": "已付", "Emitidas": "已开出", "Vencidas": "已逾期",
  "Abertos": "未处理", "Concluídos": "已完成",
  "Nome": "姓名", "Papel": "角色", "Unidade": "单元", "CPF/CNPJ": "证件号", "Telefone": "电话", "Status": "状态",
  "Data": "日期", "Tipo": "类型", "Categoria": "类别", "Descrição": "描述", "Valor": "金额",
  "Responsável": "负责人", "Competência": "账期", "Vencimento": "到期日", "Plano": "套餐", "Mensalidade": "月费", "Renovação": "续期",
  "Evolução da receita recorrente": "经常性收入走势", "Planos": "套餐",
  "Últimos comunicados": "最新公告", "Minha situação": "我的概况", "Cobranças da unidade": "本单元收费",
  "Unidade / apartamento": "单元 / 公寓", "Cadastre unidades primeiro na tela Unidades.": "请先在“单元”页面登记单元。",
  "Nenhuma cobrança para esta unidade ainda.": "该单元暂无收费。",
  "Toque para ler": "点击阅读",
  "Destino": "对象", "Todas as unidades (rateio pela fração)": "所有单元（按份额分摊）",
  "Valor da cobrança (R$)": "收费金额 (R$)",
  "Será gerada 1 cobrança para": "将生成 1 笔收费给",
  "O morador verá o aviso no portal dele.": "住户会在自己的门户中看到提醒。",
  "Serão geradas": "系统将生成", "cobranças (unidades com responsável financeiro), rateadas por fração ideal.": "笔收费（有财务负责人的单元），按理想份额分摊。",
  "Gerar cobrança": "生成收费", "Gerar": "生成", "cobranças": "笔收费",
  "Cobrança de": "收费", "vencida": "已逾期", "Nova cobrança de": "新收费",
  "vence em": "到期日", "venceu em": "已于该日到期：",
  "Multas da unidade": "本单元罚款",
  "Você pode apresentar defesa até": "您可在以下日期前提出申诉：",
  "Procure a administração do condomínio.": "请联系小区管理处。",
  "Movimentação de hoje": "今日出入记录", "Nenhum chamado aqui": "此处暂无工单", "sem custo lançado": "未录入费用",
  "Nome fantasia *": "商用名称 *", "Razão social": "法定名称", "CNPJ *": "企业税号 *", "Seu CPF (diretor) *": "您的证件号（董事）*",
  "Porte": "规模", "Endereço completo *": "完整地址 *", "Nome fantasia": "商用名称", "CNPJ": "企业税号",
  "Inscrição municipal": "市政登记号", "Torres / blocos": "楼栋", "Unidades / vagas": "单元 / 车位",
  "Endereço completo": "完整地址", "Administradora responsável": "负责的管理公司", "Síndico atual": "现任物业经理",
  "Diretor administrativo": "行政董事", "Início da gestão": "任期开始", "Status do contrato SaaS": "SaaS 合同状态",
  "Horário de silêncio": "静音时段", "Mudanças": "搬家", "Obras": "装修", "Visitantes": "访客", "Animais": "宠物",
  "Áreas comuns": "公共区域", "Logo (upload)": "标志（上传）", "Cor primária do portal": "门户主色",
  "Responsável financeiro": "财务负责人", "Fração ideal (%)": "理想份额 (%)", "Área privativa (m²)": "私有面积 (m²)",
  "Vagas vinculadas": "关联车位", "Número": "编号", "Bloco / torre": "楼栋", "Andar": "楼层",
  "Número (ou início do intervalo)": "编号（或区间起点）", "Até o número (opcional)": "至编号（可选）",
  "Ex.: 402, 1 ou 1D": "例：402、1 或 1D",
  "Ex.: 100 ou 4D — vazio cria só uma": "例：100 或 4D — 留空只创建一个",
  "Preencha \"Até o número\" para criar várias unidades de uma vez: 1 até 100 cria 1, 2… 100; 1D até 4D cria 1D, 2D, 3D e 4D. Números que já existem no bloco são pulados. Tipo, andar, status e fração valem para todas.": "填写“至编号”可一次创建多个单元：1 到 100 创建 1、2… 100；1D 到 4D 创建 1D、2D、3D 和 4D。楼栋中已存在的编号会被跳过。类型、楼层、状态和份额适用于全部。",
  "CPF ou CNPJ": "证件号", "Papel no condomínio": "在小区中的角色", "Unidade vinculada": "关联单元",
  "Data de entrada": "入住日期", "Documento (upload)": "文件（上传）",
  "Fundo de reserva": "储备基金", "Fundo de obras": "工程基金", "Valor (R$)": "金额 (R$)",
  "Subcategoria / centro de custo": "子类别 / 成本中心", "Forma de pagamento": "付款方式", "Rateio": "分摊",
  "Nota fiscal (anexo)": "发票（附件）", "Aguardando pagamento": "等待付款",
  "Valor total a ratear (R$)": "分摊总金额 (R$)", "Base de cálculo": "计算基准", "Canais de envio": "发送渠道",
  "Aplicadas em 2026": "2026 年已开出", "Em prazo de defesa": "申诉期内", "Arrecadado em multas": "罚款收入",
  "Categoria da infração": "违规类别", "Unidade responsável": "责任单元", "Data e hora": "日期和时间",
  "Tipo de penalidade": "处罚类型", "Valor (se multa)": "金额（如为罚款）", "Prazo para defesa": "申诉截止日",
  "Base normativa": "规章依据", "Descrição detalhada": "详细描述",
  "Provas (foto, vídeo, áudio ou documento)": "证据（照片、视频、音频或文件）",
  "Destinatários": "接收人", "Título": "标题", "Mensagem": "内容", "Canais": "渠道",
  "Unidade (se aplicável)": "单元（如适用）", "Conteúdo": "内容", "Prioridade": "优先级", "Prazo": "期限",
  "Custo estimado": "预计费用", "Fotos / vídeos": "照片 / 视频", "Descrição do problema": "问题描述",
  "Acessos registrados": "已记录出入", "Visitantes no condomínio": "小区内访客",
  "Entregas registradas": "已记录快递", "Vagas de visitante livres": "空闲访客车位",
  "Nome / empresa": "姓名 / 公司", "Unidade de destino": "目标单元", "Janela de horário": "时间段",
  "Veículo (opcional)": "车辆（可选）", "Condomínios ativos": "活跃小区",
  "Receita recorrente (MRR)": "经常性收入 (MRR)", "Em período de teste": "试用期内",
  "Nova unidade": "新单元", "Nova pessoa": "新人员", "Novo lançamento": "新记账",
  "Gerar cobranças da competência": "生成本期收费", "Registrar infração": "登记违规",
  "Novo documento timbrado": "新抬头文件", "Abrir chamado de manutenção": "创建维修工单",
  "Pré-autorizar entrada": "预授权进入", "Novo acesso": "新账号", "Contratar novo condomínio": "签约新小区",
  "Abrir chamado": "创建工单",
  "Cancelar": "取消", "Fechar": "关闭", "Exportar": "导出", "Lançamento": "记账", "Pessoa": "人员",
  "Cadastrar unidade": "登记单元", "Criar unidade": "创建单元", "Cadastrar": "登记",
  "Salvar alterações": "保存修改", "Gerar cobranças": "生成收费", "Gerar cobranças do mês": "生成本月收费",
  "Reenviar": "重新发送", "Baixar": "下载", "Enviar por WhatsApp": "通过 WhatsApp 发送", "Imprimir PDF": "打印 PDF",
  "Enviar ao responsável": "发送给负责人", "Cancelar multa": "取消罚款", "Aprovar (síndico)": "批准（物业经理）",
  "Enviar para aprovação": "提交审批", "Ver": "查看", "Publicar e enviar": "发布并发送",
  "Criar documento timbrado": "创建抬头文件", "Gerar PDF": "生成 PDF",
  "Gerar QR de acesso": "生成出入二维码", "Registrar ocorrência": "登记事件",
  "Autorizar e gerar QR": "授权并生成二维码", "Adicionar acesso": "添加账号", "Remover": "删除",
  "Criar acesso": "创建账号", "Novo cliente": "新客户", "Bloquear acesso": "封禁访问", "Abrir painel": "打开面板",
  "Iniciar implantação": "开始上线", "Pagar": "付款", "Copiar código": "复制代码", "Enviar chamado": "提交工单",
  "Tentar novamente": "重试", "Voltar e trocar perfil": "返回并切换角色", "Sair": "退出",
  "Lançar e enviar para aprovação": "记账并提交审批", "Criar condomínio e começar": "创建小区并开始",
  "Salvando…": "保存中…", "Criando…": "创建中…", "Gerando…": "生成中…", "Publicando…": "发布中…",
  "Abrindo…": "打开中…", "Autorizando…": "授权中…", "Enviando…": "发送中…",
  "Boletos e QR": "账单与二维码", "Extrato": "流水",
  "Início": "首页", "Pagamentos": "付款", "Avisos": "公告",
  "Buscar por número, bloco ou responsável…": "按编号、楼栋或负责人搜索…",
  "Buscar por nome…": "按姓名搜索…", "Buscar lançamento…": "搜索记账…",
  "Buscar por unidade ou responsável…": "按单元或负责人搜索…",
  "Nenhuma unidade encontrada": "未找到单元",
  "Ajuste a busca ou os filtros, ou cadastre a primeira unidade deste condomínio.": "调整搜索或筛选条件，或登记本小区的第一个单元。",
  "Nenhuma pessoa encontrada": "未找到人员",
  "Cadastre proprietários, inquilinos, funcionários e prestadores com papéis separados para evitar confusão operacional.": "以分离的角色登记业主、租户、员工和服务商，避免运营混乱。",
  "Nenhum lançamento neste período": "该期间无记账",
  "Registre a primeira receita ou despesa da competência para começar a acompanhar o caixa.": "录入本期第一笔收入或支出，开始跟踪现金流。",
  "Nenhuma cobrança nesta competência": "本期暂无收费",
  "Gere as cobranças do mês: o sistema cria um QR Code Verum Pay único por unidade e envia pelo portal, e-mail ou WhatsApp.": "生成本月收费：系统为每个单元创建唯一的 Verum Pay 二维码，并通过门户、邮件或 WhatsApp 发送。",
  "Nenhum documento nesta categoria": "此类别暂无文件",
  "Documentos timbrados de multas, comunicados, atas e recibos são arquivados automaticamente aqui, com retenção por anos.": "罚款、公告、会议记录和收据的抬头文件会自动存档于此，保存多年。",
  "Nenhum acesso criado ainda": "尚未创建任何账号",
  "Cadastre o primeiro e-mail e senha para que síndico, tesouraria, administradora e moradores consigam entrar.": "创建第一个邮箱和密码，让物业经理、财务、管理公司和住户能够登录。",
  "Não foi possível carregar os dados": "无法加载数据",
  "Verifique a conexão e tente novamente. Se o problema continuar, contate o suporte.": "请检查网络后重试。若问题持续，请联系客服。",
};
